
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__dbusadaptor_h__ADAPTOR_MARSHAL_H
#define __dbusxx__dbusadaptor_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace com {
namespace pelagicore {
namespace test {

class pelagicontaintestapp_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    pelagicontaintestapp_adaptor()
    : ::DBus::InterfaceAdaptor("com.pelagicore.test.pelagicontaintestapp")
    {
        register_method(pelagicontaintestapp_adaptor, Echo, _Echo_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument Echo_args[] = 
        {
            { "argument", "s", true },
            { 0, "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod pelagicontaintestapp_adaptor_methods[] = 
        {
            { "Echo", Echo_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod pelagicontaintestapp_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty pelagicontaintestapp_adaptor_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface pelagicontaintestapp_adaptor_interface = 
        {
            "com.pelagicore.test.pelagicontaintestapp",
            pelagicontaintestapp_adaptor_methods,
            pelagicontaintestapp_adaptor_signals,
            pelagicontaintestapp_adaptor_properties
        };
        return &pelagicontaintestapp_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::string Echo(const std::string& argument) = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Echo_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::string argin1; ri >> argin1;
        std::string argout1 = Echo(argin1);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
};

} } } 
#endif //__dbusxx__dbusadaptor_h__ADAPTOR_MARSHAL_H
