var annotated =
[
    [ "com", null, [
      [ "pelagicore", null, [
        [ "SoftwareContainerAgent", "classcom_1_1pelagicore_1_1_software_container_agent.html", "classcom_1_1pelagicore_1_1_software_container_agent" ]
      ] ]
    ] ],
    [ "softwarecontainer", null, [
      [ "BaseConfigStore", "classsoftwarecontainer_1_1_base_config_store.html", "classsoftwarecontainer_1_1_base_config_store" ],
      [ "CgroupsGateway", "classsoftwarecontainer_1_1_cgroups_gateway.html", "classsoftwarecontainer_1_1_cgroups_gateway" ],
      [ "CGroupsParser", "classsoftwarecontainer_1_1_c_groups_parser.html", "classsoftwarecontainer_1_1_c_groups_parser" ],
      [ "CleanUpHandler", "classsoftwarecontainer_1_1_clean_up_handler.html", "classsoftwarecontainer_1_1_clean_up_handler" ],
      [ "CommandJob", "classsoftwarecontainer_1_1_command_job.html", "classsoftwarecontainer_1_1_command_job" ],
      [ "Config", "classsoftwarecontainer_1_1_config.html", "classsoftwarecontainer_1_1_config" ],
      [ "ConfigDefaults", "classsoftwarecontainer_1_1_config_defaults.html", "classsoftwarecontainer_1_1_config_defaults" ],
      [ "ConfigDependencyError", "classsoftwarecontainer_1_1_config_dependency_error.html", "classsoftwarecontainer_1_1_config_dependency_error" ],
      [ "ConfigError", "classsoftwarecontainer_1_1_config_error.html", "classsoftwarecontainer_1_1_config_error" ],
      [ "ConfigLoaderAbstractInterface", "classsoftwarecontainer_1_1_config_loader_abstract_interface.html", "classsoftwarecontainer_1_1_config_loader_abstract_interface" ],
      [ "ConfigMandatoryError", "classsoftwarecontainer_1_1_config_mandatory_error.html", "classsoftwarecontainer_1_1_config_mandatory_error" ],
      [ "Container", "classsoftwarecontainer_1_1_container.html", "classsoftwarecontainer_1_1_container" ],
      [ "ContainerAbstractInterface", "classsoftwarecontainer_1_1_container_abstract_interface.html", "classsoftwarecontainer_1_1_container_abstract_interface" ],
      [ "DBusGateway", "classsoftwarecontainer_1_1_d_bus_gateway.html", "classsoftwarecontainer_1_1_d_bus_gateway" ],
      [ "DBusGatewayInstance", "classsoftwarecontainer_1_1_d_bus_gateway_instance.html", "classsoftwarecontainer_1_1_d_bus_gateway_instance" ],
      [ "DBusGatewayParser", "classsoftwarecontainer_1_1_d_bus_gateway_parser.html", "classsoftwarecontainer_1_1_d_bus_gateway_parser" ],
      [ "DefaultConfigStore", "classsoftwarecontainer_1_1_default_config_store.html", "classsoftwarecontainer_1_1_default_config_store" ],
      [ "DeviceNodeGateway", "classsoftwarecontainer_1_1_device_node_gateway.html", "classsoftwarecontainer_1_1_device_node_gateway" ],
      [ "DeviceNodeLogic", "classsoftwarecontainer_1_1_device_node_logic.html", "classsoftwarecontainer_1_1_device_node_logic" ],
      [ "DeviceNodeParser", "classsoftwarecontainer_1_1_device_node_parser.html", "classsoftwarecontainer_1_1_device_node_parser" ],
      [ "DirectoryCleanUpHandler", "classsoftwarecontainer_1_1_directory_clean_up_handler.html", "classsoftwarecontainer_1_1_directory_clean_up_handler" ],
      [ "EnvironmentGateway", "classsoftwarecontainer_1_1_environment_gateway.html", "classsoftwarecontainer_1_1_environment_gateway" ],
      [ "EnvironmentGatewayParser", "classsoftwarecontainer_1_1_environment_gateway_parser.html", "classsoftwarecontainer_1_1_environment_gateway_parser" ],
      [ "Executable", "classsoftwarecontainer_1_1_executable.html", "classsoftwarecontainer_1_1_executable" ],
      [ "FileCleanUpHandler", "classsoftwarecontainer_1_1_file_clean_up_handler.html", "classsoftwarecontainer_1_1_file_clean_up_handler" ],
      [ "FileConfigLoader", "classsoftwarecontainer_1_1_file_config_loader.html", "classsoftwarecontainer_1_1_file_config_loader" ],
      [ "FileGateway", "classsoftwarecontainer_1_1_file_gateway.html", "classsoftwarecontainer_1_1_file_gateway" ],
      [ "FileGatewayParser", "classsoftwarecontainer_1_1_file_gateway_parser.html", "classsoftwarecontainer_1_1_file_gateway_parser" ],
      [ "FileGatewaySettingStore", "classsoftwarecontainer_1_1_file_gateway_setting_store.html", "classsoftwarecontainer_1_1_file_gateway_setting_store" ],
      [ "FileToolkitWithUndo", "classsoftwarecontainer_1_1_file_toolkit_with_undo.html", "classsoftwarecontainer_1_1_file_toolkit_with_undo" ],
      [ "FilteredConfigStore", "classsoftwarecontainer_1_1_filtered_config_store.html", "classsoftwarecontainer_1_1_filtered_config_store" ],
      [ "FunctionJob", "classsoftwarecontainer_1_1_function_job.html", "classsoftwarecontainer_1_1_function_job" ],
      [ "Gateway", "classsoftwarecontainer_1_1_gateway.html", "classsoftwarecontainer_1_1_gateway" ],
      [ "GatewayConfiguration", "classsoftwarecontainer_1_1_gateway_configuration.html", "classsoftwarecontainer_1_1_gateway_configuration" ],
      [ "GatewayError", "classsoftwarecontainer_1_1_gateway_error.html", "classsoftwarecontainer_1_1_gateway_error" ],
      [ "GatewayParserError", "classsoftwarecontainer_1_1_gateway_parser_error.html", "classsoftwarecontainer_1_1_gateway_parser_error" ],
      [ "IPTableEntry", "classsoftwarecontainer_1_1_i_p_table_entry.html", "classsoftwarecontainer_1_1_i_p_table_entry" ],
      [ "JobAbstract", "classsoftwarecontainer_1_1_job_abstract.html", "classsoftwarecontainer_1_1_job_abstract" ],
      [ "JSONParser", "classsoftwarecontainer_1_1_j_s_o_n_parser.html", "classsoftwarecontainer_1_1_j_s_o_n_parser" ],
      [ "MandatoryConfigs", "classsoftwarecontainer_1_1_mandatory_configs.html", "classsoftwarecontainer_1_1_mandatory_configs" ],
      [ "MountCleanUpHandler", "classsoftwarecontainer_1_1_mount_clean_up_handler.html", "classsoftwarecontainer_1_1_mount_clean_up_handler" ],
      [ "Netlink", "classsoftwarecontainer_1_1_netlink.html", "classsoftwarecontainer_1_1_netlink" ],
      [ "NetworkGateway", "classsoftwarecontainer_1_1_network_gateway.html", "classsoftwarecontainer_1_1_network_gateway" ],
      [ "NetworkGatewayParser", "classsoftwarecontainer_1_1_network_gateway_parser.html", "classsoftwarecontainer_1_1_network_gateway_parser" ],
      [ "OverlaySyncCleanupHandler", "classsoftwarecontainer_1_1_overlay_sync_cleanup_handler.html", "classsoftwarecontainer_1_1_overlay_sync_cleanup_handler" ],
      [ "PulseGateway", "classsoftwarecontainer_1_1_pulse_gateway.html", "classsoftwarecontainer_1_1_pulse_gateway" ],
      [ "RecursiveCopy", "classsoftwarecontainer_1_1_recursive_copy.html", "classsoftwarecontainer_1_1_recursive_copy" ],
      [ "SignalConnectionsHandler", "classsoftwarecontainer_1_1_signal_connections_handler.html", "classsoftwarecontainer_1_1_signal_connections_handler" ],
      [ "SoftwareContainer", "classsoftwarecontainer_1_1_software_container.html", "classsoftwarecontainer_1_1_software_container" ],
      [ "SoftwareContainerAgent", "classsoftwarecontainer_1_1_software_container_agent.html", "classsoftwarecontainer_1_1_software_container_agent" ],
      [ "SoftwareContainerAgentAdaptor", "classsoftwarecontainer_1_1_software_container_agent_adaptor.html", "classsoftwarecontainer_1_1_software_container_agent_adaptor" ],
      [ "WaylandGateway", "classsoftwarecontainer_1_1_wayland_gateway.html", "classsoftwarecontainer_1_1_wayland_gateway" ],
      [ "Workspace", "classsoftwarecontainer_1_1_workspace.html", "classsoftwarecontainer_1_1_workspace" ]
    ] ],
    [ "ObservableProperty", "class_observable_property.html", "class_observable_property" ],
    [ "ObservableWritableProperty", "class_observable_writable_property.html", "class_observable_writable_property" ],
    [ "PProfiler", "class_p_profiler.html", "class_p_profiler" ],
    [ "SoftwareContainerAgentCommon", "class_software_container_agent_common.html", "class_software_container_agent_common" ],
    [ "SoftwareContainerAgentMessageHelper", "class_software_container_agent_message_helper.html", "class_software_container_agent_message_helper" ]
];