var annotated =
[
    [ "com", null, [
      [ "pelagicore", null, [
        [ "SoftwareContainerAgent", "classcom_1_1pelagicore_1_1_software_container_agent.html", "classcom_1_1pelagicore_1_1_software_container_agent" ]
      ] ]
    ] ],
    [ "softwarecontainer", null, [
      [ "BaseConfigStore", "classsoftwarecontainer_1_1_base_config_store.html", "classsoftwarecontainer_1_1_base_config_store" ],
      [ "CleanUpHandler", "classsoftwarecontainer_1_1_clean_up_handler.html", "classsoftwarecontainer_1_1_clean_up_handler" ],
      [ "CommandJob", "classsoftwarecontainer_1_1_command_job.html", "classsoftwarecontainer_1_1_command_job" ],
      [ "Config", "classsoftwarecontainer_1_1_config.html", "classsoftwarecontainer_1_1_config" ],
      [ "ConfigDependencyError", "classsoftwarecontainer_1_1_config_dependency_error.html", "classsoftwarecontainer_1_1_config_dependency_error" ],
      [ "ConfigError", "classsoftwarecontainer_1_1_config_error.html", "classsoftwarecontainer_1_1_config_error" ],
      [ "ConfigMandatoryError", "classsoftwarecontainer_1_1_config_mandatory_error.html", "classsoftwarecontainer_1_1_config_mandatory_error" ],
      [ "DefaultConfigStore", "classsoftwarecontainer_1_1_default_config_store.html", "classsoftwarecontainer_1_1_default_config_store" ],
      [ "FileToolkitWithUndo", "classsoftwarecontainer_1_1_file_toolkit_with_undo.html", "classsoftwarecontainer_1_1_file_toolkit_with_undo" ],
      [ "FilteredConfigStore", "classsoftwarecontainer_1_1_filtered_config_store.html", "classsoftwarecontainer_1_1_filtered_config_store" ],
      [ "FunctionJob", "classsoftwarecontainer_1_1_function_job.html", "classsoftwarecontainer_1_1_function_job" ],
      [ "Gateway", "classsoftwarecontainer_1_1_gateway.html", "classsoftwarecontainer_1_1_gateway" ],
      [ "GatewayError", "classsoftwarecontainer_1_1_gateway_error.html", "classsoftwarecontainer_1_1_gateway_error" ],
      [ "GatewayParserError", "classsoftwarecontainer_1_1_gateway_parser_error.html", "classsoftwarecontainer_1_1_gateway_parser_error" ],
      [ "JobAbstract", "classsoftwarecontainer_1_1_job_abstract.html", "classsoftwarecontainer_1_1_job_abstract" ],
      [ "JSONParser", "classsoftwarecontainer_1_1_j_s_o_n_parser.html", "classsoftwarecontainer_1_1_j_s_o_n_parser" ],
      [ "MandatoryConfigs", "classsoftwarecontainer_1_1_mandatory_configs.html", "classsoftwarecontainer_1_1_mandatory_configs" ],
      [ "SignalConnectionsHandler", "classsoftwarecontainer_1_1_signal_connections_handler.html", "classsoftwarecontainer_1_1_signal_connections_handler" ],
      [ "SoftwareContainer", "classsoftwarecontainer_1_1_software_container.html", "classsoftwarecontainer_1_1_software_container" ],
      [ "SoftwareContainerAgent", "classsoftwarecontainer_1_1_software_container_agent.html", "classsoftwarecontainer_1_1_software_container_agent" ],
      [ "SoftwareContainerAgentAdaptor", "classsoftwarecontainer_1_1_software_container_agent_adaptor.html", "classsoftwarecontainer_1_1_software_container_agent_adaptor" ],
      [ "Workspace", "classsoftwarecontainer_1_1_workspace.html", "classsoftwarecontainer_1_1_workspace" ]
    ] ],
    [ "CgroupsGateway", "class_cgroups_gateway.html", "class_cgroups_gateway" ],
    [ "CGroupsParser", "class_c_groups_parser.html", "class_c_groups_parser" ],
    [ "ConfigDefaults", "class_config_defaults.html", "class_config_defaults" ],
    [ "ConfigLoaderAbstractInterface", "class_config_loader_abstract_interface.html", "class_config_loader_abstract_interface" ],
    [ "Container", "class_container.html", "class_container" ],
    [ "ContainerAbstractInterface", "class_container_abstract_interface.html", "class_container_abstract_interface" ],
    [ "DBusGateway", "class_d_bus_gateway.html", "class_d_bus_gateway" ],
    [ "DBusGatewayInstance", "class_d_bus_gateway_instance.html", "class_d_bus_gateway_instance" ],
    [ "DBusGatewayParser", "class_d_bus_gateway_parser.html", "class_d_bus_gateway_parser" ],
    [ "DeviceNodeGateway", "class_device_node_gateway.html", "class_device_node_gateway" ],
    [ "DeviceNodeLogic", "class_device_node_logic.html", "class_device_node_logic" ],
    [ "DeviceNodeParser", "class_device_node_parser.html", "class_device_node_parser" ],
    [ "DirectoryCleanUpHandler", "class_directory_clean_up_handler.html", "class_directory_clean_up_handler" ],
    [ "EnvironmentGateway", "class_environment_gateway.html", "class_environment_gateway" ],
    [ "EnvironmentGatewayParser", "class_environment_gateway_parser.html", "class_environment_gateway_parser" ],
    [ "FileCleanUpHandler", "class_file_clean_up_handler.html", "class_file_clean_up_handler" ],
    [ "FileConfigLoader", "class_file_config_loader.html", "class_file_config_loader" ],
    [ "FileGateway", "class_file_gateway.html", "class_file_gateway" ],
    [ "FileGatewayParser", "class_file_gateway_parser.html", "class_file_gateway_parser" ],
    [ "FileGatewaySettingStore", "class_file_gateway_setting_store.html", "class_file_gateway_setting_store" ],
    [ "GatewayConfiguration", "class_gateway_configuration.html", "class_gateway_configuration" ],
    [ "IPTableEntry", "class_i_p_table_entry.html", "class_i_p_table_entry" ],
    [ "MountCleanUpHandler", "class_mount_clean_up_handler.html", "class_mount_clean_up_handler" ],
    [ "Netlink", "class_netlink.html", "class_netlink" ],
    [ "NetworkGateway", "class_network_gateway.html", "class_network_gateway" ],
    [ "NetworkGatewayParser", "class_network_gateway_parser.html", "class_network_gateway_parser" ],
    [ "ObservableProperty", "class_observable_property.html", "class_observable_property" ],
    [ "ObservableWritableProperty", "class_observable_writable_property.html", "class_observable_writable_property" ],
    [ "OverlaySyncCleanupHandler", "class_overlay_sync_cleanup_handler.html", "class_overlay_sync_cleanup_handler" ],
    [ "PProfiler", "class_p_profiler.html", "class_p_profiler" ],
    [ "PulseGateway", "class_pulse_gateway.html", "class_pulse_gateway" ],
    [ "RecursiveCopy", "class_recursive_copy.html", "class_recursive_copy" ],
    [ "SoftwareContainerAgentCommon", "class_software_container_agent_common.html", "class_software_container_agent_common" ],
    [ "SoftwareContainerAgentMessageHelper", "class_software_container_agent_message_helper.html", "class_software_container_agent_message_helper" ],
    [ "WaylandGateway", "class_wayland_gateway.html", "class_wayland_gateway" ]
];