softwarecontainer: softwarecontainer::Config Class Reference
softwarecontainer::Config Class Reference
Represents the SoftwareContainer main config.
#include <config.h>
Public Member Functions
Config (std::unique_ptr< ConfigLoaderAbstractInterface > loader, std::unique_ptr< ConfigDefaults > defaults, const std::map< std::string, std::string > &stringOptions=std::map< std::string, std::string >(), const std::map< std::string, int > &intOptions=std::map< std::string, int >(), const std::map< std::string, bool > &boolOptions=std::map< std::string, bool >())
Constructor.
Config (std::unique_ptr< ConfigLoaderAbstractInterface > loader, std::unique_ptr< ConfigDefaults > defaults, MandatoryConfigs &mandatory, std::vector< std::pair< std::string, std::vector< std::string >>> &dependencies, const std::map< std::string, std::string > &stringOptions=std::map< std::string, std::string >(), const std::map< std::string, int > &intOptions=std::map< std::string, int >(), const std::map< std::string, bool > &boolOptions=std::map< std::string, bool >())
TODO: Find a way to reuse parts of above comment.
std::string getStringValue (const std::string &group, const std::string &key) const
getStringValue Get a config value of type string
int getIntegerValue (const std::string &group, const std::string &key) const
getIntegerValue Get a config value of type integer
bool getBooleanValue (const std::string &group, const std::string &key) const
getBooleanValue Get a config value of type boolean
template<>
std::string getGlibValue (const std::string &group, const std::string &key) const
template<>
bool getGlibValue (const std::string &group, const std::string &key) const
template<>
int getGlibValue (const std::string &group, const std::string &key) const
Static Public Attributes
static const std::string SC_CONFIG_PATH_INITIAL_VALUE
static const int PRELOAD_COUNT_INITIAL_VALUE
static const bool KEEP_CONTAINERS_ALIVE_INITIAL_VALUE
static const int SHUTDOWN_TIMEOUT_INITIAL_VALUE
static const std::string SERVICE_MANIFEST_DIR_INITIAL_VALUE
static const std::string DEFAULT_SERVICE_MANIFEST_DIR_INITIAL_VALUE
static const bool USE_SESSION_BUS_INITIAL_VALUE
static const std::string SC_GROUP
static const std::string PRELOAD_COUNT_KEY
static const std::string KEEP_CONTAINERS_ALIVE_KEY
static const std::string USE_SESSION_BUS_KEY
static const std::string SHUTDOWN_TIMEOUT_KEY
static const std::string SHARED_MOUNTS_DIR_KEY
static const std::string LXC_CONFIG_PATH_KEY
static const std::string SERVICE_MANIFEST_DIR_KEY
static const std::string DEFAULT_SERVICE_MANIFEST_DIR_KEY
Detailed Description
Represents the SoftwareContainer main config.
A 'config' is a key-value pair, a 'config source' is somewhere that these key-value pairs are defined.
There are three different config sources:
Command line options
Main config file
Defaults
Some configs are optional and some are mandatory. A config can become mandatory if some other specified config depends on it. E.g. if an optional config in the main config file is uncommented and thus used, it might mean that other configs are mandatory as a consequence. A mandatory config must always be present in the command line options or in the main config file.
In the main config file, there are also 'confgig groups' which some might be mandatory and others not. Groups does not exist in the other config sources.
NOTE: It is an error if a mandatory config is not found in any config source when Config is initialized.
NOTE: It is en error if a dependency to a config is not found in any config source when Config is initialized.
NOTE: It is an error if a mandatory config group is not found in the main config file when Config is initialized.
Config sources have an order of priority: 1 - Command line options 2 - Main config file 3 - Defaults
The config sources as considered in the above order, i.e. first command line options etc. As soon as a config is found in a source, the value is returned and less prioritized sources are ignored.
NOTE: It is an error if a config is requested and not found in any source.
Definition at line 152 of file config.h.
Constructor & Destructor Documentation
softwarecontainer::Config::Config (std::unique_ptr< ConfigLoaderAbstractInterface > loader, std::unique_ptr< ConfigDefaults > defaults, const std::map< std::string, std::string > & stringOptions = std::map<std::string, std::string>(), const std::map< std::string, int > & intOptions = std::map<std::string, int>(), const std::map< std::string, bool > & boolOptions = std::map<std::string, bool>())
Constructor.
The optional params takes any potential explicitly set configs, e.g. read as command line options. These values will take precedence over any existing values with the same key in the static configuration.
If no configs are found among the explicit set configs or in the config file provided by the loader, the default values will be used as a last resort.
If no explicit configs are to be used, this Constructor can be called by passing only the 'loader' and 'defaults' arguments. Otherwise all parameters needs to be passed.
It is an error to not provide default configuration values. Not finding values in any of the other sources, i.e. explicit or config file, will not cause an error unless there are problems parsing.
Parameters
loader An interface to a loader which provides the underlying config to this class
defaults An interface to default configs
stringOptions A string:string map with config keys and corresponding values
intOptions A string:int map with config keys and corresponding values
boolOptions A string:bool map with config keys and corresponding values
Exceptions
ConfigError On error
Definition at line 49 of file config.cpp.
                                                            :
     m_loader(std::move(loader)),
     m_defaults(std::move(defaults)),
     m_stringOptions(stringOptions),
     m_intOptions(intOptions),
     m_boolOptions(boolOptions)
 {
     loadConfig();
 }
softwarecontainer::Config::Config (std::unique_ptr< ConfigLoaderAbstractInterface > loader, std::unique_ptr< ConfigDefaults > defaults, MandatoryConfigs & mandatory, std::vector< std::pair< std::string, std::vector< std::string >>> & dependencies, const std::map< std::string, std::string > & stringOptions = std::map<std::string, std::string>(), const std::map< std::string, int > & intOptions = std::map<std::string, int>(), const std::map< std::string, bool > & boolOptions = std::map<std::string, bool>())
TODO: Find a way to reuse parts of above comment.
Parameters
mandatory A reference to a MandatoryConfigs object that specifies what configs will be considered mandatory.
dependencies A list of dependee keys mapping to lists of dependency keys
Definition at line 63 of file config.cpp.
References softwarecontainer::MandatoryConfigs::configs(), getBooleanValue(), getIntegerValue(), getStringValue(), and softwarecontainer::MandatoryConfigs::groups().
                                                            :
     m_loader(std::move(loader)),
     m_defaults(std::move(defaults)),
     m_stringOptions(stringOptions),
     m_intOptions(intOptions),
     m_boolOptions(boolOptions)
 {
     loadConfig();
     /* Checking for mandatory config group is only relevant for the main config source
      */
     for (std::string group : mandatory.groups()) {
         log_debug() << "Checking for mandatory config group: \"" << group << "\"";
         if (!m_config->has_group(group)) {
             log_error() << "Missing mandatory config group: \"" + group + "\"";
             throw ConfigMandatoryError("Missing mandatory config group: \"" + group + "\"");
         }
     }
     /* Check that each mandatory config is present in one of the sources using the normal
      * retrieval methods in order to preserve the priority order.
      */
     for (std::tuple<std::string, std::string, ConfigType> config : mandatory.configs()) {
         std::string group = std::get<0>(config);
         std::string key = std::get<1>(config);
         ConfigType type = std::get<2>(config);
         log_debug() << "Checking for presence of mandatory config: \"" << key << "\"";
         /* TODO: The below only checks for presence, it should also add the values to something
          *       that can be used for retrieval later. */
         try {
             switch (type) {
                 case ConfigType::String:
                     getStringValue(group, key);
                     break;
                 case ConfigType::Integer:
                     getIntegerValue(group, key);
                     break;
                 case ConfigType::Boolean:
                     getBooleanValue(group, key);
                     break;
                 default:
                     break;
             }
         } catch (ConfigError &error) {
             log_error() << "Missing mandatory config: \"" << key << "\"";
             throw ConfigMandatoryError("Missing mandatory config: \"" + key + "\"");
         }
     }
 }
Member Function Documentation
std::string softwarecontainer::Config::getStringValue (const std::string & group, const std::string & key) const
getStringValue Get a config value of type string
Parameters
group The name of the config group the value belongs to
key The key for the config value
Returns
A string with the config value
Definition at line 129 of file config.cpp.
Referenced by Config(), and softwarecontainer::SoftwareContainerAgent::SoftwareContainerAgent().
 {
     return getValue<std::string>(group, key, m_stringOptions);
 }
int softwarecontainer::Config::getIntegerValue (const std::string & group, const std::string & key) const
getIntegerValue Get a config value of type integer
Parameters
group The name of the config group the value belongs to
key The key for the config value
Returns
An int with the config value
Definition at line 134 of file config.cpp.
Referenced by Config(), and softwarecontainer::SoftwareContainerAgent::SoftwareContainerAgent().
 {
     return getValue<int>(group, key, m_intOptions);
 }
bool softwarecontainer::Config::getBooleanValue (const std::string & group, const std::string & key) const
getBooleanValue Get a config value of type boolean
Parameters
group The name of the config group the value belongs to
key The key for the config value
Returns
A bool with the config value
Definition at line 139 of file config.cpp.
Referenced by Config(), and softwarecontainer::SoftwareContainerAgent::SoftwareContainerAgent().
 {
     return getValue<bool>(group, key, m_boolOptions);
 }
The documentation for this class was generated from the following files:
agent/src/config/config.h
agent/src/config/config.cpp