softwarecontainer: DBusGateway Class Reference
DBusGateway Class Reference
DBus Gateway takes care of spawning and killing the DBus proxies.
#include <dbusgateway.h>
Public Types
enum ProxyType { SessionProxy, SystemProxy }
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
typedef std::function< int()> ContainerFunction
Execute a function in the container.
Public Member Functions
DBusGateway (ProxyType type, const std::string &gatewayDir, const std::string &name)
Spawn the proxy and use the supplied path for the socket.
virtual ReturnCode readConfigElement (const json_t *element) override
Gateway specific parsing of config elements.
virtual bool activateGateway ()
Implements Gateway::activateGateway.
virtual bool teardownGateway () override
Implements Gateway::teardownGateway.
virtual const char * id ()
virtual bool setConfig (const std::string &config)
Configure this gateway according to the supplied JSON configuration string.
virtual bool activate ()
Applies any configuration set by setConfig()
virtual bool teardown ()
Restore system to the state prior to launching of gateway.
bool hasContainer ()
Check if the gateway has an associated container.
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Get a reference to the associated container.
void setContainer (std::shared_ptr< ContainerAbstractInterface > container)
Set the associated contaitner for this gateway.
bool isConfigured ()
Is the gateway configured or not?
bool isActivated ()
Is the gateway activated or not?
ReturnCode setEnvironmentVariable (const std::string &variable, const std::string &value)
ReturnCode executeInContainer (const std::string &cmd)
Execute the given command in the container.
ReturnCode executeInContainer (ContainerFunction func)
Static Public Attributes
static constexpr const char * ID
Protected Member Functions
bool read (const json_t *element, const char *key, std::string &result)
Reads a string from a JSON Object.
bool read (const json_t *element, const char *key, bool &result)
Reads a boolean from a JSON Object.
bool read (const json_t *element, const char *key, int &result)
Reads an integer from a JSON Object.
Protected Attributes
std::shared_ptr
< ContainerAbstractInterface > m_container
const char * m_id
GatewayState m_state
Static Protected Attributes
static constexpr const char * ENABLED_FIELD
static constexpr const char * XDG_RUNTIME_DIR_VARIABLE_NAME
Detailed Description
DBus Gateway takes care of spawning and killing the DBus proxies.
This module requires the 'dbus-proxy' binary to be available in the $PATH of the user executing softwarecontainer.
Definition at line 33 of file dbusgateway.h.
Member Typedef Documentation
typedef std::function<int ()> Gateway::ContainerFunction inherited
Execute a function in the container.
Definition at line 144 of file gateway.h.
Constructor & Destructor Documentation
DBusGateway::DBusGateway (ProxyType type, const std::string & gatewayDir, const std::string & name)
Spawn the proxy and use the supplied path for the socket.
Parameters
type SessionProxy or SystemProxy
Definition at line 24 of file dbusgateway.cpp.
     : Gateway(ID)
     , m_type(type)
 {
     m_state = GatewayState::CREATED;
     m_socket = gatewayDir
              + (m_type == SessionProxy ? "/sess_" : "/sys_")
              + name
              + ".sock";
     m_sessionBusConfig = json_array();
     m_systemBusConfig = json_array();
 }
Member Function Documentation
ReturnCode DBusGateway::readConfigElement (const json_t * element) override virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
ReturnCode FAILURE if an error was encountered while parsing, SUCCESS otherwise.
Implements Gateway.
Definition at line 50 of file dbusgateway.cpp.
 {
     bool has_session, has_system = false;
     // First, parse session bus configuration
     json_t *sessionConfig = json_object_get(element, SESSION_CONFIG);
     if (sessionConfig) {
         has_session = true;
         if (!json_is_array(sessionConfig)) {
             log_error() << "Value for " << SESSION_CONFIG << " is not an array";
             return ReturnCode::FAILURE;
         }
         for (unsigned int i = 0; i < json_array_size(sessionConfig); i++) {
             json_t *child = json_array_get(sessionConfig, i);
             // TODO: Error checking here, so that dbus-proxy can accept config
             json_array_append(m_sessionBusConfig, json_deep_copy(child));
         }
     }
     // Then, parse system bus configuration
     json_t *systemConfig = json_object_get(element, SYSTEM_CONFIG);
     if (systemConfig) {
         has_system = true;
         if (!json_is_array(systemConfig)) {
             log_error() << "Value for " << SYSTEM_CONFIG << " is not an array";
             return ReturnCode::FAILURE;
         }
         for (unsigned int i = 0; i < json_array_size(systemConfig); i++) {
             json_t *child = json_array_get(systemConfig, i);
             // TODO: Error checking here, so that dbus-proxy can accept config
             json_array_append(m_systemBusConfig, json_deep_copy(child));
         }
     }
     if (!has_session && !has_system) {
         log_error() << "Neither system nor session configuration was provided";
         return ReturnCode::FAILURE;
     }
     m_state = GatewayState::CONFIGURED;
     return ReturnCode::SUCCESS;
 }
bool DBusGateway::activateGateway () virtual
Implements Gateway::activateGateway.
Starts the dbus-proxy binary and feeds it the configuration set in setConfig(). This function will also set up the correct environment variables (DBUS_SESSION_BUS_ADDRESS when proxying the session bus, or DBUS_SYSTEM_BUS_ADDRESS when proxying the system bus).
This function requires a config to have been set using setConfig().
This function requires the 'dbus-proxy' binary to be available in $PATH
Returns
true when dbus-proxy was correctly execute and environment variable was correctly set false if dbus-proxy failed to execute or accept input on STDIN, or when environment variable could not be set.
Implements Gateway.
Definition at line 95 of file dbusgateway.cpp.
 {
     // set DBUS_{SESSION,SYSTEM}_BUS_ADDRESS env variable
     std::string variable = std::string("DBUS_")
                          + (m_type == SessionProxy ? "SESSION" : "SYSTEM")
                          + std::string("_BUS_ADDRESS");
     std::string value = "unix:path=/gateways/" + socketName();
     setEnvironmentVariable(variable, value);
     std::vector<std::string> commandVec = { "dbus-proxy"
                                           , m_socket
                                           , m_type == SessionProxy ? "session" : "system" };
     // Give the dbus-proxy access to the real dbus bus address.
     std::vector<std::string> envVec;
     if (char *envValue = getenv(variable.c_str())) {
         envVec.push_back(variable + "=" + envValue);
     } else if (m_type == SessionProxy) {
         log_error() << "Using DBus gateway in session mode"
                     << " and no " + variable + " set in host environment, dbus-proxy won't work";
         return false;
     } else {
         log_warn() << "Using DBus gateway in system mode"
                    << " and no " + variable + " set in host environment, this could be a problem";
     }
     if (!startDBusProxy(commandVec, envVec)) {
         return false;
     }
     // Write configuration
     json_t *jsonConfig = json_object();
     json_object_set(jsonConfig, SESSION_CONFIG, m_sessionBusConfig);
     json_object_set(jsonConfig, SYSTEM_CONFIG, m_systemBusConfig);
     std::string config = std::string(json_dumps(jsonConfig, JSON_COMPACT));
     return testDBusConnection(config);
 }
bool DBusGateway::teardownGateway () override virtual
Implements Gateway::teardownGateway.
This function will clean up processes launched and file descriptors opened during the lifetime of the gatway. Specifically it will close the connection to the dbus-proxy, and close the stdin and stdout pipes opened to dbus-proxy.
Returns
false if dbus-proxy could not be terminated, if stdin or stdout could not be closed, or if the socket created by the dbus-proxy could not be removed.
Implements Gateway.
Definition at line 203 of file dbusgateway.cpp.
 {
     bool success = true;
     if (m_pid != INVALID_PID) {
         log_debug() << "Killing dbus-proxy with pid " << m_pid;
         kill(m_pid, SIGKILL); // In some configurations, hangs if using SIGTERM instead
         waitpid(m_pid, nullptr, 0); // Wait until it exits
         Glib::spawn_close_pid(m_pid);
     } else {
         log_debug() << "dbus-proxy pid not set or already dead: " << m_pid;
     }
     if (access(m_socket.c_str(), F_OK) != -1) {
         if (unlink(m_socket.c_str()) == -1) {
             log_error() << "Could not remove " << m_socket << ": " << strerror(errno);
             success = false;
         }
     } else {
         log_debug() << "Socket not accessible, has it been removed already?";
     }
     return success;
 }
virtual const char* Gateway::id () inline virtual inherited
Returns
Returns the ID of the gateway
Definition at line 68 of file gateway.h.
Referenced by Gateway::activate(), softwarecontainer::SoftwareContainer::setGatewayConfigs(), and Gateway::teardown().
     {
         return m_id;
     }
bool Gateway::setConfig (const std::string & config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
true if config was successfully parsed false otherwise
Definition at line 25 of file gateway.cpp.
References Gateway::readConfigElement().
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
 {
     json_error_t error;
     json_t *root = json_loads(config.c_str(), 0, &error);
     if (!root) {
         log_error() << "Could not parse config: " << error.text;
         return false;
     }
     if (json_is_array(root)) {
         for(size_t i = 0; i < json_array_size(root); i++) {
             json_t *element = json_array_get(root, i);
             if (json_is_object(element)) {
                 if (isError(readConfigElement(element))) {
                     log_error() << "Could not read config element";
                     return false;
                 }
             } else {
                 log_error() << "json configuration is not an object";
                 return false;
             }
         }
     } else {
         log_error() << "Root JSON element is not an array";
         return false;
     }
     m_state = GatewayState::CONFIGURED;
     return true;
 }
bool Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
true upon successful application of configuration false otherwise
Definition at line 56 of file gateway.cpp.
References Gateway::hasContainer(), and Gateway::id().
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
{
     if (m_state != GatewayState::CONFIGURED) {
         log_warning() << "Activate was called on a gateway which is not in configured state: " << id();
         return false;
     }
     if (!hasContainer()) {
         log_warning() << "Activate was called on a gateway which has no associated container: " << id();
         return false;
     }
     return activateGateway();
 }
bool Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
true upon successful clean-up, false otherwise
Definition at line 70 of file gateway.cpp.
References Gateway::id().
{
     if (m_state != GatewayState::ACTIVATED) {
         log_warning() << "Teardown called on non-activated gateway " << id();
     }
     return teardownGateway();
 }
bool Gateway::hasContainer () inherited
Check if the gateway has an associated container.
Definition at line 78 of file gateway.cpp.
Referenced by Gateway::activate(), NetworkGateway::activateGateway(), and Gateway::executeInContainer().
 {
     return m_container != nullptr;
 }
std::shared_ptr< ContainerAbstractInterface > Gateway::getContainer () inherited
Get a reference to the associated container.
Definition at line 83 of file gateway.cpp.
Referenced by PulseGateway::activateGateway(), DeviceNodeGateway::activateGateway(), and Gateway::executeInContainer().
 {
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
void Gateway::setContainer (std::shared_ptr< ContainerAbstractInterface > container) inherited
Set the associated contaitner for this gateway.
Definition at line 89 of file gateway.cpp.
 {
     m_container = container;
 }
bool Gateway::isConfigured () inherited
Is the gateway configured or not?
Definition at line 94 of file gateway.cpp.
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool Gateway::isActivated () inherited
Is the gateway activated or not?
Definition at line 99 of file gateway.cpp.
 {
     return m_state >= GatewayState::ACTIVATED;
 }
ReturnCode Gateway::executeInContainer (const std::string & cmd) inherited
Execute the given command in the container.
Definition at line 117 of file gateway.cpp.
References Gateway::getContainer(), and Gateway::hasContainer().
 {
     if (hasContainer()) {
         return getContainer()->executeInContainer(cmd);
     } else {
         log_error() << "Can't execute in container from gateway without container";
         return ReturnCode::FAILURE;
     }
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, std::string & result) protected inherited
Reads a string from a JSON Object.
Tries to read a string value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the string could not be read, either due to the given object does not contain the given key or the given key did not hold a string, false will be returned and the result reference will not be changed.
Returns
True: If the string was successfully read.
False: If the string could not be read.
Definition at line 26 of file jsonparser.cpp.
Referenced by EnvironmentGateway::readConfigElement(), WaylandGateway::readConfigElement(), CgroupsGateway::readConfigElement(), FileGateway::readConfigElement(), PulseGateway::readConfigElement(), NetworkGateway::readConfigElement(), and DeviceNodeGateway::readConfigElement().
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         return false;
     }
     if (!json_is_string(value)) {
         log_error() << "json element is not a string";
         return false;
     }
     result = json_string_value(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, bool & result) protected inherited
Reads a boolean from a JSON Object.
Tries to read a boolean value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the boolean could not be read, either due to the given object does not contain the given key or the given key did not hold a boolean value, false will be returned and the result reference will not be changed.
Returns
True: If the boolean was successfully read.
False: If the boolean could not be read.
Definition at line 42 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         return false;
     }
     if (!json_is_boolean(value)) {
         log_error() << "json element is not a boolean";
         return false;
     }
     result = json_is_true(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, int & result) protected inherited
Reads an integer from a JSON Object.
Tries to read an integer value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the integer could not be read, either due to the given object does not contain the given key or the given key did not hold an integer value, false will be returned and the result reference will not be changed.
Returns
True: If the integer was successfully read.
False: If the integer could not be read.
Definition at line 58 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         return false;
     }
     if (!json_is_integer(value)) {
         log_error() << "json element is not an integer";
         return false;
     }
     result = json_integer_value(value);
     return true;
 }
The documentation for this class was generated from the following files:
src/gateway/dbusgateway.h
src/gateway/dbusgateway.cpp