softwarecontainer: softwarecontainer::JSONParser Class Reference
softwarecontainer::JSONParser Class Reference final
Convenience layer for the Jansson JSON parser.
#include <jsonparser.h>
Static Public Member Functions
static bool readOptional (const json_t *element, const char *key, std::string &result)
Reads an optional value from a JSON object.
static bool readOptional (const json_t *element, const char *key, bool &result)
static bool readOptional (const json_t *element, const char *key, int &result)
static bool read (const json_t *element, const char *key, std::string &result)
Reads a string from a JSON Object.
static bool read (const json_t *element, const char *key, bool &result)
Reads a boolean from a JSON Object.
static bool read (const json_t *element, const char *key, int &result)
Reads an integer from a JSON Object.
static bool hasKey (const json_t *element, const char *key)
Checks if a given JSON object contains a certain key.
Detailed Description
Convenience layer for the Jansson JSON parser.
This class provides convenience functions that handles commonly used operations using the Janssson JSON parser.
Definition at line 32 of file jsonparser.h.
Member Function Documentation
bool softwarecontainer::JSONParser::readOptional (const json_t * element, const char * key, std::string & result) static
Reads an optional value from a JSON object.
This differs from the read functions in that it return true instead of false if the key was not found, so the only way it returns false is if the key was of bad type or could not be parsed (but existed)
Returns
false if the key existed and was of bad type
true otherwise
Definition at line 24 of file jsonparser.cpp.
References hasKey(), and read().
 {
     if (!hasKey(element, key)) {
         return true;
     }
     return read(element, key, result);
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, std::string & result) static
Reads a string from a JSON Object.
Tries to read a string value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the string could not be read, either due to the given object does not contain the given key or the given key did not hold a string, false will be returned and the result reference will not be changed.
Returns
True: If the string was successfully read.
False: If the string could not be read.
Definition at line 51 of file jsonparser.cpp.
Referenced by softwarecontainer::NetworkGatewayParser::parseNetworkGatewayConfiguration(), softwarecontainer::WaylandGateway::readConfigElement(), softwarecontainer::PulseGateway::readConfigElement(), and readOptional().
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_warning() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_string(value)) {
         log_error() << "json element is not a string";
         return false;
     }
     result = json_string_value(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, bool & result) static
Reads a boolean from a JSON Object.
Tries to read a boolean value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the boolean could not be read, either due to the given object does not contain the given key or the given key did not hold a boolean value, false will be returned and the result reference will not be changed.
Returns
True: If the boolean was successfully read.
False: If the boolean could not be read.
Definition at line 68 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_warning() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_boolean(value)) {
         log_error() << "json element is not a boolean";
         return false;
     }
     result = json_is_true(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, int & result) static
Reads an integer from a JSON Object.
Tries to read an integer value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the integer could not be read, either due to the given object does not contain the given key or the given key did not hold an integer value, false will be returned and the result reference will not be changed.
Returns
True: If the integer was successfully read.
False: If the integer could not be read.
Definition at line 85 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_warning() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_integer(value)) {
         log_error() << "json element is not an integer";
         return false;
     }
     result = json_integer_value(value);
     return true;
 }
bool softwarecontainer::JSONParser::hasKey (const json_t * element, const char * key) static
Checks if a given JSON object contains a certain key.
Definition at line 102 of file jsonparser.cpp.
Referenced by readOptional().
 {
     return json_object_get(element, key) != NULL;
 }
The documentation for this class was generated from the following files:
common/jsonparser.h
common/jsonparser.cpp