softwarecontainer: NetworkGatewayParser Class Reference
NetworkGatewayParser Class Reference
Public Member Functions
ReturnCode parseNetworkGatewayConfiguration (const json_t *element, IPTableEntry &e)
Parses NetworkGateway configuration into IPTableEntry.
Static Protected Member Functions
static bool read (const json_t *element, const char *key, std::string &result)
Reads a string from a JSON Object.
static bool read (const json_t *element, const char *key, bool &result)
Reads a boolean from a JSON Object.
static bool read (const json_t *element, const char *key, int &result)
Reads an integer from a JSON Object.
Detailed Description
Definition at line 27 of file networkgatewayparser.h.
Member Function Documentation
ReturnCode NetworkGatewayParser::parseNetworkGatewayConfiguration (const json_t * element, IPTableEntry & e)
Parses NetworkGateway configuration into IPTableEntry.
Parameters
element JSON string containing configuration
e rule representing corresponding network rules
Returns
ReturnCode::SUCCESS if the rule is successfully parsed
ReturnCode::FAILURE otherwise.
Definition at line 21 of file networkgatewayparser.cpp.
References softwarecontainer::JSONParser::read().
Referenced by NetworkGateway::readConfigElement().
 {
     std::string chain;
     if (!read(element, "type", chain)) {
         log_error() << "No type specified in network config.";
         return ReturnCode::FAILURE;
     }
     if ("INCOMING" == chain) {
         e.m_type = "INPUT";
     } else if ("OUTGOING" == chain) {
         e.m_type = "OUTPUT";
     } else {
         log_error() << e.m_type << " is not a valid type ('INCOMING' or 'OUTGOING')";
         return ReturnCode::FAILURE;
     }
     int p;
     if (!read(element, "priority", p)) {
         log_error() << "No priority specified in network config.";
         return ReturnCode::FAILURE;
     }
     e.m_priority = p;
     if (e.m_priority < 1) {
         log_error() << "Priority can not be less than 1 but is " << e.m_priority;
         return ReturnCode::FAILURE;
     }
     const json_t *rules = json_object_get(element, "rules");
     if (rules == nullptr) {
         log_error() << "No rules specified";
         return ReturnCode::FAILURE;
     }
     if (!json_is_array(rules)) {
         log_error() << "Rules not specified as an array";
         return ReturnCode::FAILURE;
     }
     size_t ix;
     json_t *val;
     json_array_foreach(rules, ix, val) {
         if (json_is_object(val)) {
             if (isError(parseRule(val, e.m_rules))) {
                 log_error() << "Could not parse rule config";
                 return ReturnCode::FAILURE;
             }
         } else {
             log_error() << "formatting of rules array is incorrect.";
             return ReturnCode::FAILURE;
         }
     }
     std::string readTarget;
     if (!read(element, "default", readTarget)) {
         log_error() << "No default target specified or default target is not a string.";
         return ReturnCode::FAILURE;
     }
     e.m_defaultTarget = parseTarget(readTarget);
     if (e.m_defaultTarget == IPTableEntry::Target::INVALID_TARGET
         || e.m_defaultTarget == IPTableEntry::Target::REJECT) {
         log_error() << "Default target '" << readTarget << "' is not a supported target";
         return ReturnCode::FAILURE;
     }
     return ReturnCode::SUCCESS;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, std::string & result) static inherited
Reads a string from a JSON Object.
Tries to read a string value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the string could not be read, either due to the given object does not contain the given key or the given key did not hold a string, false will be returned and the result reference will not be changed.
Returns
True: If the string was successfully read.
False: If the string could not be read.
Definition at line 24 of file jsonparser.cpp.
Referenced by parseNetworkGatewayConfiguration(), EnvironmentGateway::readConfigElement(), WaylandGateway::readConfigElement(), CgroupsGateway::readConfigElement(), FileGateway::readConfigElement(), PulseGateway::readConfigElement(), DeviceNodeGateway::readConfigElement(), and softwarecontainer::SoftwareContainerAgent::readConfigElement().
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_error() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_string(value)) {
         log_error() << "json element is not a string";
         return false;
     }
     result = json_string_value(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, bool & result) static inherited
Reads a boolean from a JSON Object.
Tries to read a boolean value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the boolean could not be read, either due to the given object does not contain the given key or the given key did not hold a boolean value, false will be returned and the result reference will not be changed.
Returns
True: If the boolean was successfully read.
False: If the boolean could not be read.
Definition at line 41 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_error() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_boolean(value)) {
         log_error() << "json element is not a boolean";
         return false;
     }
     result = json_is_true(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, int & result) static inherited
Reads an integer from a JSON Object.
Tries to read an integer value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the integer could not be read, either due to the given object does not contain the given key or the given key did not hold an integer value, false will be returned and the result reference will not be changed.
Returns
True: If the integer was successfully read.
False: If the integer could not be read.
Definition at line 58 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_error() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_integer(value)) {
         log_error() << "json element is not an integer";
         return false;
     }
     result = json_integer_value(value);
     return true;
 }
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/networkgatewayparser.h
libsoftwarecontainer/src/gateway/networkgatewayparser.cpp