softwarecontainer: softwarecontainer::DBusGatewayInstance Class Reference
softwarecontainer::DBusGatewayInstance Class Reference
DBus Gateway takes care of spawning and killing the DBus proxies.
#include <dbusgatewayinstance.h>
Public Types
enum ProxyType { SessionProxy, SystemProxy }
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
Public Member Functions
DBusGatewayInstance (ProxyType type, const std::string &gatewayDir, std::shared_ptr< ContainerAbstractInterface > container)
Spawn the proxy and use the supplied path for the socket.
virtual bool readConfigElement (const json_t *element) override
Gateway specific parsing of config elements.
virtual bool activateGateway ()
Implements Gateway::activateGateway.
virtual bool teardownGateway () override
Implements Gateway::teardownGateway.
virtual const char * id ()
virtual bool setConfig (const json_t *config)
Configure this gateway according to the supplied JSON configuration string.
virtual bool activate ()
Applies any configuration set by setConfig()
virtual bool teardown ()
Restore system to the state prior to launching of gateway.
virtual bool isConfigured ()
Is the gateway configured or not?
virtual bool isActivated ()
Is the gateway activated or not?
Static Public Attributes
static constexpr const char * ID
static constexpr const char * SESSION_CONFIG
static constexpr const char * SYSTEM_CONFIG
Protected Member Functions
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Get a handle to the associated container.
bool setEnvironmentVariable (const std::string &variable, const std::string &value)
Set an environment variable in the associated container.
Detailed Description
DBus Gateway takes care of spawning and killing the DBus proxies.
This module requires the 'dbus-proxy' binary to be available in the $PATH of the user executing softwarecontainer.
Definition at line 32 of file dbusgatewayinstance.h.
Constructor & Destructor Documentation
softwarecontainer::DBusGatewayInstance::DBusGatewayInstance (ProxyType type, const std::string & gatewayDir, std::shared_ptr< ContainerAbstractInterface > container)
Spawn the proxy and use the supplied path for the socket.
Parameters
type SessionProxy or SystemProxy
Definition at line 30 of file dbusgatewayinstance.cpp.
References softwarecontainer::Gateway::id().
                                                                                               :
     Gateway(ID, container),
     m_type(type)
 {
     std::string name = container->id();
     std::string socketName = (m_type == SessionProxy ? "sess_" : "sys_") + name + ".sock";
     m_socket = buildPath(gatewayDir, socketName);
     // Write configuration
     m_entireConfig = json_object();
     m_busConfig = json_array();
     const char* unusedTypeStr;
     if (m_type == SessionProxy) {
         typeStr = SESSION_CONFIG;
         unusedTypeStr = SYSTEM_CONFIG;
     } else {
         typeStr = SYSTEM_CONFIG;
         unusedTypeStr = SESSION_CONFIG;
     }
     json_object_set(m_entireConfig, typeStr, m_busConfig);
     // Send an empty array as config for the irrelevant proxy type
     json_t* emptyArray = json_array();
     json_object_set(m_entireConfig, unusedTypeStr, emptyArray);
 }
Member Function Documentation
bool softwarecontainer::DBusGatewayInstance::readConfigElement (const json_t * element) override virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
false if an error was encountered while parsing, true otherwise.
Implements softwarecontainer::Gateway.
Definition at line 69 of file dbusgatewayinstance.cpp.
 {
     DBusGatewayParser parser;
     // TODO: This should really be done with exceptions instead and json_t* as return type.
     if (!parser.parseDBusConfig(element, typeStr, m_busConfig)) {
         log_error() << "Failed to parse DBus configuration element";
         return false;
     }
     return true;
 }
bool softwarecontainer::DBusGatewayInstance::activateGateway () virtual
Implements Gateway::activateGateway.
Starts the dbus-proxy binary and feeds it the configuration set in setConfig(). This function will also set up the correct environment variables (DBUS_SESSION_BUS_ADDRESS when proxying the session bus, or DBUS_SYSTEM_BUS_ADDRESS when proxying the system bus).
This function requires a config to have been set using setConfig().
This function requires the 'dbus-proxy' binary to be available in $PATH
Returns
true when dbus-proxy was correctly execute and environment variable was correctly set false if dbus-proxy failed to execute or accept input on STDIN, or when environment variable could not be set.
Implements softwarecontainer::Gateway.
Definition at line 82 of file dbusgatewayinstance.cpp.
References softwarecontainer::Gateway::getContainer().
 {
     // set DBUS_{SESSION,SYSTEM}_BUS_ADDRESS env variable
     std::string variable = std::string("DBUS_")
                          + (m_type == SessionProxy ? "SESSION" : "SYSTEM")
                          + std::string("_BUS_ADDRESS");
     std::string value = "unix:path=" + buildPath("/gateways", socketName());
     getContainer()->setEnvironmentVariable(variable, value);
     std::vector<std::string> commandVec = { "dbus-proxy"
                                           , m_socket
                                           , m_type == SessionProxy ? "session" : "system" };
     // Give the dbus-proxy access to the real dbus bus address.
     std::vector<std::string> envVec;
     bool hasEnvVar = false;
     std::string envValue = Glib::getenv(variable, hasEnvVar);
     if (!hasEnvVar) {
         if (m_type == SessionProxy) {
             log_error() << "Using DBus gateway in session mode"
                         << " and no " + variable + " set in host environment, dbus-proxy won't work";
             return false;
         } else {
             log_warn() << "Using DBus gateway in system mode"
                        << " and no " + variable + " set in host environment, this could be a problem";
         }
     } else {
         envVec.push_back(variable + "=" + envValue);
     }
     if (!startDBusProxy(commandVec, envVec)) {
         return false;
     }
     // Dump to string and clean up
     char *config_c = json_dumps(m_entireConfig, JSON_COMPACT);
     std::string config = std::string(config_c);
     free(config_c);
     return testDBusConnection(config);
 }
bool softwarecontainer::DBusGatewayInstance::teardownGateway () override virtual
Implements Gateway::teardownGateway.
This function will clean up processes launched and file descriptors opened during the lifetime of the gatway. Specifically it will close the connection to the dbus-proxy, and close the stdin and stdout pipes opened to dbus-proxy.
Returns
false if dbus-proxy could not be terminated, if stdin or stdout could not be closed, or if the socket created by the dbus-proxy could not be removed.
Implements softwarecontainer::Gateway.
Definition at line 195 of file dbusgatewayinstance.cpp.
 {
     bool success = true;
     if (nullptr != m_entireConfig) {
         json_decref(m_entireConfig);
         m_entireConfig = nullptr;
     }
     if (m_pid != INVALID_PID) {
         log_debug() << "Killing dbus-proxy with pid " << m_pid;
         kill(m_pid, SIGKILL); // In some configurations, hangs if using SIGTERM instead
         waitpid(m_pid, nullptr, 0); // Wait until it exits
         Glib::spawn_close_pid(m_pid);
     } else {
         log_debug() << "dbus-proxy pid not set or already dead: " << m_pid;
     }
     if (access(m_socket.c_str(), F_OK) != -1) {
         if (unlink(m_socket.c_str()) == -1) {
             log_error() << "Could not remove " << m_socket << ": " << strerror(errno);
             success = false;
         }
     } else {
         // TODO: Seems weird that this would ever happen. Seems like a severe error.
         log_debug() << "Socket not accessible, has it been removed already?";
     }
     return success;
 }
virtual const char* softwarecontainer::Gateway::id () inline virtual inherited
Returns
Returns the ID of the gateway
Definition at line 83 of file gateway.h.
Referenced by softwarecontainer::Gateway::activate(), DBusGatewayInstance(), softwarecontainer::Gateway::setConfig(), and softwarecontainer::Gateway::teardown().
     {
         return m_id;
     }
bool softwarecontainer::Gateway::setConfig (const json_t * config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
true if config was successfully parsed, false otherwise
Exceptions
GatewayError If called on an already activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 24 of file gateway.cpp.
References softwarecontainer::Gateway::id(), and softwarecontainer::Gateway::readConfigElement().
Referenced by softwarecontainer::DBusGateway::setConfig().
 {
     if (m_state == GatewayState::ACTIVATED) {
         log_error() << "Can not configure a gateway that is already activated: " << id();
         throw GatewayError("Gateway already activated");
     }
     if (!json_is_array(config)) {
         log_error() << "Root JSON element is not an array";
         return false;
     }
     if (json_array_size(config) == 0) {
         log_error() << "Root JSON array is empty";
         return false;
     }
     for(size_t i = 0; i < json_array_size(config); i++) {
         json_t *element = json_array_get(config, i);
         if (!json_is_object(element)) {
             log_error() << "json configuration is not an object";
             return false;
         }
         if (!readConfigElement(element)) {
             log_error() << "Could not read config element";
             return false;
         }
     }
     m_state = GatewayState::CONFIGURED;
     return true;
 }
bool softwarecontainer::Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
true upon successful application of configuration, false otherwise
Exceptions
GatewayError If called on an already activated gateway, or if the gateway has not been previously configured, or if there is not container instance set.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 58 of file gateway.cpp.
References softwarecontainer::Gateway::id().
Referenced by softwarecontainer::DBusGateway::activate().
{
     if (m_state == GatewayState::ACTIVATED) {
         log_error() << "Activate was called on a gateway which was already activated: " << id();
         throw GatewayError("Gateway already activated");
     }
     if (m_state != GatewayState::CONFIGURED) {
         log_error() << "Activate was called on a gateway which is not in configured state: " << id();
         throw GatewayError("Gateway is not configured");
     }
     if (!activateGateway()) {
         log_error() << "Couldn't activate gateway: " << id();
         return false;
     }
     m_state = GatewayState::ACTIVATED;
     return true;
 }
bool softwarecontainer::Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
true upon successful clean-up, false otherwise
Exceptions
GatewayError If called on a non activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 78 of file gateway.cpp.
References softwarecontainer::Gateway::id().
Referenced by softwarecontainer::DBusGateway::teardown().
{
     if (m_state != GatewayState::ACTIVATED) {
         log_error() << "Teardown called on non-activated gateway: " << id();
         throw GatewayError("Gateway not previosly activated");
     }
     if (!teardownGateway()) {
         log_error() << "Could not tear down gateway: " << id();
         return false;
     }
     // Return to a state of nothingness
     m_state = GatewayState::CREATED;
     return true;
 }
bool softwarecontainer::Gateway::isConfigured () virtual inherited
Is the gateway configured or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 100 of file gateway.cpp.
Referenced by softwarecontainer::DBusGateway::activate(), and softwarecontainer::DBusGateway::isConfigured().
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool softwarecontainer::Gateway::isActivated () virtual inherited
Is the gateway activated or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 105 of file gateway.cpp.
Referenced by softwarecontainer::DBusGateway::isActivated(), and softwarecontainer::DBusGateway::teardown().
 {
     return m_state >= GatewayState::ACTIVATED;
 }
std::shared_ptr< ContainerAbstractInterface > softwarecontainer::Gateway::getContainer () protected inherited
Get a handle to the associated container.
Exceptions
GatewayError If called before setContainer() has been called.
Definition at line 94 of file gateway.cpp.
Referenced by softwarecontainer::DeviceNodeGateway::activateGateway(), softwarecontainer::NetworkGateway::activateGateway(), and activateGateway().
 {
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
bool softwarecontainer::Gateway::setEnvironmentVariable (const std::string & variable, const std::string & value) protected inherited
Set an environment variable in the associated container.
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/dbus/dbusgatewayinstance.h
libsoftwarecontainer/src/gateway/dbus/dbusgatewayinstance.cpp