softwarecontainer: softwarecontainer::ServiceManifestFileLoader Class Reference
softwarecontainer::ServiceManifestFileLoader Class Reference
Public Member Functions
ServiceManifestFileLoader (const std::string &source)
virtual std::vector< json_t * > loadContent () override
Loads the json content from the Service Manifest(s)
Protected Attributes
std::vector< json_t * > m_content
const std::string m_source
Detailed Description
Definition at line 31 of file servicemanifestfileloader.h.
Member Function Documentation
std::vector< json_t * > softwarecontainer::ServiceManifestFileLoader::loadContent () override virtual
Loads the json content from the Service Manifest(s)
Returns
a vector of json_t representing the Service Manifest(s)
Exceptions
ServiceManifestPathError if the path to the file or dir is invalid
ServiceManifestParseError if parsing of one or more files is unsuccessful
Implements softwarecontainer::ServiceManifestLoader.
Definition at line 30 of file servicemanifestfileloader.cpp.
References softwarecontainer::isDirectory(), softwarecontainer::isDirectoryEmpty(), and softwarecontainer::isFile().
 {
     std::string errorMessage;
     if (m_source.empty()) {
         //File path is empty, this is ok
         log_debug() << "Path to service manifests is empty";
     } else if (m_source.compare("/") == 0) {
         errorMessage = "Searching for configuration files from root dir not allowed";
         log_error() << errorMessage;
         throw ServiceManifestPathError(errorMessage);
     } else if (isDirectory(m_source)) {
         log_debug() << "Path to service manifests is a directory";
         loadServiceManifestDir();
     } else if (isFile(m_source)) {
         log_debug() << "Path to service manifest is a file";
         if (isJsonFile(m_source)) {
             loadServiceManifestFile(m_source);
         } else {
             errorMessage = "Path to service manifest is not a json file";
             log_debug() << errorMessage;
             throw ServiceManifestPathError(errorMessage);
         }
     } else {
         errorMessage = "The path to the service manifest(s) is not a directory or file: \""
             + m_source + "\"";
         log_error() << errorMessage;
         throw ServiceManifestPathError(errorMessage);
     }
     return m_content;
 }
The documentation for this class was generated from the following files:
agent/src/capability/servicemanifestfileloader.h
agent/src/capability/servicemanifestfileloader.cpp