softwarecontainer: IPTableEntry Class Reference
IPTableEntry Class Reference
A rules entry for the treatment of packets.
#include <iptableentry.h>
Data Structures
struct portFilter
container for port filtering options.
struct Rule
Definition of a 'Rule' used to handle network traffic.
Public Types
enum Target { INVALID_TARGET, ACCEPT, DROP, REJECT }
Targets for Rules.
Public Member Functions
ReturnCode applyRules ()
Applies all rules to iptables.
std::string interpretRule (Rule rule)
Interprets a rule to iptables applicable string.
std::string interpretPolicy (void)
This function Interprets defaultTarget rule to iptables applicable policy string.
Data Fields
unsigned int m_priority
std::string m_type
std::vector< Rule > m_rules
Target m_defaultTarget
Detailed Description
A rules entry for the treatment of packets.
Definition at line 27 of file iptableentry.h.
Member Enumeration Documentation
enum IPTableEntry::Target
Targets for Rules.
Definition at line 49 of file iptableentry.h.
     {
         INVALID_TARGET,
         ACCEPT,
         DROP,
         REJECT
     };
Member Function Documentation
ReturnCode IPTableEntry::applyRules ()
Applies all rules to iptables.
Returns
true Upon success
false Upon failure
Definition at line 23 of file iptableentry.cpp.
References interpretPolicy(), and interpretRule().
 {
     for (auto rule : m_rules) {
         if (ReturnCode::FAILURE == insertCommand(interpretRule(rule))) {
             log_error() << "Couldn't apply the rule " << rule.target;
             return ReturnCode::FAILURE;
         }
     }
     if (ReturnCode::FAILURE == insertCommand(interpretPolicy())) {
         log_error() << "Unable to set policy " << convertTarget(m_defaultTarget) << " for " << m_type;
         return ReturnCode::FAILURE;
     }
     return ReturnCode::SUCCESS;
 }
std::string IPTableEntry::interpretRule (Rule rule)
Interprets a rule to iptables applicable string.
Returns
string indicating interpreted rule
Definition at line 56 of file iptableentry.cpp.
Referenced by applyRules().
 {
     std::string iptableCommand = "iptables -A " + m_type;
     log_debug() << "Add network rule : " <<  iptableCommand;
         if (!rule.host.empty()) {
             if ("INPUT" == m_type) {
                 iptableCommand = iptableCommand + " -s ";
             } else {
                 iptableCommand = iptableCommand + " -d ";
             }
             iptableCommand = iptableCommand + rule.host ;
         }
         if (rule.ports.any) {
             if (rule.ports.multiport) {
                 iptableCommand = iptableCommand + " -p tcp --match multiport ";
                 if ("INPUT" == m_type) {
                     iptableCommand = iptableCommand + "--sports " + rule.ports.ports;
                 } else {
                     iptableCommand = iptableCommand + "--dports " + rule.ports.ports;
                 }
             } else {
                 iptableCommand = iptableCommand + " -p tcp ";
                 if ("INPUT" == m_type) {
                     iptableCommand = iptableCommand + "--sport " + rule.ports.ports;
                 } else {
                     iptableCommand = iptableCommand + "--dport " + rule.ports.ports;
                 }
             }
         }
         iptableCommand = iptableCommand + " -j " + convertTarget(rule.target);
         log_debug() << "Add network rule : " <<  iptableCommand;
         return iptableCommand;
 }
std::string IPTableEntry::interpretPolicy (void)
This function Interprets defaultTarget rule to iptables applicable policy string.
defaultTarget indicates what happens to packets if they don't match to any rules. iptables apply this functionality with setting policy. The role of this function is converting defaultTarget configuration value to iptables policy
Returns
string indicating interpreted policy
empty string when interfered incompatible m_defaultTarget
Definition at line 95 of file iptableentry.cpp.
Referenced by applyRules().
 {
     if (m_defaultTarget != Target::ACCEPT && m_defaultTarget != Target::DROP) {
         log_error() << "Wrong default target : " << convertTarget(m_defaultTarget);
         return "";
     }
     std::string iptableCommand = "iptables -P " + m_type + " " + convertTarget(m_defaultTarget);
     return iptableCommand;
 }
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/iptableentry.h
libsoftwarecontainer/src/gateway/iptableentry.cpp