softwarecontainer: softwarecontainer::FileGateway Class Reference
softwarecontainer::FileGateway Class Reference
This gateway lets you map files (including socket files) or folders from the host into the container's filesystem.
#include <filegateway.h>
Public Types
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
Public Member Functions
FileGateway (std::shared_ptr< ContainerAbstractInterface > container)
bool readConfigElement (const json_t *element) override
Gateway specific parsing of config elements.
bool activateGateway () override
bool teardownGateway () override
virtual std::string id () const
Returns the ID of the gateway.
virtual bool setConfig (const json_t *config)
Configure this gateway according to the supplied JSON configuration string.
virtual bool activate ()
Applies any configuration set by setConfig()
virtual bool teardown ()
Restore system to the state prior to launching of gateway.
virtual bool isConfigured ()
Is the gateway configured or not?
virtual bool isActivated ()
Is the gateway activated or not?
Static Public Attributes
static constexpr const char * ID
Protected Member Functions
std::shared_ptr< ContainerAbstractInterface > getContainer ()
Get a handle to the associated container.
bool setEnvironmentVariable (const std::string &variable, const std::string &value)
Set an environment variable in the associated container.
Detailed Description
This gateway lets you map files (including socket files) or folders from the host into the container's filesystem.
Definition at line 35 of file filegateway.h.
Member Function Documentation
bool softwarecontainer::FileGateway::readConfigElement (const json_t * element) override virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
false if an error was encountered while parsing, true otherwise.
Implements softwarecontainer::Gateway.
Definition at line 30 of file filegateway.cpp.
 {
     FileGatewayParser parser;
     FileGatewayParser::FileSetting setting;
     if (!parser.parseConfigElement(element, setting)) {
         return false;
     }
     if (!m_store.addSetting(setting)) {
         return false;
     }
     return true;
 }
std::string softwarecontainer::Gateway::id () const virtual inherited
Returns the ID of the gateway.
Returns
Returns the ID of the gateway as a string
Definition at line 35 of file gateway.cpp.
Referenced by softwarecontainer::Gateway::activate(), softwarecontainer::DBusGatewayInstance::DBusGatewayInstance(), softwarecontainer::Gateway::setConfig(), and softwarecontainer::Gateway::teardown().
 {
     return m_id;
 }
bool softwarecontainer::Gateway::setConfig (const json_t * config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
true if config was successfully parsed, false otherwise
Exceptions
GatewayError If called on an already activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 40 of file gateway.cpp.
References softwarecontainer::Gateway::id(), and softwarecontainer::Gateway::readConfigElement().
 {
     if (GatewayState::ACTIVATED == m_state && !m_isDynamic) {
         std::string message = "Can not configure a gateway that is already activated "
                               "if the gateway does not support dynamic behavior. "
                               "Gateway ID: " + id();
         log_error() << message;
         throw GatewayError(message);
     }
     if (!json_is_array(config)) {
         log_error() << "Root JSON element is not an array";
         return false;
     }
     if (json_array_size(config) == 0) {
         log_error() << "Root JSON array is empty";
         return false;
     }
     for(size_t i = 0; i < json_array_size(config); i++) {
         json_t *element = json_array_get(config, i);
         if (!json_is_object(element)) {
             log_error() << "json configuration is not an object";
             return false;
         }
         if (!readConfigElement(element)) {
             log_error() << "Could not read config element";
             return false;
         }
     }
     m_state = GatewayState::CONFIGURED;
     return true;
 }
bool softwarecontainer::Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
true upon successful application of configuration, false otherwise
Exceptions
GatewayError If called on an already activated gateway, or if the gateway has not been previously configured, or if there is not container instance set.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 77 of file gateway.cpp.
References softwarecontainer::Gateway::id().
{
     if (GatewayState::ACTIVATED == m_state && !m_isDynamic) {
         std::string message =  "Can not activate a gateway that is already activated "
                                "if the gateway does not support dynamic behavior. "
                                "Gateway ID: " + id();
         log_error() << message;
         throw GatewayError(message);
     }
     if (GatewayState::CONFIGURED != m_state) {
         std::string message = "Activate was called on a gateway which is not in configured state. "
                               "Gateway ID: " + id();
         log_error() << message;
         throw GatewayError(message);
     }
     if (!activateGateway()) {
         log_error() << "Couldn't activate gateway: " << id();
         return false;
     }
     m_state = GatewayState::ACTIVATED;
     return true;
 }
bool softwarecontainer::Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
true upon successful clean-up, false otherwise
Exceptions
GatewayError If called on a non activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 102 of file gateway.cpp.
References softwarecontainer::Gateway::id().
Referenced by softwarecontainer::DBusGatewayInstance::DBusGatewayInstance().
{
     if (GatewayState::ACTIVATED != m_state) {
         std::string message = "Teardown called on non-activated gateway. Gateway ID:  " + id();
         log_error() << message;
         throw GatewayError(message);
     }
     if (!teardownGateway()) {
         log_error() << "Could not tear down gateway: " << id();
         return false;
     }
     // Return to a state of nothingness
     m_state = GatewayState::CREATED;
     return true;
 }
bool softwarecontainer::Gateway::isConfigured () virtual inherited
Is the gateway configured or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 125 of file gateway.cpp.
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool softwarecontainer::Gateway::isActivated () virtual inherited
Is the gateway activated or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 130 of file gateway.cpp.
Referenced by softwarecontainer::DBusGatewayInstance::DBusGatewayInstance().
 {
     return m_state >= GatewayState::ACTIVATED;
 }
std::shared_ptr< ContainerAbstractInterface > softwarecontainer::Gateway::getContainer () protected inherited
Get a handle to the associated container.
Exceptions
GatewayError If called before setContainer() has been called.
Definition at line 119 of file gateway.cpp.
Referenced by softwarecontainer::NetworkGateway::activateGateway(), softwarecontainer::DBusGatewayInstance::activateGateway(), softwarecontainer::WaylandGateway::readConfigElement(), and softwarecontainer::NetworkGateway::teardownGateway().
 {
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
bool softwarecontainer::Gateway::setEnvironmentVariable (const std::string & variable, const std::string & value) protected inherited
Set an environment variable in the associated container.
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/files/filegateway.h
libsoftwarecontainer/src/gateway/files/filegateway.cpp