softwarecontainer: Container Class Reference
Container Class Reference
The Container class is an abstraction of the specific containment technology used.
#include <container.h>
Public Types
typedef std::function< int()> ContainerFunction
Public Member Functions
Container (const std::string id, const std::string &configFile, const std::string &containerRoot, bool enableWriteBuffer=false, int shutdownTimeout=1)
Constructor.
ReturnCode create ()
create Creates a new lxc_container and creates it with all the initialization.
ReturnCode start (pid_t *pid)
Start the container.
ReturnCode attach (const std::string &commandLine, pid_t *pid, const EnvironmentVariables &variables, uid_t userID, const std::string &workingDirectory="/", int stdin=-1, int stdout=1, int stderr=2)
Start a process from the given command line, with an environment consisting of the variables previously set by the gateways, plus the ones passed as parameters here.
ReturnCode attach (const std::string &commandLine, pid_t *pid, uid_t userID=ROOT_UID)
Start a process with the environment variables which have previously been set by the gateways.
ReturnCode setCgroupItem (std::string subsys, std::string value)
ReturnCode setUser (uid_t userID)
ReturnCode executeInContainer (ContainerFunction function, pid_t *pid, const EnvironmentVariables &variables=EnvironmentVariables(), uid_t userID=ROOT_UID, int stdin=-1, int stdout=1, int stderr=2)
ReturnCode executeInContainer (const std::string &cmd)
ReturnCode bindMountFileInContainer (const std::string &pathOnHost, const std::string &pathInContainer, bool readonly=true)
Tries to bind mount a file in the container.
ReturnCode bindMountFolderInContainer (const std::string &pathOnHost, const std::string &pathInContainer, bool readonly=true)
Tries to bind mount a directory in the container.
ReturnCode mountDevice (const std::string &pathInHost)
ReturnCode createSymLink (const std::string &source, const std::string &destination)
ReturnCode destroy ()
Calls shutdown, and then destroys the container.
ReturnCode destroy (unsigned int timeout)
ReturnCode shutdown ()
Calls shutdown on the lxc container.
ReturnCode shutdown (unsigned int timeout)
ReturnCode suspend ()
ReturnCode resume ()
ReturnCode stop ()
Calls stop on the lxc container(force stop)
ReturnCode waitForState (LXCContainerState state, int timeout=20)
ReturnCode ensureContainerRunning ()
ReturnCode initialize ()
Setup the container for preloading.
std::string toString ()
const char * id () const
std::string gatewaysDirInContainer () const
std::string gatewaysDir () const
const std::string & rootFS () const
ReturnCode setEnvironmentVariable (const std::string &var, const std::string &val)
Private Member Functions
ReturnCode createParentDirectory (const std::string &path)
createParentDirectory Recursively tries to create the directory pointed to by path.
ReturnCode createDirectory (const std::string &path)
createDirectory Create a directory, and if successful append it to a list of dirs to be deleted in the dtor.
ReturnCode bindMount (const std::string &src, const std::string &dst, bool readOnly, bool enableWriteBuffer=false)
bindMount Bind mount a src directory to another position dst.
ReturnCode overlayMount (const std::string &lower, const std::string &upper, const std::string &work, const std::string &dst)
overlayMount Mount a directory with an overlay on top of it.
ReturnCode syncOverlayMount (const std::string &lower, const std::string &upper)
syncOverlayMount Copy the directory structure from upper layer to the lower layer
ReturnCode createSharedMountPoint (const std::string &path)
createSharedMountPoint Make the mount point shared, ie new mount points created in one bind mount will also be created in the other mount point.
ReturnCode writeToFile (const std::string &path, const std::string &content)
std::string tempDir (std::string templatePath)
tempDir Creates a temporary directory at templatePath.
Private Attributes
std::stack< CleanUpHandler * > m_cleanupHandlers
m_cleanupHandlers A stack of cleanupHandlers added during the lifetime of the FileToolKitWithUndo that will be run from the destructor.
Detailed Description
The Container class is an abstraction of the specific containment technology used.
The Container class is meant to be an abstraction of the containment technology, so that SoftwareContainer can view it as a generic concept that implements the specifics behind the conceptual phases of 'Pereload', 'Launch', and 'Shutdown'.
Definition at line 41 of file container.h.
Constructor & Destructor Documentation
Container::Container (const std::string id, const std::string & configFile, const std::string & containerRoot, bool enableWriteBuffer = false, int shutdownTimeout = 1)
Constructor.
Parameters
name Name of the container
configFile Path to the configuration file (including the file name)
containerRoot A path to the root of the container, i.e. the base path to e.g. the configurations and application root
enableWriteBuffer Enable RAM write buffers on top of rootfs
shutdownTimeout Timeout for shutdown of container.
Definition at line 66 of file container.cpp.
                                           :
     m_configFile(configFile),
     m_id(id),
     m_containerRoot(containerRoot),
     m_enableWriteBuffer(enableWriteBuffer),
     m_shutdownTimeout(shutdownTimeout)
 {
     init_lxc();
     log_debug() << "Container constructed with " << id;
 }
Member Function Documentation
ReturnCode Container::create () virtual
create Creates a new lxc_container and creates it with all the initialization.
Returns
ReturnCode::FAILURE on failed creation and ReturnCode::SUCCESS on a successful creation.
Implements ContainerAbstractInterface.
Definition at line 134 of file container.cpp.
References softwarecontainer::FileToolkitWithUndo::overlayMount().
 {
     if (m_state >= ContainerState::CREATED) {
         log_warning() << "Container already created";
         return ReturnCode::FAILURE;
     }
     log_debug() << "Creating container " << toString();
     const char *containerID = id();
     if (strlen(containerID) == 0) {
         log_error() << "ContainerID cannot be empty";
         return ReturnCode::FAILURE;
     }
     setenv("GATEWAY_DIR", gatewaysDir().c_str(), true);
     log_debug() << "GATEWAY_DIR : " << Glib::getenv("GATEWAY_DIR");
     auto configFile = m_configFile.c_str();
     log_debug() << "Config file : " << configFile;
     log_debug() << "Template : " << LXCTEMPLATE;
     log_debug() << "creating container with ID : " << containerID;
     // Creating a new LXC pointer
     // After this point all failures should do rollback
     m_container = lxc_container_new(containerID, nullptr);
     if (!m_container) {
         log_error() << "Error creating a new container";
         return rollbackCreate();
     }
     if (m_container->is_defined(m_container)) {
         log_error() << "ContainerID '" << containerID << "' is already in use.";
         return rollbackCreate();
     }
     log_debug() << "Successfully created container struct";
     if (!m_container->load_config(m_container, configFile)) {
         log_error() << "Error loading container config";
         return rollbackCreate();
     }
     log_debug() << "Successfully loaded container config";
     // File system stuff
     m_rootFSPath = logging::StringBuilder() << s_LXCRoot << "/" << containerID << "/rootfs";
     if (m_enableWriteBuffer) {
         const std::string rootFSPathLower = m_rootFSPath + "-lower";
         const std::string rootFSPathUpper = m_rootFSPath + "-upper";
         const std::string rootFSPathWork  = m_rootFSPath + "-work";
         overlayMount(rootFSPathLower, rootFSPathUpper, rootFSPathWork, m_rootFSPath);
         log_debug() << "Write buffer enabled, lower=" << rootFSPathLower
                     << ", upper=" << rootFSPathUpper
                     << ", work=" << rootFSPathWork
                     << ", dst=" << m_rootFSPath;
     } else {
         log_debug() << "WriteBuffer disabled, dst=" << m_rootFSPath;
     }
     // Set the LXC template
     int flags = 0;
     std::vector<char *> argv;
     if (!m_container->create(m_container, LXCTEMPLATE, nullptr, nullptr, flags, &argv[0])) {
         log_error() << "Error creating container";
         m_rootFSPath.assign("");
         return rollbackCreate();
     }
     // Everything went fine, set state and return successfully.
     m_state = ContainerState::CREATED;
     log_debug() << "Container created. RootFS: " << m_rootFSPath;
     return ReturnCode::SUCCESS;
 }
ReturnCode Container::start (pid_t * pid) virtual
Start the container.
Returns
The pid of the init process of the container
Implements ContainerAbstractInterface.
Definition at line 254 of file container.cpp.
 {
     if (m_state < ContainerState::CREATED) {
         log_warning() << "Trying to start container that isn't created. Please create the container first";
         return ReturnCode::FAILURE;
     }
     if (pid == nullptr) {
         log_error() << "Supplied pid argument is nullptr";
         return ReturnCode::FAILURE;
     }
     // For some reason the LXC start function does not work out
     log_debug() << "Starting container";
     char commandEnv[] = "env";
     char commandSleep[] = "/bin/sleep";
     char commandSleepTime[] = "100000000";
     char* const args[] = { commandEnv, commandSleep, commandSleepTime, nullptr};
     if (!m_container->start(m_container, false, args)) {
         log_error() << "Error starting container";
         return ReturnCode::FAILURE;
     }
     log_debug() << "Container started: " << toString();
     *pid = m_container->init_pid(m_container);
     m_state = ContainerState::STARTED;
     if (isError(ensureContainerRunning())) {
         log_error() << "Container started but is not running";
         return ReturnCode::FAILURE;
     }
     log_info() << "To connect to this container : lxc-attach -n " << id();
     return ReturnCode::SUCCESS;
 }
ReturnCode Container::attach (const std::string & commandLine, pid_t * pid, const EnvironmentVariables & variables, uid_t userID, const std::string & workingDirectory = "/", int stdin = -1, int stdout = 1, int stderr = 2) virtual
Start a process from the given command line, with an environment consisting of the variables previously set by the gateways, plus the ones passed as parameters here.
Implements ContainerAbstractInterface.
Definition at line 441 of file container.cpp.
Referenced by attach().
 {
     if (isError(ensureContainerRunning())) {
         log_error() << "Container is not running or in bad state, can't attach";
         return ReturnCode::FAILURE;
     }
     if (pid == nullptr) {
         log_error() << "Supplied pid argument is nullptr";
         return ReturnCode::FAILURE;
     }
     log_debug() << "Attach " << commandLine << " UserID:" << userID;
     std::vector<std::string> executeCommandVec = Glib::shell_parse_argv(commandLine);
     std::vector<char *> args;
     for (size_t i = 0; i < executeCommandVec.size(); i++) {
         executeCommandVec[i].c_str(); // ensure the string is null-terminated. not sure thas is required.
         auto s = &executeCommandVec[i][0];
         args.push_back(s);
     }
     // We need a null terminated array
     args.push_back(nullptr);
     // We execute the function as root but will switch to the real userID inside
     ReturnCode result = executeInContainer([&] () {
 //                log_debug() << "Starting command line in container : " << commandLine << " . Working directory : " << workingDirectory;
                 if (!isSuccess(setUser(userID))) {
                     return -1;
                 }
                 if (workingDirectory.length() != 0) {
                     auto ret = chdir(workingDirectory.c_str());
                     if (ret != 0) {
 //                        log_error() << "Error when changing current directory : " << strerror(errno);
                     }
                 }
                 execvp(args[0], args.data());
 //                log_error() << "Error when executing the command in container : " << strerror(errno);
                 return 1;
             }, pid, variables, ROOT_UID, stdin, stdout, stderr);
     if (isError(result)) {
         log_error() << "Could not execute in container";
         return ReturnCode::FAILURE;
     }
     return ReturnCode::SUCCESS;
 }
ReturnCode Container::attach (const std::string & commandLine, pid_t * pid, uid_t userID = ROOT_UID) virtual
Start a process with the environment variables which have previously been set by the gateways.
Implements ContainerAbstractInterface.
Definition at line 436 of file container.cpp.
References attach().
 {
     return attach(commandLine, pid, m_gatewayEnvironmentVariables, userID);
 }
ReturnCode Container::bindMountFileInContainer (const std::string & pathOnHost, const std::string & pathInContainer, bool readonly = true) virtual
Tries to bind mount a file in the container.
This will not create parent directories if they are not already present.
Parameters
pathOnHost The path to the file that shall be bind mounted on the host system.
pathInContainer Where to mount the file in the container.
readonly Sets if the mount should be read only or read write
Returns
SUCCESS if everything worked as expected, FAILURE otherwise.
Implements ContainerAbstractInterface.
Definition at line 581 of file container.cpp.
References softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers.
 {
     // Create a file to mount to in gateways
     std::string tempFile = gatewaysDir() + "/" + std::string(basename(pathInContainer.c_str()));
     if (isError(touch(tempFile))) {
         log_error() << "Could not create file " << tempFile;
         return ReturnCode::FAILURE;
     }
     m_cleanupHandlers.push(new FileCleanUpHandler(tempFile));
     return bindMountCore(pathOnHost, pathInContainer, tempFile, readonly);
 }
ReturnCode Container::bindMountFolderInContainer (const std::string & pathOnHost, const std::string & pathInContainer, bool readonly = true) virtual
Tries to bind mount a directory in the container.
Will create missing parent directories.
Parameters
pathOnHost The path to the directory that shall be bind mounted on the host system.
pathInContainer Where to mount the file in the container.
readonly Sets if the mount should be read only or read write
Returns
SUCCESS if everything worked as expected, FAILURE otherwise.
Implements ContainerAbstractInterface.
Definition at line 597 of file container.cpp.
References softwarecontainer::FileToolkitWithUndo::createDirectory(), and softwarecontainer::FileToolkitWithUndo::tempDir().
 {
     // Check that the target is not already mounted
     pid_t pid = INVALID_PID;
     ReturnCode checkIfAlreadyMountpoint = executeInContainer([pathInContainer] () {
         FILE *mountsfile = setmntent("/proc/mounts", "r");
         struct mntent *mounts;
         while ((mounts = getmntent(mountsfile)) != nullptr) {
             std::string mountDir(mounts->mnt_dir);
             if ((mountDir).compare(pathInContainer) == 0) {
                 return -1;
             }
         }
         return 0;
     }, &pid);
     if (isError(checkIfAlreadyMountpoint) || waitForProcessTermination(pid) != 0) {
         log_error() << pathInContainer << " is already mounted to.";
         return ReturnCode::FAILURE;
     }
     // Create a directory to mount to in gateways
     std::string tempDir = gatewaysDir() + "/" + std::string(basename(pathInContainer.c_str()));
     log_debug() << "Creating folder : " << tempDir;
     if (isError(createDirectory(tempDir))) {
         log_error() << "Could not create folder " << tempDir;
         return ReturnCode::FAILURE;
     }
     return bindMountCore(pathOnHost, pathInContainer, tempDir, readonly);
 }
ReturnCode Container::destroy () virtual
Calls shutdown, and then destroys the container.
Implements ContainerAbstractInterface.
Definition at line 550 of file container.cpp.
 {
     return destroy(m_shutdownTimeout);
 }
ReturnCode Container::shutdown () virtual
Calls shutdown on the lxc container.
Implements ContainerAbstractInterface.
Definition at line 518 of file container.cpp.
 {
     return shutdown(m_shutdownTimeout);
 }
ReturnCode Container::stop () virtual
Calls stop on the lxc container(force stop)
Implements ContainerAbstractInterface.
Definition at line 498 of file container.cpp.
 {
     ReturnCode ret = ReturnCode::SUCCESS;
     if (m_state >= ContainerState::STARTED) {
         log_debug() << "Stopping the container";
         if (m_container->stop(m_container)) {
             log_debug() << "Container stopped, waiting for stop state";
             waitForState(LXCContainerState::STOPPED);
         } else {
             log_error() << "Unable to stop container";
             ret = ReturnCode::FAILURE;
         }
     } else {
         log_error() << "Can't stop container that has not been started";
         ret = ReturnCode::FAILURE;
     }
     return ret;
 }
ReturnCode Container::initialize () virtual
Setup the container for preloading.
Setup the container so directories are available for later use when setApplication is called.
Returns
true or false
Implements ContainerAbstractInterface.
Definition at line 100 of file container.cpp.
References softwarecontainer::FileToolkitWithUndo::createDirectory(), and softwarecontainer::FileToolkitWithUndo::createSharedMountPoint().
 {
     if (m_state < ContainerState::PREPARED) {
         std::string gatewayDir = gatewaysDir();
         if (isError(createDirectory(gatewayDir))) {
             log_error() << "Could not create gateway directory " << gatewayDir << strerror(errno);
             return ReturnCode::FAILURE;
         }
         if (isError(createSharedMountPoint(gatewayDir))) {
             log_error() << "Could not create shared mount point for dir: " << gatewayDir;
             return ReturnCode::FAILURE;
         }
         m_state = ContainerState::PREPARED;
     }
     return ReturnCode::SUCCESS;
 }
The documentation for this class was generated from the following files:
libsoftwarecontainer/include/container.h
libsoftwarecontainer/src/container.cpp