softwarecontainer: NetworkGateway Class Reference
NetworkGateway Class Reference
Sets up and manages network access and routing to the container.
#include <networkgateway.h>
Public Types
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
Public Member Functions
ReturnCode readConfigElement (const json_t *element) override
Gateway specific parsing of config elements.
bool activateGateway () override
Implements Gateway::activateGateway.
bool teardownGateway () override
Implements Gateway::teardownGateway.
const std::string ip ()
Returns the IP of the container.
virtual const char * id ()
virtual bool setConfig (const std::string &config)
Configure this gateway according to the supplied JSON configuration string.
virtual bool activate ()
Applies any configuration set by setConfig()
virtual bool teardown ()
Restore system to the state prior to launching of gateway.
void setContainer (std::shared_ptr< ContainerAbstractInterface > container)
Set the associated container for this gateway.
bool isConfigured ()
Is the gateway configured or not?
bool isActivated ()
Is the gateway activated or not?
Static Public Attributes
static constexpr const char * ID
Protected Types
typedef std::function< int()> ContainerFunction
Execute a function in the container.
Protected Member Functions
bool hasContainer ()
Check if the gateway has an associated container.
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Get a handle to the associated container.
ReturnCode setEnvironmentVariable (const std::string &variable, const std::string &value)
Set an environment variable in the associated container.
ReturnCode executeInContainer (const std::string &cmd)
Execute the given command in the container.
ReturnCode executeInContainer (ContainerFunction func)
Protected Attributes
std::shared_ptr
< ContainerAbstractInterface > m_container
const char * m_id
GatewayState m_state
Static Protected Attributes
static constexpr const char * ENABLED_FIELD
static constexpr const char * XDG_RUNTIME_DIR_VARIABLE_NAME
Detailed Description
Sets up and manages network access and routing to the container.
The responsibility of NetworkGateway is to setup network connection as specified by given configuration. This configuration is described in detail in the user documentation, but a short summary of it is how to handle incoming and outgoing network packages using the three targets: ACCEPT, DROP and REJECT.
Definition at line 37 of file networkgateway.h.
Member Typedef Documentation
typedef std::function<int ()> Gateway::ContainerFunction protected inherited
Execute a function in the container.
Definition at line 151 of file gateway.h.
Member Function Documentation
ReturnCode NetworkGateway::readConfigElement (const json_t * element) override virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
ReturnCode FAILURE if an error was encountered while parsing, SUCCESS otherwise.
Implements Gateway.
Definition at line 39 of file networkgateway.cpp.
References NetworkGatewayParser::parseNetworkGatewayConfiguration().
 {
     IPTableEntry e;
     NetworkGatewayParser configParser;
     ReturnCode returnValue = configParser.parseNetworkGatewayConfiguration(element, e);
     if (isSuccess(returnValue)) {
         m_entries.push_back(e);
     }
     // --- TEMPORARY WORKAROUND ---
     // in the wait of activate() being rewritten
     if (IPTableEntry::Target::ACCEPT == e.m_defaultTarget) {
         m_internetAccess = true;
         m_gateway = "10.0.3.1";
     }
     // ----------------------------
     return returnValue;
 }
bool NetworkGateway::activateGateway () override virtual
Implements Gateway::activateGateway.
Implements Gateway.
Definition at line 62 of file networkgateway.cpp.
 {
     if (!hasContainer()) {
         log_error() << "activate was called on an EnvironmentGateway which has no associated container";
         return false;
     }
     if (m_gateway.size() != 0) {
         log_debug() << "Default gateway set to " << m_gateway;
     } else {
         m_internetAccess = false;
         log_debug() << "No gateway. Network access will be disabled";
     }
     if ( !isBridgeAvailable() ) {
         log_error() << "Bridge not available, expected gateway to be " << m_gateway;
         return false;
     }
     if (m_internetAccess) {
         generateIP();
         auto returnValue = up();
         for (auto entry : m_entries) {
             executeInContainer([&] () {
                 if (isSuccess(entry.applyRules())) {
                     return 0;
                 }  else {
                     return 1;
                 }
             });
         }
         return returnValue;
     } else {
         return down();
     }
 }
bool NetworkGateway::teardownGateway () override virtual
Implements Gateway::teardownGateway.
Implements Gateway.
Definition at line 101 of file networkgateway.cpp.
 {
     return true;
 }
const std::string NetworkGateway::ip ()
Returns the IP of the container.
Definition at line 106 of file networkgateway.cpp.
 {
     return m_ip;
 }
virtual const char* Gateway::id () inline virtual inherited
Returns
Returns the ID of the gateway
Definition at line 66 of file gateway.h.
Referenced by Gateway::activate(), softwarecontainer::SoftwareContainer::setGatewayConfigs(), and Gateway::teardown().
     {
         return m_id;
     }
bool Gateway::setConfig (const std::string & config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
true if config was successfully parsed false otherwise
Definition at line 25 of file gateway.cpp.
References Gateway::readConfigElement().
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
 {
     json_error_t error;
     json_t *root = json_loads(config.c_str(), 0, &error);
     if (!root) {
         log_error() << "Could not parse config: " << error.text;
         return false;
     }
     if (json_is_array(root)) {
         for(size_t i = 0; i < json_array_size(root); i++) {
             json_t *element = json_array_get(root, i);
             if (json_is_object(element)) {
                 if (isError(readConfigElement(element))) {
                     log_error() << "Could not read config element";
                     return false;
                 }
             } else {
                 log_error() << "json configuration is not an object";
                 return false;
             }
         }
     } else {
         log_error() << "Root JSON element is not an array";
         return false;
     }
     m_state = GatewayState::CONFIGURED;
     return true;
 }
bool Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
true upon successful application of configuration, false otherwise
Definition at line 56 of file gateway.cpp.
References Gateway::hasContainer(), and Gateway::id().
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
{
     if (m_state != GatewayState::CONFIGURED) {
         log_warning() << "Activate was called on a gateway which is not in configured state: " << id();
         return false;
     }
     if (!hasContainer()) {
         log_warning() << "Activate was called on a gateway which has no associated container: " << id();
         return false;
     }
     return activateGateway();
 }
bool Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
true upon successful clean-up, false otherwise
Definition at line 70 of file gateway.cpp.
References Gateway::id().
{
     if (m_state != GatewayState::ACTIVATED) {
         log_warning() << "Teardown called on non-activated gateway " << id();
     }
     return teardownGateway();
 }
void Gateway::setContainer (std::shared_ptr< ContainerAbstractInterface > container) inherited
Set the associated container for this gateway.
Definition at line 89 of file gateway.cpp.
 {
     m_container = container;
 }
bool Gateway::isConfigured () inherited
Is the gateway configured or not?
Definition at line 94 of file gateway.cpp.
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool Gateway::isActivated () inherited
Is the gateway activated or not?
Definition at line 99 of file gateway.cpp.
 {
     return m_state >= GatewayState::ACTIVATED;
 }
bool Gateway::hasContainer () protected inherited
Check if the gateway has an associated container.
Inheriting gateways calls this method to know if they are safe to assume they can access a ContainerAbstractInterface instance previously set by SoftwareContainer calling setContainer()
Returns
true if there is a ContainerAbstractInterface instance set, false if not.
Definition at line 78 of file gateway.cpp.
Referenced by Gateway::activate(), Gateway::executeInContainer(), and Gateway::setEnvironmentVariable().
 {
     return m_container != nullptr;
 }
std::shared_ptr< ContainerAbstractInterface > Gateway::getContainer () protected inherited
Get a handle to the associated container.
Definition at line 83 of file gateway.cpp.
Referenced by PulseGateway::activateGateway(), DeviceNodeGateway::activateGateway(), Gateway::executeInContainer(), and Gateway::setEnvironmentVariable().
 {
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
ReturnCode Gateway::setEnvironmentVariable (const std::string & variable, const std::string & value) protected inherited
Set an environment variable in the associated container.
Definition at line 104 of file gateway.cpp.
References Gateway::getContainer(), and Gateway::hasContainer().
Referenced by PulseGateway::activateGateway(), and DBusGateway::activateGateway().
 {
     if (hasContainer()) {
         return getContainer()->setEnvironmentVariable(variable, value);
     } else {
         log_error() << "Can't set environment variable on gateway without container";
         return ReturnCode::FAILURE;
     }
 }
ReturnCode Gateway::executeInContainer (const std::string & cmd) protected inherited
Execute the given command in the container.
Definition at line 117 of file gateway.cpp.
References Gateway::getContainer(), and Gateway::hasContainer().
 {
     if (hasContainer()) {
         return getContainer()->executeInContainer(cmd);
     } else {
         log_error() << "Can't execute in container from gateway without container";
         return ReturnCode::FAILURE;
     }
 }
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/networkgateway.h
libsoftwarecontainer/src/gateway/networkgateway.cpp