softwarecontainer: softwarecontainer::FileToolkitWithUndo Class Reference
softwarecontainer::FileToolkitWithUndo Class Reference
Public Member Functions
bool bindMount (const std::string &src, const std::string &dst, bool readOnly, bool enableWriteBuffer=false)
bindMount Bind mount a src directory to another position dst.
std::string tempDir (std::string templatePath)
tempDir Creates a temporary directory at templatePath.
Protected Member Functions
bool writeToFile (const std::string &path, const std::string &content)
void markFileForDeletion (const std::string &path)
bool overlayMount (const std::string &lower, const std::string &upper, const std::string &work, const std::string &dst)
overlayMount Mount a directory with an overlay on top of it.
bool syncOverlayMount (const std::string &lower, const std::string &upper)
syncOverlayMount Copy the directory structure from upper layer to the lower layer
bool createSharedMountPoint (const std::string &path)
createSharedMountPoint Make the mount point shared, ie new mount points created in one bind mount will also be created in the other mount point.
bool createDirectory (const std::string &path)
createDirectory Create a directory, and if successful append it to a list of dirs to be deleted in the dtor.
bool pathInList (const std::string path)
checks whether given path is already added to clean up handlers or not
Protected Attributes
std::vector< CleanUpHandler * > m_cleanupHandlers
m_cleanupHandlers A vector of cleanupHandlers added during the lifetime of the FileToolKitWithUndo that will be run from the destructor.
Detailed Description
Definition at line 27 of file filetoolkitwithundo.h.
Member Function Documentation
bool softwarecontainer::FileToolkitWithUndo::bindMount (const std::string & src, const std::string & dst, bool readOnly, bool enableWriteBuffer = false)
bindMount Bind mount a src directory to another position dst.
Parameters
src Path to mount from
dst Path to mount to
readOnly Make the bind mount destination read only
enableWriteBuffer Enable write buffers on the bind mount.
Returns
true on success, false on failure
Definition at line 109 of file filetoolkitwithundo.cpp.
References softwarecontainer::existsInFileSystem(), m_cleanupHandlers, and tempDir().
Referenced by softwarecontainer::Container::bindMountInContainer().
 {
     unsigned long flags =  0;
     std::string fstype;
     int mountRes;
     if (!existsInFileSystem(src)) {
         log_error() << src << " does not exist on the host, can not bindMount";
         return false;
     }
     if (!existsInFileSystem(dst)) {
         log_error() << dst << " does not exist on the host, can not bindMount";
         return false;
     }
     log_debug() << "Bind-mounting " << src << " in " << dst << ", flags: " << flags;
     if(enableWriteBuffer) {
         std::string upperDir = tempDir("/tmp/sc-bindmount-upper-XXXXXX");
         std::string workDir = tempDir("/tmp/sc-bindmount-work-XXXXXX");
         fstype.assign("overlay");
         std::ostringstream os;
         os << "lowerdir=" << src << ",upperdir=" << upperDir << ",workdir=" << workDir;
         log_debug() << "enableWriteBuffer, config: " << os.str();
         mountRes = mount("overlay", dst.c_str(), fstype.c_str(), flags, os.str().c_str());
         log_debug() << "mountRes: " << mountRes;
     } else {
         const void *data = nullptr;
         flags = MS_BIND;
         mountRes = mount(src.c_str(), dst.c_str(), fstype.c_str(), flags, data);
     }
     if (mountRes == 0) {
         log_verbose() << "Bind-mounted folder " << src << " in " << dst;
         m_cleanupHandlers.push_back(new MountCleanUpHandler(dst));
     } else {
         log_error() << "Could not mount into container: src=" << src
                     << " , dst=" << dst << " err=" << strerror(errno);
         return false;
     }
     if (readOnly && !enableWriteBuffer) {
         const void *data = nullptr;
         flags = MS_REMOUNT | MS_RDONLY | MS_BIND;
         log_debug() << "Re-mounting read-only" << src << " in "
                     << dst << ", flags: " << flags;
         mountRes = mount(src.c_str(), dst.c_str(), fstype.c_str(), flags, data);
         if (mountRes != 0) {
             // Failure
             log_error() << "Could not re-mount " << src << " , read-only on "
                         << dst << " err=" << strerror(errno);
             return false;
         }
     }
     return true;
 }
std::string softwarecontainer::FileToolkitWithUndo::tempDir (std::string templatePath)
tempDir Creates a temporary directory at templatePath.
Warning
The temporary path will be destroyed when the instance of FileToolkitWithUndo is destroyed.
Parameters
templ a template Path used to create the path of the temporary directory, including XXXXXX which will be replaced with a unique ID for the temporary directory
Returns
A string path pointing to the newly creted temporary directory.
Definition at line 93 of file filetoolkitwithundo.cpp.
References m_cleanupHandlers, and pathInList().
Referenced by bindMount().
 {
     char *dir = const_cast<char*>(templ.c_str());
     dir = mkdtemp(dir);
     if (dir == nullptr) {
         log_warning() << "Failed to create buffered Directory: " << strerror(errno);
         return nullptr;
     }
     if (!pathInList(templ)) {
         m_cleanupHandlers.push_back(new DirectoryCleanUpHandler(templ));
     }
     return std::string(dir);
 }
bool softwarecontainer::FileToolkitWithUndo::overlayMount (const std::string & lower, const std::string & upper, const std::string & work, const std::string & dst) protected
overlayMount Mount a directory with an overlay on top of it.
An overlay protects the lower filesystem from writes by writing to the upper file system through the work directory.
Parameters
lower The lower file system, this will be read only.
upper The upper file system, this can be a tmpfs/ramfs of some kind. This is where final writes wind up
work This is a work directory, preferably a tmpfs/ramfs of some kind. This is where writes wind up temporarily.
dst Where the overlay filesystem will be mounted.
Returns
true on success, false on failure
Definition at line 175 of file filetoolkitwithundo.cpp.
References createDirectory(), m_cleanupHandlers, and pathInList().
Referenced by softwarecontainer::Container::create().
 {
     std::string fstype = "overlay";
     unsigned long flags = 0;
     if (!createDirectory(lower)
         || !createDirectory(upper)
         || !createDirectory(work)
         || !createDirectory(dst))
     {
         log_error() << "Failed to create lower/upper/work directory for overlayMount. lowerdir=" <<
                        lower << ", upperdir=" << upper << ", workdir=" << work;
         return false;
     }
     std::string mountoptions = logging::StringBuilder() << "lowerdir=" << lower
                                                         << ",upperdir=" << upper
                                                         << ",workdir=" << work;
     int mountRes = mount("overlay", dst.c_str(), fstype.c_str(), flags, mountoptions.c_str());
     if (mountRes == 0) {
         log_verbose() << "overlayMounted folder " << lower << " in " << dst;
         m_cleanupHandlers.push_back(new MountCleanUpHandler(dst));
         if (!pathInList(upper)) {
             m_cleanupHandlers.push_back(new DirectoryCleanUpHandler(upper));
         }
         m_cleanupHandlers.push_back(new OverlaySyncCleanupHandler(upper, lower));
         if (!pathInList(work)) {
             m_cleanupHandlers.push_back(new DirectoryCleanUpHandler(work));
         }
     } else {
         log_error() << "Could not mount into container: upper=" << upper
                     << ",lower=" << lower
                     << ",work=" << work
                     << " at dst=" << dst << " err=" << strerror(errno);
         return false;
     }
     return true;
 }
bool softwarecontainer::FileToolkitWithUndo::syncOverlayMount (const std::string & lower, const std::string & upper) protected
syncOverlayMount Copy the directory structure from upper layer to the lower layer
Parameters
lower The lower layer used in an overlay file system.
upper The upper layer in an overlay file system.
Returns
true on success, false on failure
Definition at line 220 of file filetoolkitwithundo.cpp.
References softwarecontainer::RecursiveCopy::copy(), and softwarecontainer::RecursiveCopy::getInstance().
 {
     return RecursiveCopy::getInstance().copy(upper, lower);
 }
bool softwarecontainer::FileToolkitWithUndo::createSharedMountPoint (const std::string & path) protected
createSharedMountPoint Make the mount point shared, ie new mount points created in one bind mount will also be created in the other mount point.
Parameters
path The mount path to make shared.
Returns
true on success, false on failure
Definition at line 226 of file filetoolkitwithundo.cpp.
References m_cleanupHandlers.
Referenced by softwarecontainer::Container::initialize().
 {
     auto mountRes = mount(path.c_str(), path.c_str(), "", MS_BIND, nullptr);
     if (mountRes != 0) {
         log_error() << "Could not bind mount " << path << " to itself";
         return false;
     }
     mountRes = mount(path.c_str(), path.c_str(), "", MS_UNBINDABLE, nullptr);
     if (mountRes != 0) {
         log_error() << "Could not make " << path << " unbindable";
         return false;
     }
     mountRes = mount(path.c_str(), path.c_str(), "", MS_SHARED, nullptr);
     if (mountRes != 0) {
         log_error() << "Could not make " << path << " shared";
         return false;
     }
     m_cleanupHandlers.push_back(new MountCleanUpHandler(path));
     log_debug() << "Created shared mount point at " << path;
     return true;
 }
bool softwarecontainer::FileToolkitWithUndo::createDirectory (const std::string & path) protected
createDirectory Create a directory, and if successful append it to a list of dirs to be deleted in the dtor.
Since nestled dirs will need to be deleted in reverse order to creation insert to the beginning of the list.
Parameters
path Path of directory to be created
Returns
true on success, false on failure
Definition at line 68 of file filetoolkitwithundo.cpp.
References softwarecontainer::isDirectory(), m_cleanupHandlers, and pathInList().
Referenced by softwarecontainer::Container::bindMountInContainer(), softwarecontainer::Container::initialize(), overlayMount(), and softwarecontainer::SoftwareContainer::previouslyConfigured().
 {
     log_debug() << "createDirectory(" << path << ") called";
     if (isDirectory(path)) {
         return true;
     }
     if(!createParentDirectory(path)) {
         log_error() << "Couldn't create parent directory for " << path;
         return false;
     }
     if (mkdir(path.c_str(), S_IRWXU | S_IRWXG | S_IRWXO) == -1) {
         log_error() << "Could not create directory " << path << ": " << strerror(errno);
         return false;
     }
     if (!pathInList(path)) {
         m_cleanupHandlers.push_back(new DirectoryCleanUpHandler(path));
     }
     log_debug() << "Created directory " << path;
     return true;
 }
bool softwarecontainer::FileToolkitWithUndo::pathInList (const std::string path) protected
checks whether given path is already added to clean up handlers or not
This function will be called only before adding new CleanUpHandler for FileCleanUpHandler and DirectoryCleanUpHandler. The reason behind this, only indicated CleanUpHandlers are related with file/directory removal operations.
Parameters
a string path name to check
Returns
true if the path is already exist, false otherwise
Definition at line 252 of file filetoolkitwithundo.cpp.
References m_cleanupHandlers.
Referenced by softwarecontainer::Container::bindMountInContainer(), createDirectory(), overlayMount(), and tempDir().
 {
     for (auto element : m_cleanupHandlers) {
         if (element->queryName() == path) {
             return true;
         }
     }
     return false;
 }
Field Documentation
std::vector<CleanUpHandler *> softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers protected
m_cleanupHandlers A vector of cleanupHandlers added during the lifetime of the FileToolKitWithUndo that will be run from the destructor.
Definition at line 130 of file filetoolkitwithundo.h.
Referenced by bindMount(), softwarecontainer::Container::bindMountInContainer(), createDirectory(), createSharedMountPoint(), overlayMount(), pathInList(), and tempDir().
The documentation for this class was generated from the following files:
common/filetoolkitwithundo.h
common/filetoolkitwithundo.cpp