softwarecontainer: softwarecontainer::SoftwareContainerAgent Class Reference
softwarecontainer::SoftwareContainerAgent Class Reference
A wrapper class.
#include <softwarecontaineragent.h>
Public Member Functions
SoftwareContainerAgent (Glib::RefPtr< Glib::MainContext > mainLoopContext, int preloadCount, bool shutdownContainers, int shutdownTimeout, const std::string &configPath)
bool deleteContainer (ContainerID containerID)
delete container by ID
bool checkContainer (ContainerID containerID, SoftwareContainer *&container)
Check whether the given container is valid and return a reference to the actual container.
ReturnCode readConfigElement (const json_t *element)
Tries to read a config in json format for a container.
bool parseConfig (const std::string &config)
Parse config needed for starting up the container in a correct manner.
ContainerID createContainer (const std::string &config)
Create a new container.
bool writeToStdIn (pid_t pid, const std::vector< uint8_t > &bytes)
writes to stdin of a process inside a container
pid_t launchCommand (ContainerID containerID, uid_t userID, const std::string &cmdLine, const std::string &workingDirectory, const std::string &outputFile, const EnvironmentVariables &env, std::function< void(pid_t, int)> listener)
Launch the given command in a the given container.
bool setContainerName (ContainerID containerID, const std::string &name)
sets the container name
bool shutdownContainer (ContainerID containerID)
shuts down a container
bool shutdownContainer (ContainerID containerID, unsigned int timeout)
shuts down a container with a custom timeout
bool suspendContainer (ContainerID containerID)
suspends execution of a container
bool resumeContainer (ContainerID containerID)
resumes execution of a container
std::string bindMountFolderInContainer (const ContainerID containerID, const std::string &pathInHost, const std::string &subPathInContainer, bool readOnly)
Bind mount a folder into the container.
bool setGatewayConfigs (const ContainerID &containerID, const std::map< std::string, std::string > &configs)
Set gateway configurations for the container.
bool setCapabilities (const ContainerID &containerID, const std::vector< std::string > &capabilities)
Set capabilities for the container.
std::shared_ptr< Workspace > getWorkspace ()
get a pointer to the workspace used TODO: This is only used for testing
Static Protected Member Functions
static bool read (const json_t *element, const char *key, std::string &result)
Reads a string from a JSON Object.
static bool read (const json_t *element, const char *key, bool &result)
Reads a boolean from a JSON Object.
static bool read (const json_t *element, const char *key, int &result)
Reads an integer from a JSON Object.
Detailed Description
A wrapper class.
Definition at line 60 of file softwarecontaineragent.h.
Member Function Documentation
bool SoftwareContainerAgent::deleteContainer (ContainerID containerID)
delete container by ID
Definition at line 84 of file softwarecontaineragent.cpp.
Referenced by shutdownContainer().
 {
     if (!isIdValid(containerID)) {
         log_error() << "Invalid container ID " << containerID;
         return false;
     }
     m_containers.erase(containerID);
     m_containerIdPool.push_back(containerID);
     return true;
 }
bool SoftwareContainerAgent::checkContainer (ContainerID containerID, SoftwareContainer *& container)
Check whether the given container is valid and return a reference to the actual container.
Parameters
containerID the ID for the container
container a pointer to a container object (out parameter)
Definition at line 96 of file softwarecontaineragent.cpp.
Referenced by bindMountFolderInContainer(), launchCommand(), resumeContainer(), setContainerName(), shutdownContainer(), and suspendContainer().
 {
     if (!isIdValid(containerID)) {
         log_error() << "Invalid container ID " << containerID;
         return false;
     }
     container = m_containers[containerID].get();
     return true;
 }
ReturnCode SoftwareContainerAgent::readConfigElement (const json_t * element)
Tries to read a config in json format for a container.
One can pass options to the agent when creating containers, options that are not gateway specific. These options will be read by this function
Parameters
element a config snippet in json format
Returns
ReturnCode::SUCCESS
Definition at line 107 of file softwarecontaineragent.cpp.
References softwarecontainer::JSONParser::read().
Referenced by parseConfig().
 {
     bool wo = false;
     if(!read(element, "enableWriteBuffer", wo)) {
         log_debug() << "enableWriteBuffer not found";
     }
     m_softwarecontainerWorkspace->m_enableWriteBuffer = wo;
     return ReturnCode::SUCCESS;
 }
bool SoftwareContainerAgent::parseConfig (const std::string & config)
Parse config needed for starting up the container in a correct manner.
This reads a config string into json format, makes sure it is formatted correctly, and then calls readConfigElement for its elements.
Parameters
config a configuration string
Definition at line 118 of file softwarecontaineragent.cpp.
References readConfigElement().
Referenced by createContainer().
 {
     if (config.size() == 0) {
         log_warning() << "No configuration interpreted";
         return false;
     }
     json_error_t error;
     json_t *root = json_loads(config.c_str(), 0, &error);
     if (!root) {
         log_error() << "Could not parse config: " << error.text;
         log_error() << config;
         return false;
     }
     if (!json_is_array(root)) {
         log_error() << "Root JSON element is not an array";
         return false;
     }
     size_t index;
     json_t *element;
     json_array_foreach(root, index, element) {
         if (!json_is_object(element)) {
             log_error() << "json configuration is not an object";
             return false;
         }
         if (isError(readConfigElement(element))) {
             log_error() << "Could not read config element";
             return false;
         }
     }
     return true;
 }
ContainerID SoftwareContainerAgent::createContainer (const std::string & config)
Create a new container.
Parameters
config container-wide configuration string
Returns
If the container is successfully created a positive ContainerID representing the newly created container will be returned. Otherwise, -1 will be returned.
Definition at line 175 of file softwarecontaineragent.cpp.
References parseConfig().
 {
     profilepoint("createContainerStart");
     profilefunction("createContainerFunction");
     if (!parseConfig(config)) {
         log_error() << "The provided config could not be successfully parsed";
         return -1;
     }
     std::pair<ContainerID, SoftwareContainerPtr> pair = std::move(getContainerPair());
     pair.second->setMainLoopContext(m_mainLoopContext);
     if (isError(pair.second->init())) {
         log_error() << "Could not init the container";
         return -1;
     }
     // TODO: Would be nice if this could be done async.
     if (!triggerPreload()) {
         log_warning() << "Failed to preload new container";
     }
     m_containers.insert(std::move(pair));
     // Return the ContainerID for the container
     return pair.first;
 }
bool SoftwareContainerAgent::writeToStdIn (pid_t pid, const std::vector< uint8_t > & bytes)
writes to stdin of a process inside a container
Parameters
pid the pid of the process (must be created through launchCommand)
bytes the bytes to write to stdin
Definition at line 232 of file softwarecontaineragent.cpp.
 {
     CommandJob *job = nullptr;
     if (!checkJob(pid, job)) {
         log_error() << "Unknown pid " << pid;
         return false;
     }
     log_debug() << "writing bytes to process with PID:" << job->pid() << " : " << bytes;
     write(job->stdin(), bytes.data(), bytes.size());
     return true;
 }
pid_t SoftwareContainerAgent::launchCommand (ContainerID containerID, uid_t userID, const std::string & cmdLine, const std::string & workingDirectory, const std::string & outputFile, const EnvironmentVariables & env, std::function< void(pid_t, int)> listener)
Launch the given command in a the given container.
Parameters
containerID the id for the container
userID the userID to use when running the command inside the container
cmdLine the command to run
workingDirectory the working directory to use when running
outputFile where to log any output
env any environment variables to pass to the command
listener a function that runs when the process exits
Definition at line 245 of file softwarecontaineragent.cpp.
References checkContainer().
 {
     profilefunction("launchCommandFunction");
     SoftwareContainer *container = nullptr;
     if (!checkContainer(containerID, container)) {
         log_error() << "Invalid container ID " << containerID;
         return INVALID_PID;
     }
     // Set up a CommandJob for this run in the container
     auto job = new CommandJob(*container, cmdLine);
     // Capturing this leaves an open pipe for every container, even
     // after it has terminated.
     // job->captureStdin();
     job->setOutputFile(outputFile);
     job->setUserID(userID);
     job->setEnvironmentVariables(env);
     job->setWorkingDirectory(workingDirectory);
     // Start it
     if (isError(job->start())) {
         log_error() << "Could not start job";
         return INVALID_PID;
     }
     // If things went well, do what we need when it exits
     addProcessListener(m_connections, job->pid(), [listener](pid_t pid, int exitCode) {
         listener(pid, exitCode);
     }, m_mainLoopContext);
     // Save the job
     m_jobs.push_back(job);
     profilepoint("launchCommandEnd");
     return job->pid();
 }
bool SoftwareContainerAgent::setContainerName (ContainerID containerID, const std::string & name)
sets the container name
Parameters
containerID the id for the container
name the name to set
Definition at line 289 of file softwarecontaineragent.cpp.
References checkContainer().
 {
     SoftwareContainer *container = nullptr;
     if (!checkContainer(containerID, container)) {
         log_error() << "Invalid container ID " << containerID;
         return false;
     }
     container->setContainerName(name);
     return true;
 }
bool SoftwareContainerAgent::shutdownContainer (ContainerID containerID)
shuts down a container
Parameters
containerID the container to shut down
Definition at line 301 of file softwarecontaineragent.cpp.
 {
     return shutdownContainer(containerID, m_softwarecontainerWorkspace->m_containerShutdownTimeout);
 }
bool SoftwareContainerAgent::shutdownContainer (ContainerID containerID, unsigned int timeout)
shuts down a container with a custom timeout
Parameters
containerID the container to shut down
timeout timeout in seconds to wait before forcing
Definition at line 306 of file softwarecontaineragent.cpp.
References checkContainer(), deleteContainer(), and softwarecontainer::SoftwareContainer::shutdown().
 {
     profilefunction("shutdownContainerFunction");
     if (!m_shutdownContainers) {
         log_info() << "Not shutting down containers, so not shutting down " << containerID;
         return false;
     }
     SoftwareContainer *container = nullptr;
     if (!checkContainer(containerID, container)) {
         log_error() << "Invalid container ID " << containerID;
         return false;
     }
     if (isError(container->shutdown(timeout))) {
         log_error() << "Could not shut down the container";
         return false;
     }
     if (!deleteContainer(containerID)) {
         log_error() << "Could not delete the container";
         return false;
     }
     return true;
 }
bool SoftwareContainerAgent::suspendContainer (ContainerID containerID)
suspends execution of a container
Parameters
containerID the container to suspend
Definition at line 333 of file softwarecontaineragent.cpp.
References checkContainer().
 {
     SoftwareContainer *container = nullptr;
     if (!checkContainer(containerID, container)) {
         log_error() << "Can't suspend container " << containerID;
         return false;
     }
     return isSuccess(container->suspend());
 }
bool SoftwareContainerAgent::resumeContainer (ContainerID containerID)
resumes execution of a container
Parameters
containerID the container to resume
Definition at line 344 of file softwarecontaineragent.cpp.
References checkContainer().
 {
     SoftwareContainer *container = nullptr;
     if (!checkContainer(containerID, container)) {
         log_error() << "Can't resume container " << containerID;
         return false;
     }
     return isSuccess(container->resume());
 }
std::string SoftwareContainerAgent::bindMountFolderInContainer (const ContainerID containerID, const std::string & pathInHost, const std::string & subPathInContainer, bool readOnly)
Bind mount a folder into the container.
Parameters
containerID the container to bind into
pathInHost path to the folder in the host system
subPathInContainer path (relative to a fixed start point) to use in the container
readOnly whether or not to mount read-only
Returns
the full path of the mounted folder in the container
Definition at line 355 of file softwarecontaineragent.cpp.
References checkContainer().
 {
     profilefunction("bindMountFolderInContainerFunction");
     SoftwareContainer *container = nullptr;
     if (!checkContainer(containerID, container)) {
         log_error() << "Invalid container ID " << containerID;
         return "";
     }
     std::string path;
     ReturnCode result = container->getContainer()->bindMountFolderInContainer(pathInHost, subPathInContainer, path, readOnly);
     if (isError(result)) {
         log_error() << "Unable to bind mount folder " << pathInHost << " to " << subPathInContainer;
         return "";
     }
     return path;
 }
bool SoftwareContainerAgent::setGatewayConfigs (const ContainerID & containerID, const std::map< std::string, std::string > & configs)
Set gateway configurations for the container.
Parameters
containerID the container to use
configs a mapping from gateway-ids to configuration strings to send to the container
Returns
true on success, false otherwise
Definition at line 377 of file softwarecontaineragent.cpp.
 {
     profilefunction("setGatewayConfigs");
     GatewayConfiguration parsedConfigs;
     for (auto const &it : configs) {
         json_error_t error;
         std::string gwID = it.first;
         std::string configStr = it.second;
         json_t *jConfigs = json_loads(configStr.c_str(), 0, &error);
         if (!jConfigs) {
             log_error() << "Could not parse config while setting gateway config: " << error.text;
             log_error() << configs;
             return false;
         }
         parsedConfigs[gwID] = jConfigs;
     }
     return updateGatewayConfigs(containerID, parsedConfigs);
 }
bool SoftwareContainerAgent::setCapabilities (const ContainerID & containerID, const std::vector< std::string > & capabilities)
Set capabilities for the container.
Capabilities are a mapping from a string to a set of gateway configurations. Capabilities are translated into gateway configurations and then sent the same way as with setGatewayConfigs
Parameters
containerID the container to use
capabilities the capabilities
Returns
true on success, false otherwise
Definition at line 414 of file softwarecontaineragent.cpp.
References softwarecontainer::ConfigStore::getGatewayConfigs().
 {
     for (std::string capId : capabilities) {
         GatewayConfiguration newConfigs = m_configStore.getGatewayConfigs(capId);
         if (!updateGatewayConfigs(containerID, newConfigs)) {
             log_error() << "Could noteset gateway configuration for capability"
                         << std::to_string(containerID) << " does not exist";
             return false;
         }
     }
     return true;
 }
std::shared_ptr< Workspace > SoftwareContainerAgent::getWorkspace ()
get a pointer to the workspace used TODO: This is only used for testing
Returns
a shared pointer to the current workspace
Definition at line 431 of file softwarecontaineragent.cpp.
 {
     return m_softwarecontainerWorkspace;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, std::string & result) static inherited
Reads a string from a JSON Object.
Tries to read a string value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the string could not be read, either due to the given object does not contain the given key or the given key did not hold a string, false will be returned and the result reference will not be changed.
Returns
True: If the string was successfully read.
False: If the string could not be read.
Definition at line 24 of file jsonparser.cpp.
Referenced by NetworkGatewayParser::parseNetworkGatewayConfiguration(), EnvironmentGateway::readConfigElement(), WaylandGateway::readConfigElement(), CgroupsGateway::readConfigElement(), FileGateway::readConfigElement(), PulseGateway::readConfigElement(), DeviceNodeGateway::readConfigElement(), and readConfigElement().
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_error() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_string(value)) {
         log_error() << "json element is not a string";
         return false;
     }
     result = json_string_value(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, bool & result) static inherited
Reads a boolean from a JSON Object.
Tries to read a boolean value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the boolean could not be read, either due to the given object does not contain the given key or the given key did not hold a boolean value, false will be returned and the result reference will not be changed.
Returns
True: If the boolean was successfully read.
False: If the boolean could not be read.
Definition at line 41 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_error() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_boolean(value)) {
         log_error() << "json element is not a boolean";
         return false;
     }
     result = json_is_true(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, int & result) static inherited
Reads an integer from a JSON Object.
Tries to read an integer value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the integer could not be read, either due to the given object does not contain the given key or the given key did not hold an integer value, false will be returned and the result reference will not be changed.
Returns
True: If the integer was successfully read.
False: If the integer could not be read.
Definition at line 58 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         log_error() << "Could not fetch \"" << key << "\" from json element";
         return false;
     }
     if (!json_is_integer(value)) {
         log_error() << "json element is not an integer";
         return false;
     }
     result = json_integer_value(value);
     return true;
 }
The documentation for this class was generated from the following files:
agent/src/softwarecontaineragent.h
agent/src/softwarecontaineragent.cpp