softwarecontainer: FileGateway Class Reference
FileGateway Class Reference
This gateway lets you map files (including socket files) or folders from the host into the container's filesystem.
#include <filegateway.h>
Public Types
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
Public Member Functions
ReturnCode readConfigElement (const json_t *element) override
Gateway specific parsing of config elements.
bool activateGateway () override
bool teardownGateway () override
virtual const char * id ()
virtual bool setConfig (const std::string &config)
Configure this gateway according to the supplied JSON configuration string.
virtual bool activate ()
Applies any configuration set by setConfig()
virtual bool teardown ()
Restore system to the state prior to launching of gateway.
void setContainer (std::shared_ptr< ContainerAbstractInterface > container)
Set the associated container for this gateway.
bool isConfigured ()
Is the gateway configured or not?
bool isActivated ()
Is the gateway activated or not?
Static Public Attributes
static constexpr const char * ID
Protected Types
typedef std::function< int()> ContainerFunction
Execute a function in the container.
Protected Member Functions
virtual bool hasContainer ()
Check if the gateway has an associated container.
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Get a handle to the associated container.
ReturnCode setEnvironmentVariable (const std::string &variable, const std::string &value)
Set an environment variable in the associated container.
ReturnCode executeInContainer (const std::string &cmd)
Execute the given command in the container.
ReturnCode executeInContainer (ContainerFunction func)
Detailed Description
This gateway lets you map files (including socket files) or folders from the host into the container's filesystem.
Definition at line 34 of file filegateway.h.
Member Typedef Documentation
typedef std::function<int ()> Gateway::ContainerFunction protected inherited
Execute a function in the container.
Definition at line 151 of file gateway.h.
Member Function Documentation
ReturnCode FileGateway::readConfigElement (const json_t * element) override virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
ReturnCode FAILURE if an error was encountered while parsing, SUCCESS otherwise.
Implements Gateway.
Definition at line 30 of file filegateway.cpp.
 {
     FileGatewayParser parser;
     FileGatewayParser::FileSetting setting;
     if (isError(parser.parseFileGatewayConfigElement(element, setting))) {
         return ReturnCode::FAILURE;
     }
     m_settings.push_back(setting);
     return ReturnCode::SUCCESS;
 }
virtual const char* Gateway::id () inline virtual inherited
Returns
Returns the ID of the gateway
Definition at line 66 of file gateway.h.
Referenced by Gateway::activate(), Gateway::setConfig(), softwarecontainer::SoftwareContainer::setGatewayConfigs(), and Gateway::teardown().
     {
         return m_id;
     }
bool Gateway::setConfig (const std::string & config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
true if config was successfully parsed false otherwise
Definition at line 23 of file gateway.cpp.
References Gateway::id(), and Gateway::readConfigElement().
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
 {
     if (m_state == GatewayState::ACTIVATED) {
         log_error() << "Can't configure a gateway that is already activated: " << id();
     }
     json_error_t error;
     json_t *root = json_loads(config.c_str(), 0, &error);
     if (!root) {
         log_error() << "Could not parse config: " << error.text;
         return false;
     }
     if (!json_is_array(root)) {
         log_error() << "Root JSON element is not an array";
         return false;
     }
     if (json_array_size(root) == 0) {
         log_error() << "Root JSON array is empty";
         return false;
     }
     for(size_t i = 0; i < json_array_size(root); i++) {
         json_t *element = json_array_get(root, i);
         if (!json_is_object(element)) {
             log_error() << "json configuration is not an object";
             return false;
         }
         if (isError(readConfigElement(element))) {
             log_error() << "Could not read config element";
             return false;
         }
     }
     m_state = GatewayState::CONFIGURED;
     return true;
 }
bool Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
true upon successful application of configuration, false otherwise
Definition at line 63 of file gateway.cpp.
References Gateway::hasContainer(), and Gateway::id().
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
{
     if (m_state == GatewayState::ACTIVATED) {
         log_warning() << "Activate was called on a gateway which was already activated: " << id();
         return false;
     }
     if (m_state != GatewayState::CONFIGURED) {
         log_warning() << "Activate was called on a gateway which is not in configured state: " << id();
         return false;
     }
     if (!hasContainer()) {
         log_warning() << "Activate was called on a gateway which has no associated container: " << id();
         return false;
     }
     if (!activateGateway()) {
         log_error() << "Couldn't activate gateway: " << id();
         return false;
     }
     m_state = GatewayState::ACTIVATED;
     return true;
 }
bool Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
true upon successful clean-up, false otherwise
Definition at line 88 of file gateway.cpp.
References Gateway::id().
{
     if (m_state != GatewayState::ACTIVATED) {
         log_error() << "Teardown called on non-activated gateway: " << id();
         return false;
     }
     if (!teardownGateway()) {
         log_error() << "Could not tear down gateway: " << id();
         return false;
     }
     // Return to a state of nothingness
     m_state = GatewayState::CREATED;
     return true;
 }
void Gateway::setContainer (std::shared_ptr< ContainerAbstractInterface > container) inherited
Set the associated container for this gateway.
Definition at line 115 of file gateway.cpp.
 {
     m_container = container;
 }
bool Gateway::isConfigured () inherited
Is the gateway configured or not?
Definition at line 120 of file gateway.cpp.
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool Gateway::isActivated () inherited
Is the gateway activated or not?
Definition at line 125 of file gateway.cpp.
 {
     return m_state >= GatewayState::ACTIVATED;
 }
bool Gateway::hasContainer () protected virtual inherited
Check if the gateway has an associated container.
Inheriting gateways calls this method to know if they are safe to assume they can access a ContainerAbstractInterface instance previously set by SoftwareContainer calling setContainer()
Returns
true if there is a ContainerAbstractInterface instance set, false if not.
Definition at line 104 of file gateway.cpp.
Referenced by Gateway::activate(), NetworkGateway::activateGateway(), Gateway::executeInContainer(), and Gateway::setEnvironmentVariable().
 {
     return m_container != nullptr;
 }
std::shared_ptr< ContainerAbstractInterface > Gateway::getContainer () protected inherited
Get a handle to the associated container.
Definition at line 109 of file gateway.cpp.
Referenced by PulseGateway::activateGateway(), DeviceNodeGateway::activateGateway(), Gateway::executeInContainer(), and Gateway::setEnvironmentVariable().
 {
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
ReturnCode Gateway::setEnvironmentVariable (const std::string & variable, const std::string & value) protected inherited
Set an environment variable in the associated container.
Definition at line 130 of file gateway.cpp.
References Gateway::getContainer(), and Gateway::hasContainer().
Referenced by PulseGateway::activateGateway(), and DBusGateway::activateGateway().
 {
     if (hasContainer()) {
         return getContainer()->setEnvironmentVariable(variable, value);
     } else {
         log_error() << "Can't set environment variable on gateway without container";
         return ReturnCode::FAILURE;
     }
 }
ReturnCode Gateway::executeInContainer (const std::string & cmd) protected inherited
Execute the given command in the container.
Definition at line 143 of file gateway.cpp.
References Gateway::getContainer(), and Gateway::hasContainer().
Referenced by NetworkGateway::activateGateway().
 {
     if (hasContainer()) {
         return getContainer()->executeInContainer(cmd);
     } else {
         log_error() << "Can't execute in container from gateway without container";
         return ReturnCode::FAILURE;
     }
 }
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/files/filegateway.h
libsoftwarecontainer/src/gateway/files/filegateway.cpp