softwarecontainer: softwarecontainer::WaylandGateway Class Reference
softwarecontainer::WaylandGateway Class Reference
Public Types
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
Public Member Functions
ReturnCode readConfigElement (const json_t *element)
Gateway specific parsing of config elements.
virtual bool activateGateway ()
virtual bool teardownGateway ()
virtual const char * id ()
virtual ReturnCode setConfig (const json_t *config)
Configure this gateway according to the supplied JSON configuration string.
virtual ReturnCode activate ()
Applies any configuration set by setConfig()
virtual ReturnCode teardown ()
Restore system to the state prior to launching of gateway.
virtual void setContainer (std::shared_ptr< ContainerAbstractInterface > container)
Set the associated container for this gateway.
virtual bool isConfigured ()
Is the gateway configured or not?
virtual bool isActivated ()
Is the gateway activated or not?
Static Public Attributes
static constexpr const char * ID
static constexpr const char * WAYLAND_RUNTIME_DIR_VARIABLE_NAME
static constexpr const char * SOCKET_FILE_NAME
static constexpr const char * ENABLED_FIELD
Protected Member Functions
virtual bool hasContainer ()
Check if the gateway has an associated container.
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Get a handle to the associated container.
ReturnCode setEnvironmentVariable (const std::string &variable, const std::string &value)
Set an environment variable in the associated container.
Detailed Description
Definition at line 26 of file waylandgateway.h.
Member Function Documentation
ReturnCode softwarecontainer::WaylandGateway::readConfigElement (const json_t * element) virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
ReturnCode FAILURE if an error was encountered while parsing, SUCCESS otherwise.
Implements softwarecontainer::Gateway.
Definition at line 42 of file waylandgateway.cpp.
References softwarecontainer::JSONParser::read().
 {
     bool configValue = false;
     if (!JSONParser::read(element, ENABLED_FIELD, configValue)) {
         log_error() << "Key " << ENABLED_FIELD << " missing or not bool in json configuration";
         return ReturnCode::FAILURE;
     }
     if (!m_enabled) {
         m_enabled = configValue;
     }
     return ReturnCode::SUCCESS;
 }
virtual const char* softwarecontainer::Gateway::id () inline virtual inherited
Returns
Returns the ID of the gateway
Definition at line 93 of file gateway.h.
Referenced by softwarecontainer::Gateway::activate(), softwarecontainer::Gateway::setConfig(), and softwarecontainer::Gateway::teardown().
     {
         return m_id;
     }
ReturnCode softwarecontainer::Gateway::setConfig (const json_t * config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
ReturnCode::SUCCESS if config was successfully parsed, ReturnCode::FAILURE otherwise
Exceptions
GatewayError If called on an already activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 24 of file gateway.cpp.
References softwarecontainer::Gateway::id(), softwarecontainer::isError(), and softwarecontainer::Gateway::readConfigElement().
Referenced by softwarecontainer::DBusGateway::setConfig().
 {
     if (m_state == GatewayState::ACTIVATED) {
         log_error() << "Can not configure a gateway that is already activated: " << id();
         throw GatewayError("Gateway already activated");
     }
     if (!json_is_array(config)) {
         log_error() << "Root JSON element is not an array";
         return ReturnCode::FAILURE;
     }
     if (json_array_size(config) == 0) {
         log_error() << "Root JSON array is empty";
         return ReturnCode::FAILURE;
     }
     for(size_t i = 0; i < json_array_size(config); i++) {
         json_t *element = json_array_get(config, i);
         if (!json_is_object(element)) {
             log_error() << "json configuration is not an object";
             return ReturnCode::FAILURE;
         }
         if (isError(readConfigElement(element))) {
             log_error() << "Could not read config element";
             return ReturnCode::FAILURE;
         }
     }
     m_state = GatewayState::CONFIGURED;
     return ReturnCode::SUCCESS;
 }
ReturnCode softwarecontainer::Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
ReturnCode::SUCCESS upon successful application of configuration, ReturnCode::FAILURE otherwise
Exceptions
GatewayError If called on an already activated gateway, or if the gateway has not been previously configured, or if there is not container instance set.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 58 of file gateway.cpp.
References softwarecontainer::Gateway::hasContainer(), and softwarecontainer::Gateway::id().
Referenced by softwarecontainer::DBusGateway::activate().
{
     if (m_state == GatewayState::ACTIVATED) {
         log_error() << "Activate was called on a gateway which was already activated: " << id();
         throw GatewayError("Gateway already activated");
     }
     if (m_state != GatewayState::CONFIGURED) {
         log_error() << "Activate was called on a gateway which is not in configured state: " << id();
         throw GatewayError("Gateway is not configured");
     }
     if (!hasContainer()) {
         log_error() << "Activate was called on a gateway which has no associated container: " << id();
         throw GatewayError("Gateway does not have a container instance");
     }
     if (!activateGateway()) {
         log_error() << "Couldn't activate gateway: " << id();
         return ReturnCode::FAILURE;
     }
     m_state = GatewayState::ACTIVATED;
     return ReturnCode::SUCCESS;
 }
ReturnCode softwarecontainer::Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
ReturnCode::SUCCESS upon successful clean-up, ReturnCode::FAILURE otherwise
Exceptions
GatewayError If called on a non activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 83 of file gateway.cpp.
References softwarecontainer::Gateway::id().
Referenced by softwarecontainer::DBusGateway::teardown().
{
     if (m_state != GatewayState::ACTIVATED) {
         log_error() << "Teardown called on non-activated gateway: " << id();
         throw GatewayError("Gateway not previosly activated");
     }
     if (!teardownGateway()) {
         log_error() << "Could not tear down gateway: " << id();
         return ReturnCode::FAILURE;
     }
     // Return to a state of nothingness
     m_state = GatewayState::CREATED;
     return ReturnCode::SUCCESS;
 }
void softwarecontainer::Gateway::setContainer (std::shared_ptr< ContainerAbstractInterface > container) virtual inherited
Set the associated container for this gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 114 of file gateway.cpp.
Referenced by softwarecontainer::SoftwareContainer::addGateway(), and softwarecontainer::DBusGateway::setContainer().
 {
     m_container = container;
 }
bool softwarecontainer::Gateway::isConfigured () virtual inherited
Is the gateway configured or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 119 of file gateway.cpp.
Referenced by softwarecontainer::DBusGateway::activate(), and softwarecontainer::DBusGateway::isConfigured().
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool softwarecontainer::Gateway::isActivated () virtual inherited
Is the gateway activated or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 124 of file gateway.cpp.
Referenced by softwarecontainer::DBusGateway::isActivated(), and softwarecontainer::DBusGateway::teardown().
 {
     return m_state >= GatewayState::ACTIVATED;
 }
bool softwarecontainer::Gateway::hasContainer () protected virtual inherited
Check if the gateway has an associated container.
Inheriting gateways calls this method to know if they are safe to assume they can access a ContainerAbstractInterface instance previously set by SoftwareContainer calling setContainer()
Returns
true if there is a ContainerAbstractInterface instance set, false if not.
Definition at line 99 of file gateway.cpp.
Referenced by softwarecontainer::Gateway::activate(), softwarecontainer::NetworkGateway::activateGateway(), softwarecontainer::Gateway::getContainer(), and softwarecontainer::Gateway::setEnvironmentVariable().
 {
     return m_container != nullptr;
 }
std::shared_ptr< ContainerAbstractInterface > softwarecontainer::Gateway::getContainer () protected inherited
Get a handle to the associated container.
Exceptions
GatewayError If called before setContainer() has been called.
Definition at line 104 of file gateway.cpp.
References softwarecontainer::Gateway::hasContainer().
Referenced by softwarecontainer::NetworkGateway::activateGateway(), and softwarecontainer::Gateway::setEnvironmentVariable().
 {
     if (!hasContainer()) {
         throw GatewayError("Attempting to get container reference before any container has been assigned.");
     }
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
ReturnCode softwarecontainer::Gateway::setEnvironmentVariable (const std::string & variable, const std::string & value) protected inherited
Set an environment variable in the associated container.
Definition at line 129 of file gateway.cpp.
References softwarecontainer::Gateway::getContainer(), and softwarecontainer::Gateway::hasContainer().
Referenced by softwarecontainer::DBusGatewayInstance::activateGateway().
 {
     if (hasContainer()) {
         return getContainer()->setEnvironmentVariable(variable, value);
     } else {
         log_error() << "Can't set environment variable on gateway without container";
         return ReturnCode::FAILURE;
     }
 }
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/waylandgateway.h
libsoftwarecontainer/src/gateway/waylandgateway.cpp