softwarecontainer: softwarecontainer::DeviceNodeGateway Class Reference
softwarecontainer::DeviceNodeGateway Class Reference
This gateway is responsible for exposing device nodes in an LXC container.
#include <devicenodegateway.h>
Public Types
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
Public Member Functions
virtual ReturnCode readConfigElement (const json_t *element) override
Gateway specific parsing of config elements.
virtual bool activateGateway () override
Implements Gateway::activateGateway.
virtual bool teardownGateway () override
Implements Gateway::teardownGateway.
virtual const char * id ()
virtual ReturnCode setConfig (const std::string &config)
Configure this gateway according to the supplied JSON configuration string.
virtual ReturnCode activate ()
Applies any configuration set by setConfig()
virtual ReturnCode teardown ()
Restore system to the state prior to launching of gateway.
virtual void setContainer (std::shared_ptr< ContainerAbstractInterface > container)
Set the associated container for this gateway.
virtual bool isConfigured ()
Is the gateway configured or not?
virtual bool isActivated ()
Is the gateway activated or not?
ReturnCode bindMount (const std::string &src, const std::string &dst, bool readOnly, bool enableWriteBuffer=false)
bindMount Bind mount a src directory to another position dst.
std::string tempDir (std::string templatePath)
tempDir Creates a temporary directory at templatePath.
Static Public Attributes
static constexpr const char * ID
Protected Member Functions
virtual bool hasContainer ()
Check if the gateway has an associated container.
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Get a handle to the associated container.
ReturnCode setEnvironmentVariable (const std::string &variable, const std::string &value)
Set an environment variable in the associated container.
ReturnCode createSymLink (const std::string &source, const std::string &destination)
ReturnCode writeToFile (const std::string &path, const std::string &content)
void markFileForDeletion (const std::string &path)
ReturnCode overlayMount (const std::string &lower, const std::string &upper, const std::string &work, const std::string &dst)
overlayMount Mount a directory with an overlay on top of it.
ReturnCode syncOverlayMount (const std::string &lower, const std::string &upper)
syncOverlayMount Copy the directory structure from upper layer to the lower layer
ReturnCode createSharedMountPoint (const std::string &path)
createSharedMountPoint Make the mount point shared, ie new mount points created in one bind mount will also be created in the other mount point.
ReturnCode createDirectory (const std::string &path)
createDirectory Create a directory, and if successful append it to a list of dirs to be deleted in the dtor.
bool pathInList (const std::string path)
checks whether given path is already added to clean up handlers or not
Protected Attributes
std::vector< CleanUpHandler * > m_cleanupHandlers
m_cleanupHandlers A vector of cleanupHandlers added during the lifetime of the FileToolKitWithUndo that will be run from the destructor.
Detailed Description
This gateway is responsible for exposing device nodes in an LXC container.
The basic operation looks as follows:
DeviceNodeGateway (DNG) is loaded with a JSON configuration detailing a list of devices to create, with device names (mandatory), permission modes (optional), major (optional) and minor numbers (optional).
Notes:
activate() will stop creating devices in the container upon first failure
Definition at line 42 of file devicenodegateway.h.
Member Function Documentation
ReturnCode softwarecontainer::DeviceNodeGateway::readConfigElement (const json_t * element) override virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
ReturnCode FAILURE if an error was encountered while parsing, SUCCESS otherwise.
Implements softwarecontainer::Gateway.
Definition at line 34 of file devicenodegateway.cpp.
References softwarecontainer::isError().
 {
     DeviceNodeParser parser;
     DeviceNodeParser::Device dev;
     if (isError(parser.parseDeviceNodeGatewayConfiguration(element, dev))) {
         log_error() << "Could not parse device node configuration";
         return ReturnCode::FAILURE;
     }
     return m_logic.updateDeviceList(dev);
 }
bool softwarecontainer::DeviceNodeGateway::activateGateway () override virtual
Implements Gateway::activateGateway.
This function will iterate over all devices and issue mknod and chmod commands, which are run in the container.
Returns
true upon success; all commands executed successfully, false otherwise
Implements softwarecontainer::Gateway.
Definition at line 47 of file devicenodegateway.cpp.
References softwarecontainer::isSuccess().
 {
     auto returnValue = applySettings();
     return isSuccess(returnValue);
 }
bool softwarecontainer::DeviceNodeGateway::teardownGateway () override virtual
Implements Gateway::teardownGateway.
Implements softwarecontainer::Gateway.
Definition at line 53 of file devicenodegateway.cpp.
 {
     return true;
 }
virtual const char* softwarecontainer::Gateway::id () inline virtual inherited
Returns
Returns the ID of the gateway
Definition at line 93 of file gateway.h.
Referenced by softwarecontainer::Gateway::activate(), softwarecontainer::Gateway::setConfig(), and softwarecontainer::Gateway::teardown().
     {
         return m_id;
     }
ReturnCode softwarecontainer::Gateway::setConfig (const std::string & config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
ReturnCode::SUCCESS if config was successfully parsed, ReturnCode::FAILURE otherwise
Exceptions
GatewayError If called on an already activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 24 of file gateway.cpp.
References softwarecontainer::Gateway::id(), softwarecontainer::isError(), and softwarecontainer::Gateway::readConfigElement().
Referenced by softwarecontainer::DBusGateway::setConfig().
 {
     if (m_state == GatewayState::ACTIVATED) {
         log_error() << "Can not configure a gateway that is already activated: " << id();
         throw GatewayError("Gateway already activated");
     }
     json_error_t error;
     json_t *root = json_loads(config.c_str(), 0, &error);
     if (!root) {
         std::string errorText = logging::StringBuilder()
             << "Could not parse config: " << error.text;
         setConfigRollback(errorText,root);
         return ReturnCode::FAILURE;
     }
     if (!json_is_array(root)) {
         setConfigRollback("Root JSON element is not an array",root);
         return ReturnCode::FAILURE;
     }
     if (json_array_size(root) == 0) {
         setConfigRollback("Root JSON array is empty",root);
         return ReturnCode::FAILURE;
     }
     for(size_t i = 0; i < json_array_size(root); i++) {
         json_t *element = json_array_get(root, i);
         if (!json_is_object(element)) {
             setConfigRollback("json configuration is not an object",root);
             return ReturnCode::FAILURE;
         }
         if (isError(readConfigElement(element))) {
             setConfigRollback("Could not read config element",root);
             return ReturnCode::FAILURE;
         }
     }
     json_decref(root);
     m_state = GatewayState::CONFIGURED;
     return ReturnCode::SUCCESS;
 }
ReturnCode softwarecontainer::Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
ReturnCode::SUCCESS upon successful application of configuration, ReturnCode::FAILURE otherwise
Exceptions
GatewayError If called on an already activated gateway, or if the gateway has not been previously configured, or if there is not container instance set.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 74 of file gateway.cpp.
References softwarecontainer::Gateway::hasContainer(), and softwarecontainer::Gateway::id().
Referenced by softwarecontainer::DBusGateway::activate().
{
     if (m_state == GatewayState::ACTIVATED) {
         log_error() << "Activate was called on a gateway which was already activated: " << id();
         throw GatewayError("Gateway already activated");
     }
     if (m_state != GatewayState::CONFIGURED) {
         log_error() << "Activate was called on a gateway which is not in configured state: " << id();
         throw GatewayError("Gateway is not configured");
     }
     if (!hasContainer()) {
         log_error() << "Activate was called on a gateway which has no associated container: " << id();
         throw GatewayError("Gateway does not have a container instance");
     }
     if (!activateGateway()) {
         log_error() << "Couldn't activate gateway: " << id();
         return ReturnCode::FAILURE;
     }
     m_state = GatewayState::ACTIVATED;
     return ReturnCode::SUCCESS;
 }
ReturnCode softwarecontainer::Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
ReturnCode::SUCCESS upon successful clean-up, ReturnCode::FAILURE otherwise
Exceptions
GatewayError If called on a non activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 99 of file gateway.cpp.
References softwarecontainer::Gateway::id().
Referenced by softwarecontainer::DBusGateway::teardown().
{
     if (m_state != GatewayState::ACTIVATED) {
         log_error() << "Teardown called on non-activated gateway: " << id();
         throw GatewayError("Gateway not previosly activated");
     }
     if (!teardownGateway()) {
         log_error() << "Could not tear down gateway: " << id();
         return ReturnCode::FAILURE;
     }
     // Return to a state of nothingness
     m_state = GatewayState::CREATED;
     return ReturnCode::SUCCESS;
 }
void softwarecontainer::Gateway::setContainer (std::shared_ptr< ContainerAbstractInterface > container) virtual inherited
Set the associated container for this gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 130 of file gateway.cpp.
Referenced by softwarecontainer::SoftwareContainer::addGateway(), and softwarecontainer::DBusGateway::setContainer().
 {
     m_container = container;
 }
bool softwarecontainer::Gateway::isConfigured () virtual inherited
Is the gateway configured or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 135 of file gateway.cpp.
Referenced by softwarecontainer::DBusGateway::activate(), and softwarecontainer::DBusGateway::isConfigured().
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool softwarecontainer::Gateway::isActivated () virtual inherited
Is the gateway activated or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 140 of file gateway.cpp.
Referenced by softwarecontainer::DBusGateway::isActivated(), and softwarecontainer::DBusGateway::teardown().
 {
     return m_state >= GatewayState::ACTIVATED;
 }
bool softwarecontainer::Gateway::hasContainer () protected virtual inherited
Check if the gateway has an associated container.
Inheriting gateways calls this method to know if they are safe to assume they can access a ContainerAbstractInterface instance previously set by SoftwareContainer calling setContainer()
Returns
true if there is a ContainerAbstractInterface instance set, false if not.
Definition at line 115 of file gateway.cpp.
Referenced by softwarecontainer::Gateway::activate(), softwarecontainer::NetworkGateway::activateGateway(), softwarecontainer::Gateway::getContainer(), and softwarecontainer::Gateway::setEnvironmentVariable().
 {
     return m_container != nullptr;
 }
std::shared_ptr< ContainerAbstractInterface > softwarecontainer::Gateway::getContainer () protected inherited
Get a handle to the associated container.
Exceptions
GatewayError If called before setContainer() has been called.
Definition at line 120 of file gateway.cpp.
References softwarecontainer::Gateway::hasContainer().
Referenced by softwarecontainer::NetworkGateway::activateGateway(), and softwarecontainer::Gateway::setEnvironmentVariable().
 {
     if (!hasContainer()) {
         throw GatewayError("Attempting to get container reference before any container has been assigned.");
     }
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
ReturnCode softwarecontainer::Gateway::setEnvironmentVariable (const std::string & variable, const std::string & value) protected inherited
Set an environment variable in the associated container.
Definition at line 145 of file gateway.cpp.
References softwarecontainer::Gateway::getContainer(), and softwarecontainer::Gateway::hasContainer().
Referenced by softwarecontainer::DBusGatewayInstance::activateGateway().
 {
     if (hasContainer()) {
         return getContainer()->setEnvironmentVariable(variable, value);
     } else {
         log_error() << "Can't set environment variable on gateway without container";
         return ReturnCode::FAILURE;
     }
 }
ReturnCode softwarecontainer::FileToolkitWithUndo::bindMount (const std::string & src, const std::string & dst, bool readOnly, bool enableWriteBuffer = false) inherited
bindMount Bind mount a src directory to another position dst.
Parameters
src Path to mount from
dst Path to mount to
readOnly Make the bind mount destination read only
enableWriteBuffer Enable write buffers on the bind mount.
Returns
ReturnCode::SUCCESS on success, ReturnCode::FAILURE on failure
Definition at line 108 of file filetoolkitwithundo.cpp.
References softwarecontainer::existsInFileSystem(), softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers, and softwarecontainer::FileToolkitWithUndo::tempDir().
 {
     unsigned long flags = MS_BIND;
     std::string fstype;
     const void *data = nullptr;
     int mountRes;
     if (!existsInFileSystem(src)) {
         log_error() << src << " does not exist on the host, can not bindMount";
         return ReturnCode::FAILURE;
     }
     log_debug() << "Bind-mounting " << src << " in " << dst << ", flags: " << flags;
     if(enableWriteBuffer) {
         std::string upperDir = tempDir("/tmp/sc-bindmount-upper-XXXXXX");
         std::string workDir = tempDir("/tmp/sc-bindmount-work-XXXXXX");
         fstype.assign("overlay");
         std::ostringstream os;
         os << "lowerdir=" << src << ",upperdir=" << upperDir << ",workdir=" << workDir;
         data = os.str().c_str();
         log_debug() << "enableWriteBuffer, config: " << os.str();
         mountRes = mount("overlay", dst.c_str(), fstype.c_str(), flags, data);
     } else {
         mountRes = mount(src.c_str(), dst.c_str(), fstype.c_str(), flags, data);
     }
     if (mountRes == 0) {
         log_verbose() << "Bind-mounted folder " << src << " in " << dst;
         m_cleanupHandlers.push_back(new MountCleanUpHandler(dst));
     } else {
         log_error() << "Could not mount into container: src=" << src
                     << " , dst=" << dst << " err=" << strerror(errno);
         return ReturnCode::FAILURE;
     }
     if (readOnly) {
         flags = MS_REMOUNT | MS_RDONLY | MS_BIND;
         log_debug() << "Re-mounting read-only" << src << " in "
                     << dst << ", flags: " << flags;
         mountRes = mount(src.c_str(), dst.c_str(), fstype.c_str(), flags, data);
         if (mountRes != 0) {
             // Failure
             log_error() << "Could not re-mount " << src << " , read-only on "
                         << dst << " err=" << strerror(errno);
             return ReturnCode::FAILURE;
         }
     }
     return ReturnCode::SUCCESS;
 }
std::string softwarecontainer::FileToolkitWithUndo::tempDir (std::string templatePath) inherited
tempDir Creates a temporary directory at templatePath.
Warning
The temporary path will be destroyed when the instance of FileToolkitWithUndo is destroyed.
Parameters
templ a template Path used to create the path of the temporary directory, including XXXXXX which will be replaced with a unique ID for the temporary directory
Returns
A string path pointing to the newly creted temporary directory.
Definition at line 92 of file filetoolkitwithundo.cpp.
References softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers, and softwarecontainer::FileToolkitWithUndo::pathInList().
Referenced by softwarecontainer::FileToolkitWithUndo::bindMount().
 {
     char *dir = const_cast<char*>(templ.c_str());
     dir = mkdtemp(dir);
     if (dir == nullptr) {
         log_warning() << "Failed to create buffered Directory: " << strerror(errno);
         return nullptr;
     }
     if (!pathInList(templ)) {
         m_cleanupHandlers.push_back(new DirectoryCleanUpHandler(templ));
     }
     return std::string(dir);
 }
ReturnCode softwarecontainer::FileToolkitWithUndo::overlayMount (const std::string & lower, const std::string & upper, const std::string & work, const std::string & dst) protected inherited
overlayMount Mount a directory with an overlay on top of it.
An overlay protects the lower filesystem from writes by writing to the upper file system through the work directory.
Parameters
lower The lower file system, this will be read only.
upper The upper file system, this can be a tmpfs/ramfs of some kind. This is where final writes wind up
work This is a work directory, preferably a tmpfs/ramfs of some kind. This is where writes wind up temporarily.
dst Where the overlay filesystem will be mounted.
Returns
ReturnCode::SUCCESS on success, ReturnCode::FAILURE on failure
Definition at line 166 of file filetoolkitwithundo.cpp.
References softwarecontainer::FileToolkitWithUndo::createDirectory(), softwarecontainer::isError(), softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers, and softwarecontainer::FileToolkitWithUndo::pathInList().
Referenced by softwarecontainer::Container::create().
 {
     std::string fstype = "overlay";
     unsigned long flags = MS_BIND;
     if (isError(createDirectory(lower))
         || isError(createDirectory(upper))
         || isError(createDirectory(work))
         || isError(createDirectory(dst)))
     {
         log_error() << "Failed to create lower/upper/work directory for overlayMount. lower=" <<
                        lower << ", upper=" << upper << ", work=" << work;
         return ReturnCode::FAILURE;
     }
     std::string mountoptions = logging::StringBuilder() << "lowerdir=" << lower
                                                         << ",upperdir=" << upper
                                                         << ",workdir=" << work;
     int mountRes = mount("overlay", dst.c_str(), fstype.c_str(), flags, mountoptions.c_str());
     if (mountRes == 0) {
         log_verbose() << "overlayMounted folder " << lower << " in " << dst;
         m_cleanupHandlers.push_back(new MountCleanUpHandler(dst));
         if (!pathInList(upper)) {
             m_cleanupHandlers.push_back(new DirectoryCleanUpHandler(upper));
         }
         m_cleanupHandlers.push_back(new OverlaySyncCleanupHandler(upper, lower));
         if (!pathInList(work)) {
             m_cleanupHandlers.push_back(new DirectoryCleanUpHandler(work));
         }
     } else {
         log_error() << "Could not mount into container: upper=" << upper
                     << ",lower=" << lower
                     << ",work=" << work
                     << " at dst=" << dst << " err=" << strerror(errno);
         return ReturnCode::FAILURE;
     }
     return ReturnCode::SUCCESS;
 }
ReturnCode softwarecontainer::FileToolkitWithUndo::syncOverlayMount (const std::string & lower, const std::string & upper) protected inherited
syncOverlayMount Copy the directory structure from upper layer to the lower layer
Parameters
lower The lower layer used in an overlay file system.
upper The upper layer in an overlay file system.
Returns
ReturnCode::SUCCESS on success, ReturnCode::FAILURE on failure
Definition at line 212 of file filetoolkitwithundo.cpp.
References softwarecontainer::RecursiveCopy::copy(), and softwarecontainer::RecursiveCopy::getInstance().
 {
     return RecursiveCopy::getInstance().copy(upper, lower);
 }
ReturnCode softwarecontainer::FileToolkitWithUndo::createSharedMountPoint (const std::string & path) protected inherited
createSharedMountPoint Make the mount point shared, ie new mount points created in one bind mount will also be created in the other mount point.
Parameters
path The mount path to make shared.
Returns
ReturnCode::SUCCESS on success, ReturnCode::FAILURE on failure
Definition at line 219 of file filetoolkitwithundo.cpp.
References softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers.
Referenced by softwarecontainer::Container::initialize().
 {
     auto mountRes = mount(path.c_str(), path.c_str(), "", MS_BIND, nullptr);
     if (mountRes != 0) {
         log_error() << "Could not bind mount " << path << " to itself";
         return ReturnCode::FAILURE;
     }
     mountRes = mount(path.c_str(), path.c_str(), "", MS_UNBINDABLE, nullptr);
     if (mountRes != 0) {
         log_error() << "Could not make " << path << " unbindable";
         return ReturnCode::FAILURE;
     }
     mountRes = mount(path.c_str(), path.c_str(), "", MS_SHARED, nullptr);
     if (mountRes != 0) {
         log_error() << "Could not make " << path << " shared";
         return ReturnCode::FAILURE;
     }
     m_cleanupHandlers.push_back(new MountCleanUpHandler(path));
     log_debug() << "Created shared mount point at " << path;
     return ReturnCode::SUCCESS;
 }
ReturnCode softwarecontainer::FileToolkitWithUndo::createDirectory (const std::string & path) protected inherited
createDirectory Create a directory, and if successful append it to a list of dirs to be deleted in the dtor.
Since nestled dirs will need to be deleted in reverse order to creation insert to the beginning of the list.
Parameters
path Path of directory to be created
Returns
ReturnCode::SUCCESS on success, ReturnCode::FAILURE on failure
Definition at line 68 of file filetoolkitwithundo.cpp.
References softwarecontainer::isDirectory(), softwarecontainer::isError(), softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers, and softwarecontainer::FileToolkitWithUndo::pathInList().
Referenced by softwarecontainer::Container::initialize(), and softwarecontainer::FileToolkitWithUndo::overlayMount().
 {
     if (isDirectory(path)) {
         return ReturnCode::SUCCESS;
     }
     if(isError(createParentDirectory(path))) {
         log_error() << "Couldn't create parent directory for " << path;
         return ReturnCode::FAILURE;
     }
     if (mkdir(path.c_str(), S_IRWXU | S_IRWXG | S_IRWXO) == -1) {
         log_error() << "Could not create directory " << path << " - Reason : " << strerror(errno);
         return ReturnCode::FAILURE;
     }
     if (!pathInList(path)) {
         m_cleanupHandlers.push_back(new DirectoryCleanUpHandler(path));
     }
     log_debug() << "Created directory " << path;
     return ReturnCode::SUCCESS;
 }
bool softwarecontainer::FileToolkitWithUndo::pathInList (const std::string path) protected inherited
checks whether given path is already added to clean up handlers or not
This function will be called only before adding new CleanUpHandler for FileCleanUpHandler and DirectoryCleanUpHandler. The reason behind this, only indicated CleanUpHandlers are related with file/directory removal operations.
Parameters
a string path name to check
Returns
true if the path is already exist, false otherwise
Definition at line 245 of file filetoolkitwithundo.cpp.
References softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers.
Referenced by softwarecontainer::FileToolkitWithUndo::createDirectory(), softwarecontainer::FileToolkitWithUndo::overlayMount(), and softwarecontainer::FileToolkitWithUndo::tempDir().
 {
     for (auto element : m_cleanupHandlers) {
         if (element->queryName() == path) {
             return true;
         }
     }
     return false;
 }
Field Documentation
std::vector<CleanUpHandler *> softwarecontainer::FileToolkitWithUndo::m_cleanupHandlers protected inherited
m_cleanupHandlers A vector of cleanupHandlers added during the lifetime of the FileToolKitWithUndo that will be run from the destructor.
Definition at line 135 of file filetoolkitwithundo.h.
Referenced by softwarecontainer::FileToolkitWithUndo::bindMount(), softwarecontainer::FileToolkitWithUndo::createDirectory(), softwarecontainer::FileToolkitWithUndo::createSharedMountPoint(), softwarecontainer::FileToolkitWithUndo::overlayMount(), softwarecontainer::FileToolkitWithUndo::pathInList(), and softwarecontainer::FileToolkitWithUndo::tempDir().
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/devicenode/devicenodegateway.h
libsoftwarecontainer/src/gateway/devicenode/devicenodegateway.cpp