softwarecontainer: softwarecontainer::Workspace Class Reference
softwarecontainer::Workspace Class Reference
Holds information about the container workspace.
#include <workspace.h>
Public Member Functions
Workspace (bool enableWriteBuffer=false, const std::string &containerRootDir=SOFTWARECONTAINER_DEFAULT_WORKSPACE, const std::string &containerConfigPath=SOFTWARECONTAINER_DEFAULT_CONFIG, unsigned int containerShutdownTimeout=2)
Creates a workspace.
ReturnCode checkWorkspace ()
Check if the workspace is present and create it if needed.
Data Fields
bool m_enableWriteBuffer
std::string m_containerRootDir
std::string m_containerConfigPath
unsigned int m_containerShutdownTimeout
Private Member Functions
ReturnCode createParentDirectory (const std::string &path)
createParentDirectory Recursively tries to create the directory pointed to by path.
ReturnCode createDirectory (const std::string &path)
createDirectory Create a directory, and if successful append it to a list of dirs to be deleted in the dtor.
ReturnCode bindMount (const std::string &src, const std::string &dst, bool readOnly, bool enableWriteBuffer=false)
bindMount Bind mount a src directory to another position dst.
ReturnCode overlayMount (const std::string &lower, const std::string &upper, const std::string &work, const std::string &dst)
overlayMount Mount a directory with an overlay on top of it.
ReturnCode syncOverlayMount (const std::string &lower, const std::string &upper)
syncOverlayMount Copy the directory structure from upper layer to the lower layer
ReturnCode createSharedMountPoint (const std::string &path)
createSharedMountPoint Make the mount point shared, ie new mount points created in one bind mount will also be created in the other mount point.
ReturnCode writeToFile (const std::string &path, const std::string &content)
ReturnCode createSymLink (const std::string &source, const std::string &destination)
std::string tempDir (std::string templatePath)
tempDir Creates a temporary directory at templatePath.
Private Attributes
std::stack< CleanUpHandler * > m_cleanupHandlers
m_cleanupHandlers A stack of cleanupHandlers added during the lifetime of the FileToolKitWithUndo that will be run from the destructor.
Detailed Description
Holds information about the container workspace.
Definition at line 30 of file workspace.h.
Constructor & Destructor Documentation
Workspace::Workspace (bool enableWriteBuffer = false, const std::string & containerRootDir = SOFTWARECONTAINER_DEFAULT_WORKSPACE, const std::string & containerConfigPath = SOFTWARECONTAINER_DEFAULT_CONFIG, unsigned int containerShutdownTimeout = 2)
Creates a workspace.
Parameters
enableWriteBuffer Enable writebuffers on mountpoints
containerRootDir The path at which the container resides in the host system
containerConfigPath The path to the configuration lxc
containerShutdownTimeout The timeout time for the softwarecontainer
Definition at line 22 of file workspace.cpp.
References checkWorkspace().
                                                   :
          m_enableWriteBuffer(enableWriteBuffer),
          m_containerRootDir(containerRootDir),
          m_containerConfigPath(containerConfigPath),
          m_containerShutdownTimeout(containerShutdownTimeout)
 {
     // Make sure path ends in '/' since it might not always be checked
     if (m_containerRootDir.back() != '/') {
         m_containerRootDir += "/";
     }
     if (isError(checkWorkspace())) {
         log_error() << "Failed when checking workspace";
         assert(false);
     }
 }
Member Function Documentation
ReturnCode Workspace::checkWorkspace ()
Check if the workspace is present and create it if needed.
Definition at line 46 of file workspace.cpp.
References softwarecontainer::FileToolkitWithUndo::createDirectory().
Referenced by Workspace().
 {
     if (!isDirectory(m_containerRootDir)) {
         log_debug() << "Container root "
                     << m_containerRootDir
                     << " does not exist, trying to create";
         if(isError(createDirectory(m_containerRootDir))) {
             log_debug() << "Failed to create container root directory";
             return ReturnCode::FAILURE;
         }
     }
 #ifdef ENABLE_NETWORKGATEWAY
     // TODO: Have a way to check for the bridge using C/C++ instead of a
     // shell script. Libbridge and/or netfilter?
     std::string cmdLine = INSTALL_PREFIX;
     cmdLine += "/bin/setup_softwarecontainer.sh";
     log_debug() << "Creating workspace : " << cmdLine;
     int returnCode;
     try {
         Glib::spawn_sync("", Glib::shell_parse_argv(cmdLine),
                          static_cast<Glib::SpawnFlags>(0),
                          sigc::slot<void>(), nullptr,
                          nullptr, &returnCode);
     } catch (Glib::SpawnError e) {
         log_error() << "Failed to spawn "
                     << cmdLine << ": code "
                     << e.code() << " msg: "
                     << e.what();
         return ReturnCode::FAILURE;
     }
     if (returnCode != 0) {
         log_error() << "Return code of "
                     << cmdLine << " is non-zero";
         return ReturnCode::FAILURE;
     }
 #endif
     return ReturnCode::SUCCESS;
 }
The documentation for this class was generated from the following files:
include/workspace.h
src/workspace.cpp