softwarecontainer: softwarecontainer::NetworkGateway Class Reference
softwarecontainer::NetworkGateway Class Reference
Sets up and manages network access and routing to the container.
#include <networkgateway.h>
Public Types
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
Public Member Functions
NetworkGateway (const int32_t id, const std::string bridgeDevice, const std::string gateway, const uint8_t maskBits, std::shared_ptr< ContainerAbstractInterface > container)
Creates a network gateway.
bool readConfigElement (const json_t *element) override
Gateway specific parsing of config elements.
bool activateGateway () override
Implements Gateway::activateGateway.
bool teardownGateway () override
Implements Gateway::teardownGateway.
virtual std::string id () const
Returns the ID of the gateway.
virtual bool setConfig (const json_t *config)
Configure this gateway according to the supplied JSON configuration string.
virtual bool activate ()
Applies any configuration set by setConfig()
virtual bool teardown ()
Restore system to the state prior to launching of gateway.
virtual bool isConfigured ()
Is the gateway configured or not?
virtual bool isActivated ()
Is the gateway activated or not?
Static Public Attributes
static constexpr const char * ID
static const constexpr int FAILURE
static const constexpr int SUCCESS
static const constexpr int NO_LINK
static const constexpr int BAD_LINKUP
static const constexpr int BAD_LINKDOWN
Protected Member Functions
std::shared_ptr< ContainerAbstractInterface > getContainer ()
Get a handle to the associated container.
bool setEnvironmentVariable (const std::string &variable, const std::string &value)
Set an environment variable in the associated container.
Detailed Description
Sets up and manages network access and routing to the container.
The responsibility of NetworkGateway is to setup network connection as specified by given configuration. This configuration is described in detail in the user documentation, but a short summary of it is how to handle incoming and outgoing network packages using the three targets: ACCEPT, DROP and REJECT.
Definition at line 39 of file networkgateway.h.
Constructor & Destructor Documentation
softwarecontainer::NetworkGateway::NetworkGateway (const int32_t id, const std::string bridgeDevice, const std::string gateway, const uint8_t maskBits, std::shared_ptr< ContainerAbstractInterface > container)
Creates a network gateway.
Exceptions
SoftwareContainerError if there is an error during initialization.
Definition at line 29 of file networkgateway.cpp.
                                                                                     :
     Gateway(ID, container),
     m_netmask(maskBits),
     m_gateway(gateway),
     m_bridgeDevice(bridgeDevice),
     m_interfaceInitialized(false),
     m_containerID(id)
 {
 }
Member Function Documentation
bool softwarecontainer::NetworkGateway::readConfigElement (const json_t * element) override virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
false if an error was encountered while parsing, true otherwise.
Implements softwarecontainer::Gateway.
Definition at line 45 of file networkgateway.cpp.
References softwarecontainer::NetworkGatewayParser::parseNetworkGatewayConfiguration().
 {
     IPTableEntry e;
     NetworkGatewayParser configParser;
     if (configParser.parseNetworkGatewayConfiguration(element, e)) {
         m_entries.push_back(e);
         return true;
     } else {
         return false;
     }
 }
bool softwarecontainer::NetworkGateway::activateGateway () override virtual
Implements Gateway::activateGateway.
Implements softwarecontainer::Gateway.
Definition at line 58 of file networkgateway.cpp.
References softwarecontainer::NetworkGatewayFunctions::generateIP(), and softwarecontainer::Gateway::getContainer().
 {
     if (m_gateway.size() != 0) {
         log_debug() << "Default gateway set to " << m_gateway;
     } else {
         log_warning() << "No gateway. Network access will be disabled";
         return true;
     }
     if (!isBridgeAvailable()) {
         log_error() << "Bridge not available, expected gateway to be " << m_gateway;
         return false;
     }
     try {
         m_ip.s_addr = m_functions.generateIP(m_netmask, m_gateway, m_containerID);
     } catch (IPAllocationError &error) {
         log_error() << error.what();
         return false;
     }
     bool returnValue = up();
     if (!returnValue) {
         log_error() << "Couldn't bring the network up";
         return false;
     }
     log_debug() << "Adding iptables entries";
     for (auto entry : m_entries) {
         FunctionJob job (getContainer(), [&] () {
             return entry.applyRules() ? SUCCESS : FAILURE;
         });
         job.start();
         job.wait();
         if (job.isError()) {
             log_error() << "Failed to apply rules for entry: " << entry.toString();
             return false;
         }
     }
     return true;
 }
bool softwarecontainer::NetworkGateway::teardownGateway () override virtual
Implements Gateway::teardownGateway.
Implements softwarecontainer::Gateway.
Definition at line 102 of file networkgateway.cpp.
References softwarecontainer::Netlink::findAddresses(), softwarecontainer::Netlink::findLink(), softwarecontainer::Gateway::getContainer(), softwarecontainer::Netlink::hasAddress(), softwarecontainer::Netlink::linkDown(), softwarecontainer::Netlink::linkUp(), softwarecontainer::Netlink::setDefaultGateway(), and softwarecontainer::Netlink::setIP().
 {
     return true;
 }
std::string softwarecontainer::Gateway::id () const virtual inherited
Returns the ID of the gateway.
Returns
Returns the ID of the gateway as a string
Definition at line 35 of file gateway.cpp.
Referenced by softwarecontainer::Gateway::activate(), softwarecontainer::DBusGatewayInstance::DBusGatewayInstance(), softwarecontainer::Gateway::setConfig(), and softwarecontainer::Gateway::teardown().
 {
     return m_id;
 }
bool softwarecontainer::Gateway::setConfig (const json_t * config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
true if config was successfully parsed, false otherwise
Exceptions
GatewayError If called on an already activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 40 of file gateway.cpp.
References softwarecontainer::Gateway::id(), and softwarecontainer::Gateway::readConfigElement().
 {
     if (GatewayState::ACTIVATED == m_state && !m_isDynamic) {
         std::string message = "Can not configure a gateway that is already activated "
                               "if the gateway does not support dynamic behavior. "
                               "Gateway ID: " + id();
         log_error() << message;
         throw GatewayError(message);
     }
     if (!json_is_array(config)) {
         log_error() << "Root JSON element is not an array";
         return false;
     }
     if (json_array_size(config) == 0) {
         log_error() << "Root JSON array is empty";
         return false;
     }
     for(size_t i = 0; i < json_array_size(config); i++) {
         json_t *element = json_array_get(config, i);
         if (!json_is_object(element)) {
             log_error() << "json configuration is not an object";
             return false;
         }
         if (!readConfigElement(element)) {
             log_warning() << "Could not read config element";
             return false;
         }
     }
     m_state = GatewayState::CONFIGURED;
     return true;
 }
bool softwarecontainer::Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
true upon successful application of configuration, false otherwise
Exceptions
GatewayError If called on an already activated gateway, or if the gateway has not been previously configured, or if there is not container instance set.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 77 of file gateway.cpp.
References softwarecontainer::Gateway::id().
{
     if (GatewayState::ACTIVATED == m_state && !m_isDynamic) {
         std::string message =  "Can not activate a gateway that is already activated "
                                "if the gateway does not support dynamic behavior. "
                                "Gateway ID: " + id();
         log_error() << message;
         throw GatewayError(message);
     }
     if (GatewayState::CONFIGURED != m_state) {
         std::string message = "Activate was called on a gateway which is not in configured state. "
                               "Gateway ID: " + id();
         log_error() << message;
         throw GatewayError(message);
     }
     if (!activateGateway()) {
         log_error() << "Couldn't activate gateway: " << id();
         return false;
     }
     m_state = GatewayState::ACTIVATED;
     return true;
 }
bool softwarecontainer::Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
true upon successful clean-up, false otherwise
Exceptions
GatewayError If called on a non activated gateway.
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 102 of file gateway.cpp.
References softwarecontainer::Gateway::id().
Referenced by softwarecontainer::DBusGatewayInstance::DBusGatewayInstance().
{
     if (GatewayState::ACTIVATED != m_state) {
         std::string message = "Teardown called on non-activated gateway. Gateway ID:  " + id();
         log_error() << message;
         throw GatewayError(message);
     }
     if (!teardownGateway()) {
         log_error() << "Could not tear down gateway: " << id();
         return false;
     }
     // Return to a state of nothingness
     m_state = GatewayState::CREATED;
     return true;
 }
bool softwarecontainer::Gateway::isConfigured () virtual inherited
Is the gateway configured or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 125 of file gateway.cpp.
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool softwarecontainer::Gateway::isActivated () virtual inherited
Is the gateway activated or not?
Reimplemented in softwarecontainer::DBusGateway.
Definition at line 130 of file gateway.cpp.
Referenced by softwarecontainer::DBusGatewayInstance::DBusGatewayInstance().
 {
     return m_state >= GatewayState::ACTIVATED;
 }
std::shared_ptr< ContainerAbstractInterface > softwarecontainer::Gateway::getContainer () protected inherited
Get a handle to the associated container.
Exceptions
GatewayError If called before setContainer() has been called.
Definition at line 119 of file gateway.cpp.
Referenced by activateGateway(), softwarecontainer::DBusGatewayInstance::activateGateway(), softwarecontainer::WaylandGateway::readConfigElement(), and teardownGateway().
 {
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
bool softwarecontainer::Gateway::setEnvironmentVariable (const std::string & variable, const std::string & value) protected inherited
Set an environment variable in the associated container.
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/network/networkgateway.h
libsoftwarecontainer/src/gateway/network/networkgateway.cpp