softwarecontainer: Netlink Class Reference
Netlink Class Reference
Handles various network operations over netlink.
#include <netlink.h>
Public Types
typedef std::pair< rtattr, void * > AttributeInfo
typedef std::vector
< AttributeInfo > AttributeList
typedef std::pair< ifinfomsg,
AttributeList > LinkInfo
typedef std::pair< ifaddrmsg,
AttributeList > AddressInfo
typedef std::pair< rtmsg,
AttributeList > RouteInfo
Public Member Functions
Netlink ()
Construct a new Netlink object.
virtual ~Netlink ()
release all resources held by the Netlink object
ReturnCode getKernelDump ()
get a dump of all links, addresses and routes from the kernel.
virtual ReturnCode checkKernelDump ()
check for a kernel dump, and if not present, try to get one
ReturnCode setDefaultGateway (const char *gatewayAddress)
Sets an ip address as the default gateway.
ReturnCode linkUp (const int ifaceIndex)
Bring the given interface up.
ReturnCode linkDown (const int ifaceIndex)
Bring a given interface down.
ReturnCode setIP (const int ifaceIndex, const in_addr ip, const int netmask)
Sets an IP address for a network link.
ReturnCode findLink (const char *ifaceName, LinkInfo &linkInfo)
Check that the device given is a network bridge.
ReturnCode findAddresses (const unsigned int interfaceIndex, std::vector< AddressInfo > &result)
Get all addresses associated with the given interface index.
ReturnCode hasAddress (const std::vector< AddressInfo > &haystack, const int addressFamily, const char *needle)
checks if an address is present in the given list
Detailed Description
Handles various network operations over netlink.
Some of the code in this class is based on code shown here, written by Jean Lorchat http://iijean.blogspot.se/2010/03/howto-get-list-of-network-interfaces-in.html
Definition at line 35 of file netlink.h.
Constructor & Destructor Documentation
Netlink::Netlink ()
Construct a new Netlink object.
This will do a setup of the sockets needed to talk netlink to the kernel, and will also call getKernelDump()
Definition at line 27 of file netlink.cpp.
References getKernelDump().
 {
     m_sequenceNumber = 1;
     m_hasKernelDump = false;
     m_netlinkInitialized = false;
     if (isError(setupNetlink())) {
         fprintf(stderr, "Failed to setup netlink\n");
     }
     if (isError(getKernelDump())) {
         fprintf(stderr, "Failed to initialize cache\n");
     }
 }
Netlink::~Netlink () virtual
release all resources held by the Netlink object
Since we allocate everything on the stack, except for the netlink attributes which we save as void pointers, we basically go through all data structures and free those pointers.
Also shuts down the communication with the kernel.
Definition at line 42 of file netlink.cpp.
 {
     if (m_netlinkInitialized) {
         shutdown(m_fd, SHUT_RDWR);
         close(m_fd);
     }
     if (m_hasKernelDump) {
         clearCache();
     }
 }
Member Function Documentation
ReturnCode Netlink::getKernelDump ()
get a dump of all links, addresses and routes from the kernel.
To get a dump of all links/addresses/routes we only need to use the generic netlink family message type, and for that we only need to set family (AF_PACKET).
This is done by sending RTM_GETLINK, RTM_GETADDR and RTM_GETROUTE as a general message (rtgenmsg) to the kernel.
After running this successfully, there will be a local cache of these network objects, which is needed to run some of the other functions.
Returns
ReturnCode::SUCCESS on success, ReturnCode::FAILURE otherwise
See also
clearCache()
Definition at line 447 of file netlink.cpp.
Referenced by checkKernelDump(), and Netlink().
 {
     m_hasKernelDump = false;
     netlink_request<rtgenmsg> link_msg = createMessage<rtgenmsg>(RTM_GETLINK, NLM_F_DUMP);
     link_msg.pay.rtgen_family = AF_PACKET;
     if (isError(sendMessage(link_msg))) {
         return ReturnCode::FAILURE;
     }
     netlink_request<rtgenmsg> addr_msg = createMessage<rtgenmsg>(RTM_GETADDR, NLM_F_DUMP);
     addr_msg.pay.rtgen_family = AF_PACKET;
     if (isError(sendMessage(addr_msg))) {
         return ReturnCode::FAILURE;
     }
     netlink_request<rtgenmsg> route_msg = createMessage<rtgenmsg>(RTM_GETROUTE, NLM_F_DUMP);
     route_msg.pay.rtgen_family = AF_PACKET;
     if (isError(sendMessage(route_msg))) {
         return ReturnCode::FAILURE;
     }
     m_hasKernelDump = true;
     return ReturnCode::SUCCESS;
 }
ReturnCode Netlink::checkKernelDump () virtual
check for a kernel dump, and if not present, try to get one
Returns
ReturnCode::SUCCESS if there a kernel dump was found or could be fetched
ReturnCode::FAILURE otherwise
Definition at line 473 of file netlink.cpp.
References getKernelDump().
Referenced by findAddresses(), findLink(), and linkUp().
 {
     if (!m_hasKernelDump && isError(getKernelDump())) {
         fprintf(stderr, "Could not get cache dump from kernel\n");
         return ReturnCode::FAILURE;
     }
     return ReturnCode::SUCCESS;
 }
ReturnCode Netlink::setDefaultGateway (const char * gatewayAddress)
Sets an ip address as the default gateway.
Parameters
gatewayAddress the address to set
Returns
ReturnCode::SUCCESS on success
ReturnCode::FAILURE otherwise
Definition at line 172 of file netlink.cpp.
 {
     netlink_request<rtmsg> set_gw = createMessage<rtmsg>(RTM_NEWROUTE, NLM_F_CREATE | NLM_F_REPLACE);
     set_gw.pay.rtm_family = AF_INET;
     set_gw.pay.rtm_table = RT_TABLE_MAIN;
     set_gw.pay.rtm_protocol = RTPROT_STATIC;
     set_gw.pay.rtm_scope = RT_SCOPE_UNIVERSE;
     set_gw.pay.rtm_type = RTN_UNICAST;
     struct in_addr gw_addr;
     if (inet_aton(gatewayAddress, &gw_addr) == 0) {
         return ReturnCode::FAILURE;
     }
     addAttribute(set_gw, RTA_GATEWAY, sizeof(gw_addr), &gw_addr);
     return sendMessage(set_gw);
 }
ReturnCode Netlink::linkUp (const int ifaceIndex)
Bring the given interface up.
Sets the UP flag for the given interface, if it exists.
Parameters
ifaceIndex the index for the interface to bring up
Returns
ReturnCode::SUCCESS if the interface was found and brought up
ReturnCode::FAILURE otherwise
Definition at line 191 of file netlink.cpp.
References checkKernelDump().
 {
     if (isError(checkKernelDump())) {
         return ReturnCode::FAILURE;
     }
     for (LinkInfo link : m_links) {
         ifinfomsg ifinfo = link.first;
         if (ifinfo.ifi_index != ifaceIndex) {
             continue;
         }
         // First, bring the link up
         netlink_request<ifinfomsg> msg_up = createMessage<ifinfomsg>(RTM_NEWLINK, NLM_F_CREATE);
         msg_up.pay.ifi_family = AF_UNSPEC;
         msg_up.pay.ifi_flags = ifinfo.ifi_flags | IFF_UP;
         msg_up.pay.ifi_change |= IFF_UP;
         msg_up.pay.ifi_index = ifinfo.ifi_index;
         if (isError(sendMessage(msg_up))) {
             fprintf(stderr, "Failed to bring device %i up\n", ifinfo.ifi_index);
             return ReturnCode::FAILURE;
         } else {
             return ReturnCode::SUCCESS;
         }
     }
     return ReturnCode::FAILURE;
 }
ReturnCode Netlink::linkDown (const int ifaceIndex)
Bring a given interface down.
Parameters
ifaceIndex the index for the interface to bring down
Returns
ReturnCode::SUCCESS if interface was found and brought down
ReturnCode::FAILURE otherwise
Definition at line 257 of file netlink.cpp.
 {
     for (LinkInfo link : m_links) {
         ifinfomsg ifinfo = link.first;
         if(ifinfo.ifi_type == ARPHRD_LOOPBACK) {
             continue; // This is the loopback device
         }
         netlink_request<ifinfomsg> down_msg = createMessage<ifinfomsg>(RTM_NEWLINK, 0);
         down_msg.pay.ifi_family = AF_UNSPEC;
         down_msg.pay.ifi_index = ifinfo.ifi_index;
         down_msg.pay.ifi_flags = ~IFF_UP;
         down_msg.pay.ifi_change = IFF_UP;
         if (isError(sendMessage(down_msg))) {
             return ReturnCode::FAILURE;
         } else {
             return ReturnCode::SUCCESS;
         }
     }
     return ReturnCode::FAILURE;
 }
ReturnCode Netlink::setIP (const int ifaceIndex, const in_addr ip, const int netmask)
Sets an IP address for a network link.
Parameters
ifaceIndex the index for the interface to set ip for
ip the ipv4 address to set
netmask the netmask in CIDR format (for example 24)
Returns
ReturnCode::SUCCESS if interface was found and IP was set
ReturnCode::FAILURE otherwise
Definition at line 220 of file netlink.cpp.
 {
     for (LinkInfo link : m_links) {
         ifinfomsg ifinfo = link.first;
         if (ifinfo.ifi_index != ifaceIndex) {
             continue;
         }
         // TODO: Support for ipv6
         netlink_request<ifaddrmsg> msg_setip = createMessage<ifaddrmsg>(RTM_NEWADDR, NLM_F_CREATE | NLM_F_REPLACE);
         msg_setip.pay.ifa_family = AF_INET; // ipv4
         msg_setip.pay.ifa_prefixlen = netmask;
         msg_setip.pay.ifa_scope = RT_SCOPE_UNIVERSE;
         msg_setip.pay.ifa_index = ifinfo.ifi_index; // interface (link)
         // Calculate broadcast address from ip address
         // TODO: Use the netmask instead?!
         in_addr_t netpart = inet_netof(ip);
         struct in_addr bcast_addr = inet_makeaddr(netpart, inet_addr("0.0.0.255"));
         addAttribute(msg_setip, IFA_LOCAL, sizeof(ip), &ip);
         addAttribute(msg_setip, IFA_BROADCAST, sizeof(bcast_addr), &bcast_addr);
         // No matter what happens, we return since we found the link we've been looking for.
         if (isError(sendMessage(msg_setip))) {
             // TODO: pton to print ip number also.
             fprintf(stderr, "Failed to set ip on link %i\n", ifinfo.ifi_index);
             return ReturnCode::FAILURE;
         } else {
             return ReturnCode::SUCCESS;
         }
     }
     // No link found, that's a failure.
     return ReturnCode::FAILURE;
 }
ReturnCode Netlink::findLink (const char * ifaceName, LinkInfo & linkInfo)
Check that the device given is a network bridge.
Parameters
ifaceName the name of the interface
ifaceIndex the index of the interface (out parameter)
Returns
ReturnCode::SUCCESS if interface with matching name was found.
ReturnCode::FAILURE otherwise.
Definition at line 281 of file netlink.cpp.
References checkKernelDump().
 {
     if (isError(checkKernelDump())) {
         return ReturnCode::FAILURE;
     }
     for (LinkInfo link : m_links) {
         AttributeList attributes = link.second;
         for (AttributeInfo attrinfo : attributes) {
             rtattr attr = attrinfo.first;
             void *data = attrinfo.second;
             if (attr.rta_type == IFLA_IFNAME) {
                 char *ifname = (char *) data;
                 if (strcmp(ifname, ifaceName) == 0) {
                     linkInfo = link;
                     return ReturnCode::SUCCESS;
                 }
             }
         }
     }
     return ReturnCode::FAILURE;
 }
ReturnCode Netlink::findAddresses (const unsigned int interfaceIndex, std::vector< AddressInfo > & result)
Get all addresses associated with the given interface index.
Parameters
interfaceIndex the interface address to get addresses for
result the vector to place all addresses in (out parameter)
Returns
ReturnCode::SUCCESS on success
ReturnCode::FAILURE otherwise
Definition at line 306 of file netlink.cpp.
References checkKernelDump().
 {
     if (isError(checkKernelDump())) {
         return ReturnCode::FAILURE;
     }
     for (AddressInfo addressInfo : m_addresses) {
         ifaddrmsg addrmsg = addressInfo.first;
         if (addrmsg.ifa_index == interfaceIndex) {
             result.push_back(addressInfo);
         }
     }
     return ReturnCode::SUCCESS;
 }
ReturnCode Netlink::hasAddress (const std::vector< AddressInfo > & haystack, const int addressFamily, const char * needle)
checks if an address is present in the given list
Parameters
haystack the list to search in
addressFamily the address family, AF_INET or AF_INET6
needle the ip address to search for, in dotted notation
Returns
ReturnCode::SUCCESS if the address is in the haystack
ReturnCode::FAILURE otherwise
Definition at line 323 of file netlink.cpp.
 {
     for (AddressInfo addressInfo : haystack) {
         AttributeList attributes = addressInfo.second;
         for (AttributeInfo attrPair : attributes) {
             // Skip if this attribute is not an address attribute
             rtattr attr = attrPair.first;
             if (attr.rta_type != IFA_ADDRESS && attr.rta_type != IFA_LOCAL) {
                 continue;
             }
             void *data = attrPair.second;
             char out[INET6_ADDRSTRLEN];
             // It is ok here for inet_ntop to fail (data could be bad)
             if (inet_ntop(addressFamily, data, out, sizeof(out)) && strcmp(out, needle) == 0) {
                 return ReturnCode::SUCCESS;
             }
         }
     }
     return ReturnCode::FAILURE;
 }
The documentation for this class was generated from the following files:
include/netlink.h
src/netlink.cpp