softwarecontainer: CgroupsGateway Class Reference
CgroupsGateway Class Reference
The cgroups gateway sets cgroups related settings for the container.
#include <cgroupsgateway.h>
Public Types
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
typedef std::function< int()> ContainerFunction
Execute a function in the container.
Public Member Functions
ReturnCode readConfigElement (const json_t *element) override
Gateway specific parsing of config elements.
bool activateGateway () override
bool teardownGateway () override
virtual const char * id ()
virtual bool setConfig (const std::string &config)
Configure this gateway according to the supplied JSON configuration string.
virtual bool activate ()
Applies any configuration set by setConfig()
virtual bool teardown ()
Restore system to the state prior to launching of gateway.
bool hasContainer ()
Check if the gateway has an associated container.
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Get a reference to the associated container.
void setContainer (std::shared_ptr< ContainerAbstractInterface > container)
Set the associated contaitner for this gateway.
bool isConfigured ()
Is the gateway configured or not?
bool isActivated ()
Is the gateway activated or not?
ReturnCode setEnvironmentVariable (const std::string &variable, const std::string &value)
ReturnCode executeInContainer (const std::string &cmd)
Execute the given command in the container.
ReturnCode executeInContainer (ContainerFunction func)
Static Public Attributes
static constexpr const char * ID
Protected Member Functions
bool read (const json_t *element, const char *key, std::string &result)
Reads a string from a JSON Object.
bool read (const json_t *element, const char *key, bool &result)
Reads a boolean from a JSON Object.
bool read (const json_t *element, const char *key, int &result)
Reads an integer from a JSON Object.
Protected Attributes
std::shared_ptr
< ContainerAbstractInterface > m_container
const char * m_id
GatewayState m_state
Static Protected Attributes
static constexpr const char * ENABLED_FIELD
static constexpr const char * XDG_RUNTIME_DIR_VARIABLE_NAME
Detailed Description
The cgroups gateway sets cgroups related settings for the container.
Definition at line 30 of file cgroupsgateway.h.
Member Typedef Documentation
typedef std::function<int ()> Gateway::ContainerFunction inherited
Execute a function in the container.
Definition at line 144 of file gateway.h.
Member Function Documentation
ReturnCode CgroupsGateway::readConfigElement (const json_t * element) override virtual
Gateway specific parsing of config elements.
All gateways implement this method in order to provide gateway specific parsing of the configuration content.
Parameters
element A JSON configuration item.
Returns
ReturnCode FAILURE if an error was encountered while parsing, SUCCESS otherwise.
Implements Gateway.
Definition at line 34 of file cgroupsgateway.cpp.
References softwarecontainer::JSONParser::read().
 {
     std::string settingKey;
     std::string settingValue;
     if (!read(element, "setting", settingKey)) {
         log_error() << "Key \"setting\" either not a string or not in json configuration";
         return ReturnCode::FAILURE;
     }
     if (!read(element, "value", settingValue)) {
         log_error() << "Key \"value\" either not a string or not in json configuration";
         return ReturnCode::FAILURE;
     }
     if (m_settings.count(settingKey) > 0) {
         log_warning() << "setting '" << settingKey << "' is set more than once, may be problematic.";
     }
     m_settings.insert( std::pair<std::string, std::string>(settingKey, settingValue) );
     return ReturnCode::SUCCESS;
 }
virtual const char* Gateway::id () inline virtual inherited
Returns
Returns the ID of the gateway
Definition at line 68 of file gateway.h.
Referenced by Gateway::activate(), softwarecontainer::SoftwareContainer::setGatewayConfigs(), and Gateway::teardown().
     {
         return m_id;
     }
bool Gateway::setConfig (const std::string & config) virtual inherited
Configure this gateway according to the supplied JSON configuration string.
Parameters
config JSON string containing gateway-specific JSON configuration
Returns
true if config was successfully parsed false otherwise
Definition at line 25 of file gateway.cpp.
References Gateway::readConfigElement().
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
 {
     json_error_t error;
     json_t *root = json_loads(config.c_str(), 0, &error);
     if (!root) {
         log_error() << "Could not parse config: " << error.text;
         return false;
     }
     if (json_is_array(root)) {
         for(size_t i = 0; i < json_array_size(root); i++) {
             json_t *element = json_array_get(root, i);
             if (json_is_object(element)) {
                 if (isError(readConfigElement(element))) {
                     log_error() << "Could not read config element";
                     return false;
                 }
             } else {
                 log_error() << "json configuration is not an object";
                 return false;
             }
         }
     } else {
         log_error() << "Root JSON element is not an array";
         return false;
     }
     m_state = GatewayState::CONFIGURED;
     return true;
 }
bool Gateway::activate () virtual inherited
Applies any configuration set by setConfig()
Returns
true upon successful application of configuration false otherwise
Definition at line 56 of file gateway.cpp.
References Gateway::hasContainer(), and Gateway::id().
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
{
     if (m_state != GatewayState::CONFIGURED) {
         log_warning() << "Activate was called on a gateway which is not in configured state: " << id();
         return false;
     }
     if (!hasContainer()) {
         log_warning() << "Activate was called on a gateway which has no associated container: " << id();
         return false;
     }
     return activateGateway();
 }
bool Gateway::teardown () virtual inherited
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
true upon successful clean-up, false otherwise
Definition at line 70 of file gateway.cpp.
References Gateway::id().
{
     if (m_state != GatewayState::ACTIVATED) {
         log_warning() << "Teardown called on non-activated gateway " << id();
     }
     return teardownGateway();
 }
bool Gateway::hasContainer () inherited
Check if the gateway has an associated container.
Definition at line 78 of file gateway.cpp.
Referenced by Gateway::activate(), NetworkGateway::activateGateway(), and Gateway::executeInContainer().
 {
     return m_container != nullptr;
 }
std::shared_ptr< ContainerAbstractInterface > Gateway::getContainer () inherited
Get a reference to the associated container.
Definition at line 83 of file gateway.cpp.
Referenced by PulseGateway::activateGateway(), DeviceNodeGateway::activateGateway(), and Gateway::executeInContainer().
 {
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
void Gateway::setContainer (std::shared_ptr< ContainerAbstractInterface > container) inherited
Set the associated contaitner for this gateway.
Definition at line 89 of file gateway.cpp.
 {
     m_container = container;
 }
bool Gateway::isConfigured () inherited
Is the gateway configured or not?
Definition at line 94 of file gateway.cpp.
Referenced by softwarecontainer::SoftwareContainer::setGatewayConfigs().
 {
     return m_state >= GatewayState::CONFIGURED;
 }
bool Gateway::isActivated () inherited
Is the gateway activated or not?
Definition at line 99 of file gateway.cpp.
 {
     return m_state >= GatewayState::ACTIVATED;
 }
ReturnCode Gateway::executeInContainer (const std::string & cmd) inherited
Execute the given command in the container.
Definition at line 117 of file gateway.cpp.
References Gateway::getContainer(), and Gateway::hasContainer().
 {
     if (hasContainer()) {
         return getContainer()->executeInContainer(cmd);
     } else {
         log_error() << "Can't execute in container from gateway without container";
         return ReturnCode::FAILURE;
     }
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, std::string & result) protected inherited
Reads a string from a JSON Object.
Tries to read a string value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the string could not be read, either due to the given object does not contain the given key or the given key did not hold a string, false will be returned and the result reference will not be changed.
Returns
True: If the string was successfully read.
False: If the string could not be read.
Definition at line 26 of file jsonparser.cpp.
Referenced by EnvironmentGateway::readConfigElement(), WaylandGateway::readConfigElement(), readConfigElement(), FileGateway::readConfigElement(), PulseGateway::readConfigElement(), NetworkGateway::readConfigElement(), and DeviceNodeGateway::readConfigElement().
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         return false;
     }
     if (!json_is_string(value)) {
         log_error() << "json element is not a string";
         return false;
     }
     result = json_string_value(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, bool & result) protected inherited
Reads a boolean from a JSON Object.
Tries to read a boolean value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the boolean could not be read, either due to the given object does not contain the given key or the given key did not hold a boolean value, false will be returned and the result reference will not be changed.
Returns
True: If the boolean was successfully read.
False: If the boolean could not be read.
Definition at line 42 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         return false;
     }
     if (!json_is_boolean(value)) {
         log_error() << "json element is not a boolean";
         return false;
     }
     result = json_is_true(value);
     return true;
 }
bool softwarecontainer::JSONParser::read (const json_t * element, const char * key, int & result) protected inherited
Reads an integer from a JSON Object.
Tries to read an integer value form a given JSON object using a given key. If the read is successful true will be returned and the result reference will be populated with the read value. If the integer could not be read, either due to the given object does not contain the given key or the given key did not hold an integer value, false will be returned and the result reference will not be changed.
Returns
True: If the integer was successfully read.
False: If the integer could not be read.
Definition at line 58 of file jsonparser.cpp.
 {
     json_t *value = json_object_get(element, key);
     if (!value) {
         return false;
     }
     if (!json_is_integer(value)) {
         log_error() << "json element is not an integer";
         return false;
     }
     result = json_integer_value(value);
     return true;
 }
The documentation for this class was generated from the following files:
src/gateway/cgroupsgateway.h
src/gateway/cgroupsgateway.cpp