softwarecontainer: softwarecontainer::DBusGateway Class Reference
softwarecontainer::DBusGateway Class Reference
Public Types
enum GatewayState : unsigned int { CREATED, CONFIGURED, ACTIVATED }
Public Member Functions
DBusGateway (const std::string &gatewayDir, const std::string &name)
virtual ReturnCode setConfig (const std::string &config) override
Sets config for both dbus session instances.
virtual ReturnCode activate () override
Activates both dbus session instances.
virtual ReturnCode readConfigElement (const json_t *) override
Stubbed since this class only does containment.
virtual bool activateGateway () override
Stubbed since this class only does containment.
virtual bool teardownGateway () override
Stubbed since this class only does containment.
virtual void setContainer (std::shared_ptr< ContainerAbstractInterface > container) override
Set the associated container for this gateway.
virtual ReturnCode teardown () override
Restore system to the state prior to launching of gateway.
virtual bool isConfigured () override
Is the gateway configured or not?
virtual bool isActivated () override
Is the gateway activated or not?
virtual const char * id ()
Static Public Attributes
static constexpr const char * ID
Protected Member Functions
virtual bool hasContainer ()
Check if the gateway has an associated container.
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Get a handle to the associated container.
ReturnCode setEnvironmentVariable (const std::string &variable, const std::string &value)
Set an environment variable in the associated container.
Detailed Description
Definition at line 27 of file dbusgateway.h.
Member Function Documentation
ReturnCode softwarecontainer::DBusGateway::setConfig (const std::string & config) override virtual
Sets config for both dbus session instances.
Reimplemented from softwarecontainer::Gateway.
Definition at line 36 of file dbusgateway.cpp.
References softwarecontainer::isError(), and softwarecontainer::Gateway::setConfig().
 {
     try {
         log_debug() << "Setting config for dbus session bus";
         ReturnCode sessionBusParseResult = sessionBus.setConfig(config);
         log_debug() << "Setting config for dbus system bus";
         ReturnCode systemBusParseResult = systemBus.setConfig(config);
         if (isError(sessionBusParseResult) && isError(systemBusParseResult)) {
             log_error() << "Neither session nor system bus could use the given config";
             return ReturnCode::FAILURE;
         }
     } catch (GatewayParserError &err) {
         log_error() << "Bad config in one of the gateway configurations";
         return ReturnCode::FAILURE;
     }
      return ReturnCode::SUCCESS;
 }
ReturnCode softwarecontainer::DBusGateway::activate () override virtual
Activates both dbus session instances.
Reimplemented from softwarecontainer::Gateway.
Definition at line 57 of file dbusgateway.cpp.
References softwarecontainer::Gateway::activate(), softwarecontainer::Gateway::isConfigured(), and softwarecontainer::isError().
 {
      ReturnCode sessionBusActivationResult = ReturnCode::FAILURE;
      if (sessionBus.isConfigured()) {
          log_debug() << "Activating dbus session bus";
          sessionBusActivationResult = sessionBus.activate();
      }
      ReturnCode systemBusActivationResult = ReturnCode::FAILURE;
      if (systemBus.isConfigured()) {
          log_debug() << "Activating dbus system bus";
          sessionBusActivationResult = systemBus.activate();
      }
      if (isError(sessionBusActivationResult) && isError(systemBusActivationResult)) {
          log_error() << "Neither dbus session bus nor dbus system bus could be activated";
          return ReturnCode::FAILURE;
      }
      return ReturnCode::SUCCESS;
 }
virtual ReturnCode softwarecontainer::DBusGateway::readConfigElement (const json_t *) inline override virtual
Stubbed since this class only does containment.
Implements softwarecontainer::Gateway.
Definition at line 50 of file dbusgateway.h.
 { return ReturnCode::SUCCESS; }
virtual bool softwarecontainer::DBusGateway::activateGateway () inline override virtual
Stubbed since this class only does containment.
Implements softwarecontainer::Gateway.
Definition at line 55 of file dbusgateway.h.
 { return true; }
virtual bool softwarecontainer::DBusGateway::teardownGateway () inline override virtual
Stubbed since this class only does containment.
Implements softwarecontainer::Gateway.
Definition at line 60 of file dbusgateway.h.
 { return true; }
void softwarecontainer::DBusGateway::setContainer (std::shared_ptr< ContainerAbstractInterface > container) override virtual
Set the associated container for this gateway.
Reimplemented from softwarecontainer::Gateway.
Definition at line 104 of file dbusgateway.cpp.
References softwarecontainer::Gateway::setContainer().
 {
     sessionBus.setContainer(container);
     systemBus.setContainer(container);
 }
ReturnCode softwarecontainer::DBusGateway::teardown () override virtual
Restore system to the state prior to launching of gateway.
Any cleanup code (removal of files, virtual interfaces, etc) should be placed here.
Returns
ReturnCode::SUCCESS upon successful clean-up, ReturnCode::FAILURE otherwise
Exceptions
GatewayError If called on a non activated gateway.
Reimplemented from softwarecontainer::Gateway.
Definition at line 78 of file dbusgateway.cpp.
References softwarecontainer::Gateway::isActivated(), softwarecontainer::isError(), and softwarecontainer::Gateway::teardown().
 {
      ReturnCode sessionBusTeardownResult;
      if (sessionBus.isActivated()) {
          log_debug() << "Tearing down dbus session bus";
          sessionBusTeardownResult = sessionBus.teardown();
      } else {
          sessionBusTeardownResult = ReturnCode::FAILURE;
      }
      ReturnCode systemBusTeardownResult ;
      if (systemBus.isActivated()) {
          log_debug() << "Tearing down dbus system bus";
          systemBusTeardownResult = systemBus.teardown();
      } else {
          systemBusTeardownResult = ReturnCode::FAILURE;
      }
      if (isError(sessionBusTeardownResult) && isError(systemBusTeardownResult)) {
          log_error() << "Neither dbus session bus nor dbus system bus could be tore down";
          return ReturnCode::FAILURE;
      }
      return ReturnCode::SUCCESS;
 }
bool softwarecontainer::DBusGateway::isConfigured () override virtual
Is the gateway configured or not?
Reimplemented from softwarecontainer::Gateway.
Definition at line 110 of file dbusgateway.cpp.
References softwarecontainer::Gateway::isConfigured().
 {
     return sessionBus.isConfigured() || systemBus.isConfigured();
 }
bool softwarecontainer::DBusGateway::isActivated () override virtual
Is the gateway activated or not?
Reimplemented from softwarecontainer::Gateway.
Definition at line 115 of file dbusgateway.cpp.
References softwarecontainer::Gateway::isActivated().
 {
     return sessionBus.isActivated() || systemBus.isActivated();
 }
virtual const char* softwarecontainer::Gateway::id () inline virtual inherited
Returns
Returns the ID of the gateway
Definition at line 93 of file gateway.h.
Referenced by softwarecontainer::Gateway::activate(), softwarecontainer::Gateway::setConfig(), and softwarecontainer::Gateway::teardown().
     {
         return m_id;
     }
bool softwarecontainer::Gateway::hasContainer () protected virtual inherited
Check if the gateway has an associated container.
Inheriting gateways calls this method to know if they are safe to assume they can access a ContainerAbstractInterface instance previously set by SoftwareContainer calling setContainer()
Returns
true if there is a ContainerAbstractInterface instance set, false if not.
Definition at line 115 of file gateway.cpp.
Referenced by softwarecontainer::Gateway::activate(), softwarecontainer::NetworkGateway::activateGateway(), softwarecontainer::Gateway::getContainer(), and softwarecontainer::Gateway::setEnvironmentVariable().
 {
     return m_container != nullptr;
 }
std::shared_ptr< ContainerAbstractInterface > softwarecontainer::Gateway::getContainer () protected inherited
Get a handle to the associated container.
Exceptions
GatewayError If called before setContainer() has been called.
Definition at line 120 of file gateway.cpp.
References softwarecontainer::Gateway::hasContainer().
Referenced by softwarecontainer::NetworkGateway::activateGateway(), and softwarecontainer::Gateway::setEnvironmentVariable().
 {
     if (!hasContainer()) {
         throw GatewayError("Attempting to get container reference before any container has been assigned.");
     }
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
ReturnCode softwarecontainer::Gateway::setEnvironmentVariable (const std::string & variable, const std::string & value) protected inherited
Set an environment variable in the associated container.
Definition at line 145 of file gateway.cpp.
References softwarecontainer::Gateway::getContainer(), and softwarecontainer::Gateway::hasContainer().
Referenced by softwarecontainer::DBusGatewayInstance::activateGateway().
 {
     if (hasContainer()) {
         return getContainer()->setEnvironmentVariable(variable, value);
     } else {
         log_error() << "Can't set environment variable on gateway without container";
         return ReturnCode::FAILURE;
     }
 }
The documentation for this class was generated from the following files:
libsoftwarecontainer/src/gateway/dbus/dbusgateway.h
libsoftwarecontainer/src/gateway/dbus/dbusgateway.cpp