softwarecontainer: softwarecontainer::RecursiveCopy Class Reference
softwarecontainer::RecursiveCopy Class Reference
The RecursiveCopy class is a singleton class used to copy files recursively from a source to a destination.
#include <recursivecopy.h>
Public Member Functions
RecursiveCopy (RecursiveCopy &s)=delete
Disallow copy and operator constructors.
void operator= (RecursiveCopy const &s)=delete
ReturnCode copy (std::string src, std::string dst)
copy Copy files from src to dst
Static Public Member Functions
static RecursiveCopy & getInstance ()
getInstance Gets the RecursiveCopy instance.
Detailed Description
The RecursiveCopy class is a singleton class used to copy files recursively from a source to a destination.
Definition at line 29 of file recursivecopy.h.
Constructor & Destructor Documentation
softwarecontainer::RecursiveCopy::RecursiveCopy (RecursiveCopy & s) delete
Disallow copy and operator constructors.
Member Function Documentation
RecursiveCopy & softwarecontainer::RecursiveCopy::getInstance () static
getInstance Gets the RecursiveCopy instance.
Returns
The RecursiveCopy instance.
Definition at line 70 of file recursivecopy.cpp.
Referenced by softwarecontainer::OverlaySyncCleanupHandler::clean(), and softwarecontainer::FileToolkitWithUndo::syncOverlayMount().
 {
     static RecursiveCopy instance;
     return instance;
 }
ReturnCode softwarecontainer::RecursiveCopy::copy (std::string src, std::string dst)
copy Copy files from src to dst
The function is protected by a mutex because it uses some non thread-safe C functions.
Parameters
src The source path to copy from
dst The destination path to copy to
Returns
ReturnCode::SUCCESS on success
ReturnCode::FAILURE on failure
Definition at line 76 of file recursivecopy.cpp.
Referenced by softwarecontainer::OverlaySyncCleanupHandler::clean(), and softwarecontainer::FileToolkitWithUndo::syncOverlayMount().
 {
     ReturnCode retval = ReturnCode::SUCCESS;
     m_copyLock.lock();
     dstRoot.assign(dst);
     srcRoot.assign(src);
     if (ftw(src.c_str(), copyFile, 20) != 0) {
         log_error() << "Failed to recursively copy " << src << " to " << dst;
         retval = ReturnCode::FAILURE;
     }
     m_copyLock.unlock();
     return retval;
 }
The documentation for this class was generated from the following files:
common/recursivecopy.h
common/recursivecopy.cpp