softwarecontainer: Config Class Reference
Config Class Reference
Public Member Functions
Config (std::unique_ptr< ConfigLoaderAbstractInterface > loader, std::unique_ptr< ConfigDefaults > defaults, const std::map< std::string, std::string > &stringOptions=std::map< std::string, std::string >(), const std::map< std::string, int > &intOptions=std::map< std::string, int >(), const std::map< std::string, bool > &boolOptions=std::map< std::string, bool >())
Constructor.
std::string getStringValue (const std::string &group, const std::string &key) const
getStringValue Get a config value of type string
int getIntegerValue (const std::string &group, const std::string &key) const
getIntegerValue Get a config value of type integer
bool getBooleanValue (const std::string &group, const std::string &key) const
getBooleanValue Get a config value of type boolean
template<>
std::string getGlibValue (const std::string &group, const std::string &key) const
template<>
bool getGlibValue (const std::string &group, const std::string &key) const
template<>
int getGlibValue (const std::string &group, const std::string &key) const
Static Public Attributes
static const std::string SC_CONFIG_PATH_INITIAL_VALUE
static const int PRELOAD_COUNT_INITIAL_VALUE
static const bool KEEP_CONTAINERS_ALIVE_INITIAL_VALUE
static const int SHUTDOWN_TIMEOUT_INITIAL_VALUE
static const std::string SERVICE_MANIFEST_DIR_INITIAL_VALUE
static const std::string DEFAULT_SERVICE_MANIFEST_DIR_INITIAL_VALUE
static const bool USE_SESSION_BUS_INITIAL_VALUE
static const std::string SC_GROUP
static const std::string PRELOAD_COUNT_KEY
static const std::string KEEP_CONTAINERS_ALIVE_KEY
static const std::string USE_SESSION_BUS_KEY
static const std::string SHUTDOWN_TIMEOUT_KEY
static const std::string SHARED_MOUNTS_DIR_KEY
static const std::string LXC_CONFIG_PATH_KEY
static const std::string SERVICE_MANIFEST_DIR_KEY
static const std::string DEFAULT_SERVICE_MANIFEST_DIR_KEY
Detailed Description
Definition at line 44 of file config.h.
Constructor & Destructor Documentation
Config::Config (std::unique_ptr< ConfigLoaderAbstractInterface > loader, std::unique_ptr< ConfigDefaults > defaults, const std::map< std::string, std::string > & stringOptions = std::map<std::string, std::string>(), const std::map< std::string, int > & intOptions = std::map<std::string, int>(), const std::map< std::string, bool > & boolOptions = std::map<std::string, bool>())
Constructor.
The optional params takes any potential explicitly set configs, e.g. read as command line options. These values will take precedence over any existing values with the same key in the static configuration.
If no configs are found among the explicit set configs or in the config file provided by the loader, the default values will be used as a last resort.
If no explicit configs are to be used, this Constructor can be called by passing only the 'loader' and 'defaults' arguments. Otherwise all parameters needs to be passed.
It is an error to not provide default configuration values. Not finding values in any of the other sources, i.e. explicit or config file, will not cause an error unless there are problems parsing.
Parameters
loader An interface to a loader which provides the underlying config to this class
defaults An interface to default configs
stringOptions A string:string map with config keys and corresponding values
intOptions A string:int map with config keys and corresponding values
boolOptions A string:bool map with config keys and corresponding values
Exceptions
softwarecontainer::ConfigError On error
Definition at line 48 of file config.cpp.
                                                            :
     m_defaults(std::move(defaults)),
     m_stringOptions(stringOptions),
     m_intOptions(intOptions),
     m_boolOptions(boolOptions)
 {
     try {
         m_config = loader->loadConfig();
     } catch (Glib::Error &error) {
         throw softwarecontainer::ConfigError();
     }
 }
Member Function Documentation
std::string Config::getStringValue (const std::string & group, const std::string & key) const
getStringValue Get a config value of type string
Parameters
group The name of the config group the value belongs to
key The key for the config value
Returns
A string with the config value
Definition at line 66 of file config.cpp.
Referenced by softwarecontainer::SoftwareContainerAgent::SoftwareContainerAgent().
 {
     return getValue<std::string>(group, key, m_stringOptions);
 }
int Config::getIntegerValue (const std::string & group, const std::string & key) const
getIntegerValue Get a config value of type integer
Parameters
group The name of the config group the value belongs to
key The key for the config value
Returns
An int with the config value
Definition at line 71 of file config.cpp.
Referenced by softwarecontainer::SoftwareContainerAgent::SoftwareContainerAgent().
 {
     return getValue<int>(group, key, m_intOptions);
 }
bool Config::getBooleanValue (const std::string & group, const std::string & key) const
getBooleanValue Get a config value of type boolean
Parameters
group The name of the config group the value belongs to
key The key for the config value
Returns
A bool with the config value
Definition at line 76 of file config.cpp.
Referenced by softwarecontainer::SoftwareContainerAgent::SoftwareContainerAgent().
 {
     return getValue<bool>(group, key, m_boolOptions);
 }
The documentation for this class was generated from the following files:
agent/src/config/config.h
agent/src/config/config.cpp