softwarecontainer: softwarecontainer::SoftwareContainer Class Reference
softwarecontainer::SoftwareContainer Class Reference
An abstraction of concrete container implementations.
#include <softwarecontainer.h>
Public Member Functions
LOG_DECLARE_CLASS_CONTEXT ("PCL","SoftwareContainer library")
SoftwareContainer (const ContainerID id, std::unique_ptr< const SoftwareContainerConfig > config)
Creates a new SoftwareContainer instance.
ReturnCode startGateways (const GatewayConfiguration &configs)
Starts the Gateways by setting the gateway configurations and activating the configured gateway.
std::shared_ptr< FunctionJob > createFunctionJob (const std::function< int()> fun)
Create a job that can run a function in a container.
std::shared_ptr< CommandJob > createCommandJob (const std::string &command)
Create a job that can run a command in a container.
void shutdown ()
Shut down the container.
void shutdown (unsigned int timeout)
Shot down the container with an explicit timeout.
void suspend ()
Suspend the container.
void resume ()
Resume a suspended container.
ReturnCode bindMount (const std::string &pathOnHost, const std::string &pathInContainer, bool readonly=true)
Should only be called on containers in state 'READY'.
ObservableProperty
< ContainerState > & getContainerState ()
Get the state of this container instance.
std::shared_ptr
< ContainerAbstractInterface > getContainer ()
Rturns a pointer to the underlying container implementation.
bool previouslyConfigured ()
Indicates if gateways have been configured previously.
void addGateway (Gateway *gateway)
Only used for testing, should not be used by e.g.
Private Member Functions
ReturnCode bindMount (const std::string &src, const std::string &dst, bool readOnly, bool enableWriteBuffer=false)
bindMount Bind mount a src directory to another position dst.
std::string tempDir (std::string templatePath)
tempDir Creates a temporary directory at templatePath.
ReturnCode createSymLink (const std::string &source, const std::string &destination)
ReturnCode writeToFile (const std::string &path, const std::string &content)
void markFileForDeletion (const std::string &path)
ReturnCode overlayMount (const std::string &lower, const std::string &upper, const std::string &work, const std::string &dst)
overlayMount Mount a directory with an overlay on top of it.
ReturnCode syncOverlayMount (const std::string &lower, const std::string &upper)
syncOverlayMount Copy the directory structure from upper layer to the lower layer
ReturnCode createSharedMountPoint (const std::string &path)
createSharedMountPoint Make the mount point shared, ie new mount points created in one bind mount will also be created in the other mount point.
ReturnCode createDirectory (const std::string &path)
createDirectory Create a directory, and if successful append it to a list of dirs to be deleted in the dtor.
bool pathInList (const std::string path)
checks whether given path is already added to clean up handlers or not
Private Attributes
std::vector< CleanUpHandler * > m_cleanupHandlers
m_cleanupHandlers A vector of cleanupHandlers added during the lifetime of the FileToolKitWithUndo that will be run from the destructor.
Detailed Description
An abstraction of concrete container implementations.
SoftwareContainer (SC) can be in various states. Some method calls are only valid when SC is in a particular state.
States:
READY
SUSPENDED
TERMINATED
INVALID
When SC is in state 'READY', all relevant gateways are added and the underlying container implementation is created and initialized. In this state, the following methods are allowed to be called:
suspend() - successful call triggers transition to SUSPENDED
shutdown() - successful call triggers trasition to TERMINATED
bindMount()
startGateways()
getContainer()
createFunctionJob()
createCommandJob()
When SC is in state 'SUSPENDED', the following method calls are allowed to be called:
shutdown() - successful call triggers a transition to TERMINATED
resume() - successful call triggers a transition to READY
When SC is in state 'INVALID', something has gone wrong in the underlying container implementation and the container should be considered to be in a broken state from which it cannot recover.
The following methods are allowed to be called in every state:
getContainerState()
If a call is made when SC is in an inappropriate state, the InvalidOperationError exception is thrown. This error does not mean that the intended operation was erroneous, since the operation can't even be performed in the current state.
It is an error to call a method on a state which would be the result of the operation, e.g. calling suspend on a suspended container is an invalid operation. The reason for this is that the interface should be clear that there can't be any side effects or other changes when making a call which is redundant.
Definition at line 165 of file softwarecontainer.h.
Constructor & Destructor Documentation
softwarecontainer::SoftwareContainer::SoftwareContainer (const ContainerID id, std::unique_ptr< const SoftwareContainerConfig > config)
Creates a new SoftwareContainer instance.
On successful creation, the state will be 'READY'.
Parameters
id The containerID to use.
config An object holding all needed settings for the container
Exceptions
SoftwareContainerError If unable to set up the needed directories or network settings for this container, or if anything goes wrong when creating and initializing the underlying container implementation.
Definition at line 58 of file softwarecontainer.cpp.
References softwarecontainer::isError().
                                                                                          :
     m_containerID(id),
     m_config(std::move(config)),
     m_previouslyConfigured(false)
 {
     checkWorkspace();
 #ifdef ENABLE_NETWORKGATEWAY
     checkNetworkSettings();
 #endif // ENABLE_NETWORKGATEWAY
     m_container = std::shared_ptr<ContainerAbstractInterface>(
         new Container("SC-" + std::to_string(id),
                       m_config->containerConfigPath(),
                       m_config->sharedMountsDir(),
                       m_config->enableWriteBuffer(),
                       m_config->containerShutdownTimeout()));
     if(isError(init())) {
         throw SoftwareContainerError("Could not initialize SoftwareContainer, container ID: "
                                      + std::to_string(id));
     }
     m_containerState.setValueNotify(ContainerState::READY);
 }
Member Function Documentation
ReturnCode softwarecontainer::SoftwareContainer::startGateways (const GatewayConfiguration & configs)
Starts the Gateways by setting the gateway configurations and activating the configured gateway.
This should only be called on containers in state 'READY'
Returns
ReturnCode::SUCCESS If configuration and activation was successful
ReturnCode::FAILURE If configuration or activation encountered a non-fatal error
Exceptions
GatewayError If configuration or activation of any gateway encountered a fatal error.
InvalidOperationError If called when state is not 'READY'
InvalidContainerError If the container is in state 'INVALID'
Definition at line 169 of file softwarecontainer.cpp.
References softwarecontainer::isError().
 {
     assertValidState();
     if (m_containerState != ContainerState::READY) {
         std::string message = "Invalid to start gateways on non ready container " +
                               std::string(m_container->id());
         log_error() << message;
         throw InvalidOperationError(message);
     }
     ReturnCode result = ReturnCode::SUCCESS;
     result = configureGateways(gwConfig);
     if (isError(result)) {
         return result;
     }
     result = activateGateways();
     if (isError(result)) {
         return result;
     }
     // Keep track of if user has called this method at least once
     m_previouslyConfigured = true;
     return result;
 }
std::shared_ptr< FunctionJob > softwarecontainer::SoftwareContainer::createFunctionJob (const std::function< int()> fun)
Create a job that can run a function in a container.
This should only be called on containers in state 'READY'
Exceptions
InvalidOperationError If called when state is not 'READY'
InvalidContainerError If the container is in state 'INVALID'
Definition at line 387 of file softwarecontainer.cpp.
References getContainer().
 {
     assertValidState();
     if (m_containerState != ContainerState::READY) {
         std::string message = "Invalid to execute code in non ready container " +
                               std::string(m_container->id());
         log_error() << message;
         throw InvalidOperationError(message);
     }
     auto containerInterface = getContainer();
     return std::make_shared<FunctionJob>(containerInterface, fun);
 }
std::shared_ptr< CommandJob > softwarecontainer::SoftwareContainer::createCommandJob (const std::string & command)
Create a job that can run a command in a container.
This should only be called on containers in state 'READY'
Exceptions
InvalidOperationError If called when state is not 'READY'
InvalidContainerError If the container is in state 'INVALID'
Definition at line 402 of file softwarecontainer.cpp.
References getContainer().
 {
     assertValidState();
     if (m_containerState != ContainerState::READY) {
         std::string message = "Invalid to execute code in non ready container " +
                               std::string(m_container->id());
         log_error() << message;
         throw InvalidOperationError(message);
     }
     auto containerInterface = getContainer();
     return std::make_shared<CommandJob>(containerInterface, command);
 }
void softwarecontainer::SoftwareContainer::shutdown ()
Shut down the container.
A successful call to this method triggers a transition to state 'TERMINATED'.
This shoud only be called on containers in state 'READY' or 'SUSPENDED'
If the operation is not successful, the container state will be set to 'INVALID'. This means that this container instance should be considered broken.
Exceptions
ContainerError If operation was unsucessful InvalidOperationError If called when state is not 'READY' or 'SUSPENDED'
InvalidContainerError If the container is in state 'INVALID'
Definition at line 256 of file softwarecontainer.cpp.
 {
     return shutdown(m_config->containerShutdownTimeout());
 }
void softwarecontainer::SoftwareContainer::shutdown (unsigned int timeout)
Shot down the container with an explicit timeout.
Same as the shutdown() method, but the value passed will override any timeout value in the main configuration.
Parameters
timeout Seconds to use for timeout
Definition at line 261 of file softwarecontainer.cpp.
References softwarecontainer::isError().
 {
     assertValidState();
     log_debug() << "shutdown called";
     if (m_containerState != ContainerState::READY
         && m_containerState != ContainerState::SUSPENDED)
     {
         std::string message = "Invalid to shut down container which is not ready or suspended " +
                               std::string(m_container->id());
         log_error() << message;
         throw InvalidOperationError(message);
     }
     if(isError(shutdownGateways())) {
         log_error() << "Could not shut down all gateways cleanly, check the log";
     }
     if(isError(m_container->destroy(timeout))) {
         std::string message = "Could not destroy the container during shutdown " +
                               std::string(m_container->id());
         log_error() << message;
         m_containerState.setValueNotify(ContainerState::INVALID);
         throw ContainerError(message);
     }
     m_containerState.setValueNotify(ContainerState::TERMINATED);
 }
void softwarecontainer::SoftwareContainer::suspend ()
Suspend the container.
This suspends any execution inside the container until resume is called. A successful call to this method triggers a transition to state 'SUSPENDED'.
If the operation is not successful, the container state will be set to 'INVALID'. This means that this container instance should be considered broken.
Exceptions
ContainerError If operation was unsuccessful
InvalidOperationError If called when state is not 'READY'
InvalidContainerError If the container is in state 'INVALID'
Definition at line 291 of file softwarecontainer.cpp.
References softwarecontainer::isError().
 {
     assertValidState();
     std::string id = std::string(m_container->id());
     if (m_containerState != ContainerState::READY) {
         std::string message = "Invalid to suspend non ready container " + id;
         log_error() << message;
         throw InvalidOperationError(message);
     }
     if (isError(m_container->suspend())) {
         std::string message =  "Failed to suspend container " + id;
         log_error() << message;
         m_containerState.setValueNotify(ContainerState::INVALID);
         throw ContainerError(message);
     }
     log_debug() << "Suspended container " << id;
     m_containerState.setValueNotify(ContainerState::SUSPENDED);
 }
void softwarecontainer::SoftwareContainer::resume ()
Resume a suspended container.
This resumes execution of a container that was suspended. A successful call to this method will trigger a transition to state 'READY'.
If the operation is not successful, the container state will be set to 'INVALID'. This means that this container instance should be considered broken.
Exceptions
ContainerError If operation was unsucessful
InvalidOperationError If called when state is not 'SUSPENDED'
InvalidContainerError If the container is in state 'INVALID'
Definition at line 314 of file softwarecontainer.cpp.
References softwarecontainer::isError().
 {
     assertValidState();
     std::string id = std::string(m_container->id());
     if (m_containerState != ContainerState::SUSPENDED) {
         std::string message =  "Invalid to resume non suspended container " + id;
         log_error() << message;
         throw InvalidOperationError(message);
     }
     if (isError(m_container->resume())) {
         std::string message = "Failed to resume container " + id;
         log_error() << message;
         m_containerState.setValueNotify(ContainerState::INVALID);
         throw ContainerError(message);
     }
     log_debug() << "Resumed container " << id;
     m_containerState.setValueNotify(ContainerState::READY);
 }
ReturnCode softwarecontainer::SoftwareContainer::bindMount (const std::string & pathOnHost, const std::string & pathInContainer, bool readonly = true)
Should only be called on containers in state 'READY'.
Exceptions
InvalidOperationError If called when state is not 'READY'
InvalidContainerError If the container is in state 'INVALID'
Definition at line 417 of file softwarecontainer.cpp.
References getContainer().
 {
     assertValidState();
     std::string id = std::string(m_container->id());
     if (m_containerState != ContainerState::READY) {
         std::string message = "Invalid to bind mount in non ready container " + id;
         log_error() << message;
         throw InvalidOperationError(message);
     }
     return getContainer()->bindMountInContainer(pathOnHost, pathInContainer, readonly);
 }
ObservableProperty< ContainerState > & softwarecontainer::SoftwareContainer::getContainerState ()
Get the state of this container instance.
Returns
ContainerState representing the current state
Definition at line 382 of file softwarecontainer.cpp.
 {
     return m_containerState;
 }
std::shared_ptr< ContainerAbstractInterface > softwarecontainer::SoftwareContainer::getContainer ()
Rturns a pointer to the underlying container implementation.
This should only be called on a container in state 'READY'
Exceptions
InvalidOperationError If called when state is not 'READY'
InvalidContainerError If the container is in state 'INVALID'
Definition at line 354 of file softwarecontainer.cpp.
Referenced by bindMount(), createCommandJob(), and createFunctionJob().
 {
     assertValidState();
     std::string id = std::string(m_container->id());
     if (m_containerState != ContainerState::READY) {
         std::string message = "Invalid to access container implementation when "
                               "not ready " + id;
         log_error() << message;
         throw InvalidOperationError(message);
     }
     std::shared_ptr<ContainerAbstractInterface> ptrCopy = m_container;
     return ptrCopy;
 }
bool softwarecontainer::SoftwareContainer::previouslyConfigured ()
Indicates if gateways have been configured previously.
The user should use this method to check if startGateways have been called previously.
TODO: This should be removed when quick-launch is implemented
Returns
true if startGateways has been called previously, false if not
Definition at line 441 of file softwarecontainer.cpp.
 {
     return m_previouslyConfigured;
 }
void softwarecontainer::SoftwareContainer::addGateway (Gateway * gateway)
Only used for testing, should not be used by e.g.
the launcher
TODO: Remove or change scope of this method if possible.
Definition at line 163 of file softwarecontainer.cpp.
References softwarecontainer::Gateway::setContainer().
 {
     gateway->setContainer(m_container);
     m_gateways.push_back(std::move(std::unique_ptr<Gateway>(gateway)));
 }
The documentation for this class was generated from the following files:
libsoftwarecontainer/include/softwarecontainer.h
libsoftwarecontainer/src/softwarecontainer.cpp