softwarecontainer: softwarecontainer Namespace Reference
softwarecontainer Namespace Reference
Developers guide to adding a config item:
Data Structures
class BadSuffixError
class BaseConfigStore
class BoolConfig
Represents a config item of type bool.
class CapabilityParseError
An error occured in ConfigStore when parsing a Capability in a Service Manifest.
class CgroupsGateway
The cgroups gateway sets cgroups related settings for the container.
class CgroupsGatewayError
class CGroupsParser
class CleanUpHandler
class CommandJob
Use this class to execute a command line in a SoftwareContainer.
class CommandlineConfigSource
A config source representing the commandline options.
class Config
Represents the configuration of SoftwareContainer (the component)
class ConfigDefinition
class ConfigDependencyError
class ConfigError
class ConfigFileError
An error occured in a Glib operation.
class ConfigInternalError
An error occured which is an internal error in the config code.
class ConfigItem
Base class for all config item types.
class ConfigLoader
class ConfigMandatoryError
class ConfigNotFoundError
A requested config item could not be found in any of the config sources.
class ConfigSource
Base class for all config sources.
class ConfigStoreError
class ConfigTypes
class ConfigUnknownError
A config is found which is not defined in ConfigDefinition.
class Container
The Container class is an abstraction of the specific containment technology used.
class ContainerAbstractInterface
class ContainerError
An error has occured in the underlying container implementation.
class ContainerOptionParseError
class ContainerOptionParser
class DBusGateway
class DBusGatewayInstance
DBus Gateway takes care of spawning and killing the DBus proxies.
class DBusGatewayParser
class DefaultConfigSource
Represents the default config values.
class DefaultConfigStore
class DeviceNodeGateway
This gateway is responsible for exposing device nodes in an LXC container.
class DeviceNodeLogic
This class is responsible for storing all device node configurations in a well-formed list.
class DeviceNodeParser
class DirectoryCleanUpHandler
class DynamicContainerOptions
class EnvironmentGateway
Environment Gateway is used to define environment variables to the container.
class EnvironmentGatewayParser
class Executable
class FileCleanUpHandler
The FileCleanUpHandler class is a subclass of CleanUpHandler that deletes a file.
class FileConfigLoader
class FileGateway
This gateway lets you map files (including socket files) or folders from the host into the container's filesystem.
class FileGatewayParser
class FileGatewaySettingStore
class FileToolkitWithUndo
class FilteredConfigStore
class FunctionJob
Run a C++ function lambda inside a SoftwareContainer.
class Gateway
Gateway base class for SoftwareContainer.
class GatewayConfiguration
class GatewayError
class GatewayParserError
class IntConfig
Represents a config item of type int.
class InvalidContainerError
The container instance is in an invalid state and should not be used.
class InvalidOperationError
A method was called which is inappropriate in the current state.
class IPAllocationError
class IPTableEntry
A rules entry for the treatment of packets.
class JobAbstract
Abstract class for jobs which get executed inside a container.
class JSonError
class JSONParser
Convenience layer for the Jansson JSON parser.
class LimitRangeError
class MainConfigSource
class MountCleanUpHandler
class Netlink
Handles various network operations over netlink.
class NetworkGateway
Sets up and manages network access and routing to the container.
class NetworkGatewayError
class NetworkGatewayFunctions
Sets up and manages network access and routing to the container.
class NetworkGatewayParser
class OverlaySyncCleanupHandler
The OverlaySyncCleanupHandler class is used to copy files on cleanup and can be added to the CleanupHandler stack in the FileToolkitWithUndo class.
class PulseGateway
The PulseAudio Gateway is used to provide access to the host system PulseAudio server.
class RecursiveCopy
The RecursiveCopy class is a singleton class used to copy files recursively from a source to a destination.
class ServiceManifestParseError
An error occured in ConfigStore when parsing a Service Manifest.
class ServiceManifestPathError
An error occured in ConfigStore relating to the path to the Service Manifest(s)
class SignalConnectionsHandler
The SignalConnectionsHandler class contains references to sigc++ connections and automatically disconnects them on destruction.
class SoftwareContainer
An abstraction of concrete container implementations.
class SoftwareContainerAgent
class SoftwareContainerAgentAdaptor
class SoftwareContainerAgentError
An error occured in SoftwareContainerAgent.
class SoftwareContainerConfig
Contains all values that should be passed to SoftwareContainer on creation.
class SoftwareContainerError
class StringConfig
Represents a config item of type string.
class WaylandGateway
Typedefs
typedef std::vector
< std::tuple< std::string,
std::string, ConfigType,
MandatoryFlag > > ConfigItems
typedef std::pair< std::string,
std::string > UniqueKey
typedef std::vector< UniqueKey > MandatoryConfigs
typedef std::map< UniqueKey,
std::vector< UniqueKey > > ConfigDependencies
typedef std::map< UniqueKey,
ConfigType > TypeMap
typedef bool MandatoryFlag
typedef int32_t ContainerID
typedef std::map< std::string,
std::string > EnvironmentVariables
typedef logging::DefaultLogContext LogContext
Enumerations
enum ConfigType { String, Integer, Boolean }
Represents the type of a config value.
enum ConfigSourceType { Commandline, Main, Default }
enum ReturnCode { FAILURE, SUCCESS }
The ReturnCode enum contains common return values.
enum ContainerState { READY, SUSPENDED, TERMINATED, INVALID }
Functions
LOG_DEFINE_APP_IDS ("SCAG","SoftwareContainer agent")
LOG_DECLARE_DEFAULT_CONTEXT (PAM_DefaultLogContext,"MAIN","Main context")
int copyFile (const char *, const struct stat, int)
int copyFile (const char *srcPath, const struct stat *sb, int typeflag)
copy_file Copy files from src_path to dst_root global path
void addProcessListener (SignalConnectionsHandler &connections, pid_t pid, std::function< void(pid_t, int)> function, Glib::RefPtr< Glib::MainContext > context)
addProcessListener Adds a glib child watch for a process.
LOG_DECLARE_DEFAULT_CONTEXT (defaultLogContext,"MAIN","Main context")
bool getStat (const std::string &path, struct stat &st)
bool isDirectory (const std::string &path)
isDirectory Check if path is a directory
bool isDirectoryEmpty (const std::string &path)
isDirectoryEmpty Check if path is empty
bool isFile (const std::string &path)
isFile Check if path is a file
bool isPipe (const std::string &path)
isPipe Check if path is a pipe
bool isSocket (const std::string &path)
isSocket Check if path is a socket
bool existsInFileSystem (const std::string &path)
existsInFileSystem Check if path exists
std::string parentPath (const std::string &path_)
std::string baseName (const std::string &path)
std::string buildPath (const std::string &arg1, const std::string &arg2)
std::string buildPath (const std::string &arg1, const std::string &arg2, const std::string &arg3)
ReturnCode touch (const std::string &path)
ReturnCode writeToFile (const std::string &path, const std::string &content)
ReturnCode readFromFile (const std::string &path, std::string &content)
bool parseInt (const char *arg, int *result)
ReturnCode bool2ReturnCode (bool b)
bool2ReturnCode Convert bool to ReturnCode
bool isError (ReturnCode code)
isError Check if ReturnCode indicates Error or not
bool isSuccess (ReturnCode code)
isSuccess Check if ReturnCode indicates Success or not
int waitForProcessTermination (pid_t pid)
waitForProcessTermination Waits for a process to terminate and then returns the status of the process terminating.
Variables
const MandatoryFlag Mandatory
const MandatoryFlag Optional
const int ITEM_INDEX_GROUP
const int ITEM_INDEX_KEY
const int ITEM_INDEX_TYPE
const int ITEM_INDEX_MANDATORY
const ConfigItems CONFIGS
static constexpr ContainerID INVALID_CONTAINER_ID
std::string dstRoot
std::string srcRoot
static constexpr pid_t INVALID_PID
static constexpr int INVALID_FD
static constexpr uid_t ROOT_UID
static constexpr const char * LXC_CONTAINERS_ROOT_CONFIG_ITEM
Detailed Description
Developers guide to adding a config item:
Add a definition of the string used as key
If the config will be possible to set with a command line option, also add an "intial value" set to something which is possible to use for testing if the user set it, i.e. an "impossible" value.
Add an entry for the config to the CONFIGS data
Enumeration Type Documentation
enum softwarecontainer::ConfigType strong
Represents the type of a config value.
This is used to specify the type of the a value when mandatory configs are defined. This information is later used to know how a key should be used to retrive a value, e.g. what type specific methods can be used.
Definition at line 32 of file configtypes.h.
 {
     String,
     Integer,
     Boolean
 };
enum softwarecontainer::ReturnCode strong
The ReturnCode enum contains common return values.
Definition at line 42 of file softwarecontainer-common.h.
 {
     FAILURE,
     SUCCESS
 };
Function Documentation
int softwarecontainer::copyFile (const char * srcPath, const struct stat * sb, int typeflag)
copy_file Copy files from src_path to dst_root global path
This function is wrapped and hidden in this separate code unit because of it's side effects and used by the RecursiveCopy::copy() function.
Parameters
src_path The path of the file to copy
sb not used in this function
typeflag Points to what type of node is traversed by ftw(). Uses the global variables dst_root and src_root to know the root directories being copied to and from. These must not be changed while ftw is running or the function will misbehave.
Returns
always 0 for now.
Definition at line 49 of file recursivecopy.cpp.
 {
     std::string dstPath;
     std::string src(srcPath);
     if (src.find(srcRoot) != std::string::npos) {
         dstPath = buildPath(dstRoot, src.erase(0, srcRoot.length()));
     } else {
         dstPath = buildPath(dstRoot, src);
     }
     switch(typeflag) {
     case FTW_D:
         mkdir(dstPath.c_str(), sb->st_mode);
         break;
     case FTW_F:
         std::ifstream src(srcPath, std::ios::binary);
         std::ofstream dst(dstPath, std::ios::binary);
         dst << src.rdbuf();
     }
     return 0;
 }
void softwarecontainer::addProcessListener (SignalConnectionsHandler & connections, pid_t pid, std::function< void(pid_t, int)> function, Glib::RefPtr< Glib::MainContext > context) inline
addProcessListener Adds a glib child watch for a process.
Warning
This is not thread safe!
Parameters
connections Add the signal to this list of connections
pid The pid to watch for.
function A lambda/function pointer to run when the signal is sent for a process.
context glib context to attach the SignalChildWatch to.
Definition at line 58 of file signalconnectionshandler.h.
References softwarecontainer::SignalConnectionsHandler::addConnection().
Referenced by softwarecontainer::SoftwareContainerAgent::execute().
 {
     Glib::SignalChildWatch watch = context->signal_child_watch();
     auto connection = watch.connect(function, pid);
     connections.addConnection(connection);
 }
bool softwarecontainer::isDirectory (const std::string & path)
isDirectory Check if path is a directory
Parameters
path Path to check
Returns
true/false
Definition at line 43 of file softwarecontainer-common.cpp.
Referenced by softwarecontainer::Container::bindMountInContainer(), and softwarecontainer::FileToolkitWithUndo::createDirectory().
 {
     struct stat st;
     if (getStat(path, st)) {
         return S_ISDIR(st.st_mode);
     }
     return false;
 }
bool softwarecontainer::isDirectoryEmpty (const std::string & path)
isDirectoryEmpty Check if path is empty
Parameters
path The path to check
Returns
false if the directory is not empty
false if the directory does not exist
true if the directory is empty
Definition at line 53 of file softwarecontainer-common.cpp.
{
     int n = 0;
     constexpr int EMPTY_DIR_SIZE=2;
     struct dirent *d;
     DIR *dir = opendir(path.c_str());
     if (dir == NULL) { //Not a directory or doesn't exist
         return true;
     }
     while ((d = readdir(dir)) != NULL) {
         ++n;
         if(n > EMPTY_DIR_SIZE) {
             break;
         }
     }
     closedir(dir);
     if (n <= EMPTY_DIR_SIZE) { //Directory Empty
         return true;
     } else {
         return false;
     }
 }
bool softwarecontainer::isFile (const std::string & path)
isFile Check if path is a file
Parameters
path Path to check
Returns
true/false
Definition at line 75 of file softwarecontainer-common.cpp.
 {
     struct stat st;
     if (getStat(path, st)) {
         return S_ISREG(st.st_mode);
     }
     return false;
 }
bool softwarecontainer::isPipe (const std::string & path)
isPipe Check if path is a pipe
Parameters
path Path to check
Returns
true/false
Definition at line 85 of file softwarecontainer-common.cpp.
 {
     struct stat st;
     if (getStat(path, st)) {
         return S_ISFIFO(st.st_mode);
     }
     return false;
 }
bool softwarecontainer::isSocket (const std::string & path)
isSocket Check if path is a socket
Parameters
path Path to check
Returns
true/false
Definition at line 95 of file softwarecontainer-common.cpp.
 {
     struct stat st;
     if (getStat(path, st)) {
         return S_ISSOCK(st.st_mode);
     }
     return false;
 }
bool softwarecontainer::existsInFileSystem (const std::string & path)
existsInFileSystem Check if path exists
Parameters
path Path to check
Returns
true/false
Definition at line 105 of file softwarecontainer-common.cpp.
Referenced by softwarecontainer::FileToolkitWithUndo::bindMount(), and softwarecontainer::Container::bindMountInContainer().
 {
     struct stat st;
     return getStat(path, st);
 }
ReturnCode softwarecontainer::bool2ReturnCode (bool b) inline
bool2ReturnCode Convert bool to ReturnCode
Parameters
b boolean value to be converted
Returns
ReturnCode::SUCCESS if b is true
ReturnCode::FAILURE if b is false
Definition at line 54 of file softwarecontainer-common.h.
 {
     return b ? ReturnCode::SUCCESS : ReturnCode::FAILURE;
 }
bool softwarecontainer::isError (ReturnCode code) inline
isError Check if ReturnCode indicates Error or not
Parameters
code the ReturnCode to check
Returns
true if ReturnCode::FAILURE is indicated
Definition at line 64 of file softwarecontainer-common.h.
Referenced by softwarecontainer::DBusGateway::activate(), softwarecontainer::NetworkGateway::activateGateway(), softwarecontainer::SoftwareContainerAgent::bindMount(), softwarecontainer::Netlink::checkKernelDump(), softwarecontainer::FileToolkitWithUndo::createDirectory(), softwarecontainer::Container::execute(), softwarecontainer::SoftwareContainerAgent::execute(), softwarecontainer::Netlink::findAddresses(), softwarecontainer::Netlink::findLink(), softwarecontainer::Netlink::getKernelDump(), softwarecontainer::Container::initialize(), isSuccess(), softwarecontainer::Netlink::linkDown(), softwarecontainer::Netlink::linkUp(), softwarecontainer::Netlink::Netlink(), softwarecontainer::FileToolkitWithUndo::overlayMount(), softwarecontainer::NetworkGatewayParser::parseNetworkGatewayConfiguration(), softwarecontainer::EnvironmentGateway::readConfigElement(), softwarecontainer::FileGateway::readConfigElement(), softwarecontainer::DBusGatewayInstance::readConfigElement(), softwarecontainer::DeviceNodeGateway::readConfigElement(), softwarecontainer::SoftwareContainer::resume(), softwarecontainer::DBusGateway::setConfig(), softwarecontainer::Gateway::setConfig(), softwarecontainer::Netlink::setIP(), softwarecontainer::SoftwareContainer::shutdown(), softwarecontainer::SoftwareContainer::SoftwareContainer(), softwarecontainer::Container::start(), softwarecontainer::SoftwareContainer::startGateways(), softwarecontainer::SoftwareContainer::suspend(), and softwarecontainer::DBusGateway::teardown().
 {
     return (code != ReturnCode::SUCCESS);
 }
bool softwarecontainer::isSuccess (ReturnCode code) inline
isSuccess Check if ReturnCode indicates Success or not
Parameters
code the ReturnCode to check
Returns
true if ReturnCode::SUCCESS is indicated
Definition at line 74 of file softwarecontainer-common.h.
References isError().
Referenced by softwarecontainer::PulseGateway::activateGateway(), softwarecontainer::NetworkGateway::activateGateway(), softwarecontainer::DeviceNodeGateway::activateGateway(), and softwarecontainer::NetworkGateway::readConfigElement().
 {
     return !isError(code);
 }
int softwarecontainer::waitForProcessTermination (pid_t pid) inline
waitForProcessTermination Waits for a process to terminate and then returns the status of the process terminating.
Parameters
pid the process id to wait for.
Returns
Process termination status.
Definition at line 85 of file softwarecontainer-common.h.
 {
     int status = 0;
     waitpid(pid, &status, 0);
     return WEXITSTATUS(status);
 }